### ISSUE TITLE
Java11 support

### ISSUE THREAD

**Issue by dantefff** [broadinstitute/gatk#7333] opened 2021-06-30 09:00 UTC
### Description
Now that java8 support has been dropped on some major linux distributions, I think would be nice to have official java11 support in GATK. I know that I can compile in java11, but the only reference I could find (from 2019) says it is an experimental support only.

**Comment by lbergelson** [comment] 2021-06-30 18:01
Hi @dantefff.  We're planning on officially moving GATK to use java 11 by default in the relatively near future.  I don't have an exact timeline.  It's definitely annoying to not have it work out of the box on most linux systems and it's something we want to do soon.  I have had very limited bandwidth lately and updating to 11 has been a casualty of that.  Now that the world is rebooting things should start to tick along faster and I hope to have it updated soon.

**Comment by dantefff** [comment] 2021-06-30 20:59
Hi @lbergelson ,
Compile it from sources is not a major issue for me. Can I understand for your words that current master branch from github is reasonably tested in Java11?
Best regards

**Comment by dantefff** [comment] 2021-07-07 08:38
Java11 compiled versions will crash with UnsupportedOperationException. I created a new issue and a pull request for this: #7338

**Comment by gokalpcelik** [comment] 2021-07-08 11:44
openjdk-8 can still be found on many major distributions albeit it is not the default one to be installed. Just check the package manager for openjdk-8 tags. 
If not check adoptopenjdk repos to install one from there. Or use the docker image.

**Comment by dantefff** [comment] 2021-07-08 13:22
> openjdk-8 can still be found on many major distributions albeit it is not the default one to be installed. Just check the package manager for openjdk-8 tags.
> If not check adoptopenjdk repos to install one from there. Or use the docker image.

That's true now, but it is matter of months not being.

**Comment by droazen** [comment] 2021-07-19 18:28
Closing as dupe of https://github.com/broadinstitute/gatk/issues/6671. Java 11 support is definitely on our roadmap for this year!

**Closed by droazen** 2021-07-19 18:28 UTC
