### ISSUE TITLE
System.exit in Main.java lead to a failure in yarn cluster mode

### ISSUE THREAD

**Issue by popboy126** [broadinstitute/gatk#3166] opened 2017-06-26 14:07 UTC
Line 154(System.exit(0)) in Main.java will lead a unormal exitcode(143) for a container in yarn cluster mode. Remove this will get the correct output.
` final Object result = runCommandLineProgram(program, args);
            handleResult(result);
            //System.exit(0);`

**Comment by lbergelson** [comment] 2017-07-05 19:34
This is a duplicate of https://github.com/broadinstitute/gatk/issues/2666.

**Closed** 2017-08-08 20:20 UTC
Labels: bug, Spark
