### ISSUE TITLE
GenotypeGVCFs / NoClassDefFoundError: org/broadinstitute/hellbender/relocated/com/google/common/base/Function

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#7675] opened 2022-02-15 22:24 UTC
Hello,

I am running GATK GenotypeGVCFs v4.2.5.0 using a command similar to the one below. I downloaded the gatk ZIP from github, unzipped, and we run the local JAR (renamed to GenomeAnalysisTK4.jar). I am consistently getting a strange NoClassDefFoundError error (below). I noticed com/google/common/base is relocated in the shadowJar step, and that is the class it's complaining about here. Have you seen an error like this before?

```
/home/exacloud/gscratch/prime-seq/java/java8/bin/java \
	-Djava.io.tmpdir=<path> \
	-Xmx178g -Xms178g \
	-Xss2m \
	-jar GenomeAnalysisTK4.jar \
	GenotypeGVCFs \
	-R 128_Mmul_10.fasta \
	--variant gendb:///home/exacloud/gscratch/prime-seq/cachedData/16b9ede7-6db8-103a-9262-f8f3fc86a851/WGS_Feb22_1852.gdb \
	-O /home/exacloud/gscratch/prime-seq/workDir/1bb5295c-6ec5-103a-8692-f8f3fc86cd3f/Job1.work/WGS_pre-mGAPv2.3_1852.vcf.gz \
	--annotate-with-num-discovered-alleles \
	-stand-call-conf 30 \
	--max-alternate-alleles 6 \
	--force-output-intervals mmul10.WGS-WXS.whitelist.v2.3.sort.merge.bed \
	-L 1:1-3714165 \
	--only-output-calls-starting-in-intervals \
	--genomicsdb-shared-posixfs-optimizations
```

and the exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/broadinstitute/hellbender/relocated/com/google/common/base/Function
	at org.broadinstitute.hellbender.Main.<clinit>(Main.java:45)
Caused by: java.lang.ClassNotFoundException: org.broadinstitute.hellbender.relocated.com.google.common.base.Function
	at java.net.URLClassLoader$1.run(URLClassLoader.java:370)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:716)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)

```

**Comment by droazen** [comment] 2022-02-15 22:29
@bbimber The underlying error (`ZipException: invalid LOC header (bad signature)`) suggests that there might be an issue with the JAR file being corrupt. Can you try re-downloading the GATK from github and seeing if the problem persists? It would also be helpful if you could post the MD5 of the JAR file you're running (generated via the command `md5sum <jar_file>`)

**Comment by bbimber** [comment] 2022-02-15 22:31
I thought that at first too. I re-downloaded and for the same error.  The md5sum is (I dont know if filename matters for this):

ca9b358340abbe146ecdd1e83c39cad4  ../bin/GenomeAnalysisTK4.jar

**Comment by bbimber** [comment] 2022-02-15 22:35
After yet one more re-download, the "pristine" JAR from github (https://github.com/broadinstitute/gatk/releases/download/4.2.5.0/gatk-4.2.5.0.zip), comes out the same:

ca9b358340abbe146ecdd1e83c39cad4  ./gatk-4.2.5.0/gatk-package-4.2.5.0-local.jar

**Comment by droazen** [comment] 2022-02-15 22:39
@bbimber Can you try building the GATK 4.2.5.0 zip from source using the command `./gradlew bundle`, and report whether the issue persists?

**Comment by bbimber** [comment] 2022-02-15 23:51
OK, so that involved jumping through a bunch of hurdles. i ended up using your docker image to check out and build the project (based on the 4.2.5.0 tag). copied that JAR out, and re-tried on our cluster.  I grabbed the JAR in the build -> "bundled resources" folder, named: gatk-package-4.2.5.0-SNAPSHOT-local.jar. I think this is the shadow JAR, but nothing was explicitly named that.

From here, I restarted my jobs, but unfortunately I'm actually getting different ClassNotFoundException errors: 

```
15 Feb 2022 15:46:19,117 DEBUG: 	Exception in thread "main" java.lang.NoClassDefFoundError: htsjdk/samtools/FileTruncatedException
15 Feb 2022 15:46:19,123 DEBUG: 		at htsjdk.samtools.util.BlockCompressedOutputStream.close(BlockCompressedOutputStream.java:355)
15 Feb 2022 15:46:19,128 DEBUG: 		at htsjdk.samtools.util.BlockCompressedOutputStream.close(BlockCompressedOutputStream.java:333)
15 Feb 2022 15:46:19,150 DEBUG: 		at htsjdk.variant.variantcontext.writer.IndexingVariantContextWriter.close(IndexingVariantContextWriter.java:172)
15 Feb 2022 15:46:19,160 DEBUG: 		at htsjdk.variant.variantcontext.writer.VCFWriter.close(VCFWriter.java:233)
15 Feb 2022 15:46:19,169 DEBUG: 		at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.closeTool(GenotypeGVCFs.java:297)
15 Feb 2022 15:46:19,180 DEBUG: 		at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1091)
15 Feb 2022 15:46:19,185 DEBUG: 		at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
15 Feb 2022 15:46:19,190 DEBUG: 		at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
15 Feb 2022 15:46:19,212 DEBUG: 		at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
15 Feb 2022 15:46:19,217 DEBUG: 		at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
15 Feb 2022 15:46:19,223 DEBUG: 		at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
15 Feb 2022 15:46:19,229 DEBUG: 		at org.broadinstitute.hellbender.Main.main(Main.java:289)
15 Feb 2022 15:46:19,235 DEBUG: 	Caused by: java.lang.ClassNotFoundException: htsjdk.samtools.FileTruncatedException
15 Feb 2022 15:46:19,242 DEBUG: 		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
15 Feb 2022 15:46:19,249 DEBUG: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
15 Feb 2022 15:46:19,258 DEBUG: 		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
15 Feb 2022 15:46:19,265 DEBUG: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by lbergelson** [comment] 2022-02-16 18:41
I can't reproduce this yet.  I tried downloading the jar, unzipping it, and running the example command you gave, but I can't reproduce what you're seeing.

I modified it for my local files:
```
ava -jar gatk-package-4.2.5.0-local.jar \
        GenotypeGVCFs \
        -R /Users/louisb/Workspace/gatk/src/test/resources/large/Homo_sapiens_assembly19.fasta.gz \
        --variant gendb:///Users/louisb/Workspace/gatk/output \
        -O out.vcf \
        --annotate-with-num-discovered-alleles \
        -stand-call-conf 30 \
        --max-alternate-alleles 6 \
        --force-output-intervals 20 \
        -L 20 \
        --only-output-calls-starting-in-intervals \
        --genomicsdb-shared-posixfs-optimizations
```
It runs to completion on my machine.  
My md5sum matches yours so that's not the problem.

It's not clear to me what's going on here.  Are the previous releases working on your cluster still?

**Comment by lbergelson** [comment] 2022-02-16 18:44
Unrelatedly, I'm a bit curious about what hoops you had to jump through to get the build from source to work.

**Comment by droazen** [comment] 2022-02-16 18:45
@bbimber Could you please try running the following command on your GATK jar:

```
jar tvf GenomeAnalysisTK4.jar
echo $?
```

Then see whether the `jar` command reports any error, and whether the `echo` command shows an exit status of 0 for the command.

Also try running this:

```
jar tvf GenomeAnalysisTK4.jar | grep -i FileTruncatedException
```

You should get output like:

```
   765 Wed Mar 17 12:09:12 EDT 2021 htsjdk/samtools/FileTruncatedException.class
```

Lastly, can you paste your complete Java classpath here?

We just checked the official release jar on github ourselves for corruption, and it seems fine, so we're not sure what's causing this issue on your end.

**Comment by lbergelson** [comment] 2022-02-16 18:48
To follow that up, I see the same md5 for the unpacked local jar as you had, so I don't think there's something wrong with your download.

`gatk-package-4.2.5.0-local.jar` is indeed the shadow jar you're looking for.  We make 2 different ones so they have more specific names than "shadow".  `gatk-package-4.2.5.0-spark.jar` is the other one.

**Comment by bbimber** [comment] 2022-02-16 18:48
@lbergelson thanks for following up. To the first part:

```
jar tvf GenomeAnalysisTK4.jar
echo $?
```
returns 0. and this is:
```
jar tvf ../bin/GenomeAnalysisTK4.jar | grep -i FileTruncatedException
   765 Wed Mar 17 12:09:12 PDT 2021 htsjdk/samtools/FileTruncatedException.class
```
so seems ok. I will talk to the group that manages the cluster. one out there possibility is that this is based on a lustre filesystem, and there could be some cryptic cluster-specific access issue. i have no specific reason to believe this, but weird things have happened.

**Comment by bbimber** [comment] 2022-02-16 18:51
To the question on building it: I guess it isnt really a problem with your build per-se, but rather it seems to make a variety of assumptions or requirements on the environment that were difficult to replicate on our cluster (where i lack admin privs). Using your docker image was the faster way i could find to replicate the needed environment. Issues I hit included: 1) needed git lfs installed (on cluster i lack sudo/apt access), 2) gradle complained about building on the lustre filesystem, so i needed to move to other disks.

**Comment by lbergelson** [comment] 2022-02-16 19:12
Huh, I wonder why gradle doesn't like a lustre system.  I didn't now that was an issue.  Git-lfs is an annoyance to install if you don't have access to a package manager.  I *think* it can be installed without sudo but I get why that's a pain.  I've spent a non-zero amount of time fighting with git-lfs installation before. Thank you for elaborating!

**Comment by bbimber** [comment] 2022-02-16 19:13
@lbergelson yes, those things might have been possible, but once i hit more than one snag, docker seemed much more appealing.

**Comment by lbergelson** [comment] 2022-02-16 19:30
Yes, using docker makes sense!

**Comment by droazen** [comment] 2022-02-28 19:45
Closing this one since we can't replicate it on our end

**Closed by droazen** 2022-02-28 19:45 UTC
