### ISSUE TITLE
ReadsSparkSink.writeReadsSingle is too slow

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#940] opened 2015-10-01 01:39 UTC
I tested on a 30Gb file, trying to write to HDFS. It wrote more than 1.4 TB to disk and took hours to complete.

**Comment by droazen** [comment] 2015-10-19 19:25
Dupe of https://github.com/broadinstitute/gatk/issues/1015 -- closing

**Closed** 2015-10-19 19:25 UTC
Labels: Spark
