### ISSUE TITLE
allow for no decimal point in float INFO fields

### ISSUE THREAD

**Issue by pontikos** [broadinstitute/gatk#5789] opened 2019-03-12 18:06 UTC
bcftools removes decimal point when there are trailing zeroes:
https://github.com/samtools/bcftools/issues/980

GATK should be able to handle floating points without a decimal point.

**Comment by lbergelson** [comment] 2019-03-12 18:11
Is this specifically a problem filtering VCF's with filter expressions written in jexl?  Or are you hitting it somewhere else as well?

**Comment by pontikos** [comment] 2019-03-12 18:23
The gVCF has been generated using "bcftools view" to extract samples.  Type
floats in the INFO field which have trailing zeroes after the decimal point
are rounded by bcftools to integers e.g: `70.0` becomes `70`
This breaks the GATK combineGVCFs code.  I know this is the bug because
when I add back `.0`, GATK works again.

I'm using GATK 3.5

**Comment by lbergelson** [comment] 2019-03-12 18:58
Any chance you could test with GATK 4.1.0.0 to make sure it's still happening?  GATK 3.5 is no longer maintained.

**Comment by pontikos** [comment] 2019-03-12 20:24
Sorry but I am stuck with using GATK 3.5 at the moment as they are too many difference between GATK 4 and GATK 3.

**Comment by lbergelson** [comment] 2019-03-12 22:08
Ok.  I'm sorry, but we're unable to help you then.  GATK 3 is no longer maintained or updated.  We recommend everyone upgrades to 4.  The differences between 3 and 4 are only going to increase over time.  

Is there a specific missing feature preventing you from upgrading?  Or some issue that manifests in 4 but not 3?

**Comment by ldgauthier** [comment] 2019-03-14 15:24
@pontikos if you use the issue template we might be able to help.

### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_

### Affected version(s)
- [ ] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem. (The support team may follow up to ask you to upload data to reproduce the issue.)_

**Comment by lbergelson** [comment] 2019-05-22 20:08
Closing since the bug was reported against GATK 3.

**Closed by lbergelson** 2019-05-22 20:08 UTC

**Comment by cmnbroad** [comment] 2019-05-22 20:47
FWIW, this issue was fixed in GATK a while back. It sounds exactly like https://github.com/broadinstitute/gatk/issues/4633, which was fixed in https://github.com/broadinstitute/gatk/pull/4680.
