### ISSUE TITLE
Too many alleles warning in GenotypeGVCFs

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/gatk#2688] opened 2017-05-09 19:06 UTC
running GenotypeGVCFs on test data produced warnings such as

`Column 948660 has too many alleles in the combined VCF record : 61 : current limit : 50. Fields, such as  PL, with length equal to the number of genotypes will NOT be added for this location.`

It seems like the limit might need to be raised / raisable ?

**Comment by droazen** [comment] 2017-05-09 19:08
Closing -- duplicate of https://github.com/broadinstitute/gatk/issues/2687

**Comment by Horneth** [comment] 2017-05-09 19:09
oops sorry -_-

**Closed by droazen** 2017-05-09 19:08 UTC
