### ISSUE TITLE
fix and reenable cloud tests in BaseRecalibratorSparkIntegrationTest

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1118] opened 2015-11-13 20:57 UTC
the testPlottingWorkflow in BaseRecalibratorSparkIntegrationTest is disabled because it uses a bogus expected file. Needs to be fixed and reenabled

**Comment by droazen** [comment] 2016-01-05 22:43
Closing -- dupe of https://github.com/broadinstitute/gatk/issues/1192

**Closed by droazen** 2016-01-05 22:43 UTC
Labels: Spark, tests
