### ISSUE TITLE
Tumor-in-normal and PoN creation from mixed-N/T cohorts

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3004] opened 2017-06-05 20:45 UTC
@mbabadi commented on [Fri May 19 2017](https://github.com/broadinstitute/gatk-protected/issues/1069)

This is a long shot, but the idea is to be able to learn biases from mixed N/T cohorts. In a way, this is similar to semisupervised learning where the _stiff_ integer-state HMM on normal samples lead the way of learning biases (as a matter of imposing a strong copy-neutrality prior), and tumor samples along with a _loose_ infinite HMM provide additional (though generalically less) statistical power.

Weak tumor-in-normal contamination can be handled using an adaptive integer-state HMM where the quantizied copy ratio states are chosen uniformly, though, adaptively.

In the future, we must move toward a generic CLI tool called something like FancySchmancyCNVCaller that can perform the following tasks in its idealized form:

- create PoN and make calls from normals
- create PoN and make calls from tumors (possible with iHMM)
- create PoN and make calls from mixed normals and tumors (possible with iHMM)
- make calls from a given model on normals
- make calls from a given model on tumors
- make calls from a given model on mixed normals and tumors

The tool would then additionally take a sample annotation table (normal, tumor) and perform its job. For the first release, all samples have be annotated as normal; otherwise, an UnsupportedFeatureException is thrown.

**Comment by samuelklee** [comment] 2019-01-31 15:03
Dupe of #4116.

**Closed by samuelklee** 2019-01-31 15:03 UTC
Labels: Copy Number tools
