### ISSUE TITLE
port VariantEval

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#616] opened 2015-07-08 14:30 UTC
the requirement is to port the VariantEval walker and all tests. For now, the combinatorial nature of the eval is to be ported. (later on we may split it into multiple tools and a pipeline)

**Comment by akiezun** [comment] 2016-02-18 03:32
@vdauwera @ldgauthier my understanding now is that VariantEval is to be phased out in favor of improving CollectVariantCallingMetrics. Yes?

**Comment by vdauwera** [comment] 2016-02-18 03:39
Yes, with the caveat that VariantEval offers a lot of capabilities that CollectVariantCallingMetrics does not, so the latter will need quite a lot of improvement in order to replace VE.

**Comment by akiezun** [comment] 2016-02-18 03:49
can you list here the capabilities we need? Here's what I got from @ldgauthier:

```
1. TiTv and Indel ratios are only for dbsnp and novel and there is no ratio for total and/or no way of calculating it.
2. Related to above, would like to see total number of insertions, deletions, transitions, transversions, het alt and hom alts.
3. % missingness or a similar metric
4. % GQ=0
```

**Comment by vdauwera** [comment] 2016-02-24 21:16
That looks about right to start with. We may need to add things later but this covers the major use cases.

**Comment by bbimber** [comment] 2017-08-07 18:06
Posting at the suggetion of shlee.  There's discussion about what parts of VariantEval will be ported to GATK4 or whether Picard's partially overlapping tool CollectVariantCallingMetrics will take this over.  I want to at least make you aware that we've developed a tool we're calling VariantQC, which is built in GATK3 and runs VariantEval internally to generate data stratified in various ways to make HTML QC reports, sorta like FASTQC or MultiQC (https://github.com/bbimber/gatk-protected/releases).  An example report is here: https://prime-seq.ohsu.edu/_webdav/Internal/Bimber/Public/%40files/VariantQC_Example.html

Our goal was always to port this to GATK4, polish it up, and then make it more generally available.   Much of what this tool does is take the pre-built tables/reports from VariantEval and put them into HTML, but we also wrote some custom stratifications to bin data by filter, etc.  Like this thread notes, VariantEval has a lot of features not in picard, and honestly we dont use many of them.  However, the extensibility of Stratifier/VariantEvaluator are pretty important for us.  

We realize this is prioritized against all the GATK4 features; however, 1) how set are plans about migration of VariantEval/merge w/ picard and 2) if most of VariantEval isnt going to be ported, can we pick it up in our repo?  We could also potentially offer some assistance in porting the tool because we have a vested interest; however, unless the task is defined as porting VariantEval as close as possible to as-is (not that this is critical, but it's the simplest thing for the outsider to do), it would need some discussion around exactly what's planned.

**Comment by droazen** [comment] 2017-08-07 19:26
@bbimber We're not opposed to the idea of porting `VariantEval` if it's useful to the community -- the problem is finding time to do so with all of the other GATK4-related projects going on right now, particularly with a viable alternative tool in Picard. However, if someone (such as yourself) were to submit a pull request with a straightforward 1:1 port of the tool from GATK3 with the absolute minimum necessary changes, I think we'd be inclined to accept it. Most GATK3 tools port fairly cleanly to GATK4, provided that you're porting it as a walker rather than as a Spark tool. If you were to take this task on, we'd be happy to offer advice/support on technical issues related to the port.

**Comment by bbimber** [comment] 2017-08-07 19:51
Alright - I'll see how much time people have here (@melissayan - any interest?)

Has anyone on your side done investigation or put thought into merging the tools beyond the little on this thread?  I'm not wholly opposed to slimming it down if we can preserve the tiny bit of it we need (stratifications/VariantEvaluator modules), though I'm worried the scope of what that would take pretty rapidly increases.

**Comment by droazen** [comment] 2017-08-07 20:01
There aren't any plans to add the module functionality from `VariantEval` to the Picard tool. It would almost certainly be easier to do a straightforward port of `VariantEval` to GATK4 than to try to perform major surgery on `CollectVariantCallingMetrics` in Picard.

**Comment by bbimber** [comment] 2017-08-09 00:44
Alright, @melissayan will give a straight port a try.

**Comment by droazen** [comment] 2017-08-09 13:00
Great to hear! If you need any help during the porting process, just comment here and we'll respond.

**Comment by bbimber** [comment] 2017-10-17 17:58
hi guys,

we've finally had some time to look over this.  A few initial questions:

1) Is there a great for RefMetadataTracker?  For example, in VariantEval, it is used like:

//context = RefMetadataTracker
nProcessedLoci += context.getSkippedBases() + (referenceContext == null ? 0 : 1);

In GATK3, many walkers also tested for tracker!=null.  Are there general rules on what is or isnt @Nullable on the arguments to apply()?

2) Is there a parallel to the annotation @Input in GATK4?  Most of the time these are referring to files, and near as I can tell the way GATK4 does this is to primarily define the field as FeatureDataSource.  So the GATK4 version would be:

@Argument(fullName="stratIntervals".......)
public FeatureDataSource<Feature> intervalsFile = null;

3) Exceptions seem to have also changed a fair amount.  for exception classes that no longer exist in GATK4, I'm trying to make guesses based on tools that have already been ported that also used the exception class in question.   The most frequent change I see is things like UserException.BadArgumentValue (which explicitly accepts the argument names) not existing.  I've been converting these to UserException, which no longer explicitly holds argument names.  Did this become something different in GATK4?

Thanks

**Comment by bbimber** [comment] 2017-10-17 19:19
Another question: is there a way to get the test data used for GATK3 and VariantEval?  Even if they're not small enough to reasonably check in, it would be at least useful to use that integration test as a way to validate it's working as expected in GATK4.

**Comment by magicDGS** [comment] 2017-10-18 13:54
@bbimber - here some answers:

* The `LocusWalker` in the GATK4 framework provides the traversal over each locus, and provides the information for the reference (`ReferenceContext`) and the pileup (`AlignmentContext`). I guess that this is similar to a rod-walker in the previous framework if a  `FeatureInput` is present (accessed by the `FeatureContext`)
* The apply function params are never null, but they may be empty. The reference context could be tested if it is empty by using `hasBackingDataSource()`. Other contexts can be tested with other methods to check if they are empty.
* For auto-discovery of feature inputs, mark the field with `FeatureInput<>` for the type of feature that you want; if you require more than one, a list of `FeatureInput` can be provided. Then, the features for the feature class can be retrieved from the `FeatureContext` on the apply function.
* For argument exceptions, use the ones in `UserException` or `CommandLineProgramException`, depending on which one fits better on your use case...

If you wanna check an example of a locus walker with features, see [`ExampleLocusWalker`](https://github.com/broadinstitute/gatk/blob/4ef87ca10c3b57af76d829995e532c279b17cff2/src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleLocusWalker.java).

I hope that it helps!

**Comment by bbimber** [comment] 2017-10-18 18:51
Thanks, that's a start.  If anyone on the GATK team has thoughts about the other two questions about GenomeLocParser or getting test data, I'd appreciate it.  

Based on Daniel's reply: In the GATK3 VariantEval, the walker is counting traversed loci by checking AlignmentContext.getSkippedBases(), and then adding 1 if referenceContext is non-null.  From his reply, does this mean it now calls apply() at every locus, meaning getSkippedBases() is irrelevant?  In GATK3, would getSkippedBases have come into play if there was zero coverage at a locus?  In GATK4, would ReadsContext.getInterval() be the appropriate way to count number of loci being inspected in apply() then?

**Comment by magicDGS** [comment] 2017-10-19 09:16
@bbimber, you can configure the `LocusWalker` to traverse every locus even if it is empty and thus the `getSkippedBases()` is unnecessary. Another option is to track the previous `AlignmentContext` and compare the location with the current one, to check how many bases have been skipped....

**Comment by bbimber** [comment] 2017-11-10 19:26
Hello,

I think we're pretty close on porting this.  However, i wanted to ask again if I could get access to the test data used in GATK3 VariantEvalWalkerUnitTest and VariantEvalIntegrationTest.  We dont need to port those files to GATK4 unless some of them already exist; however, having these files would help confirm the ported tool is behaving exactly as GATK3.

Second, I am hoping to confirm a behavior for FeaureContext: many GATK3 stratifiers follow roughly this pattern (VariantEval / knownCNVsFile being an example).  The pattern is: 1) some VCF/BED file provided as an argument, 2) in initialize(), the walker reads this file in memory into a List<GenomeLoc> or IntervalTree<GenomeLoc>.  This is so each locus can quickly find overlapping intervals.  In GATK4, there is no longer a point in loading the whole file into memory, right?  If I define an argument as FeatureInput<Feature>, it will automatically be initialized.  FeatureContext.getValues() seems to give me overlapping intervals (including partial overlaps).  Therefore there is no reason to try to replicate that GATK3 pattern of reading intervals into memory.  Can someone confirm this is correct?

**Comment by bbimber** [comment] 2017-11-10 20:28
Also, in GATK3, PluginManager was used to lookup plugin w/ Reflection, such as:

new PluginManager<RequiredStratification>(RequiredStratification.class).getPlugins())

Is there a similar concept in GATK4?

**Comment by magicDGS** [comment] 2017-11-11 16:55
@bbimber - using the `FeatureContext` to get the overlapping BED/VCF records should do the job (for the first message, second part).

Regarding the `PluginManager`, I am not familiar with the GATK3's concept. If you are talking about the plugins like  `ReadFilter`s, you can retrieve them by using: `getCommandLineParser().getPluginDescriptor(RequiredStratification.class)`. This will get the plugin descriptor already parsed by the command line. But for that, you need to have a `RequiredStratification` plugin...

**Comment by bbimber** [comment] 2017-11-13 19:02
@magicDGS - thanks again for the help on this.  yes, GATKReadFilterPluginDescriptor seems somewhat like the same concept as GATK3's PluginManager.  Some of the not-yet-ported tools like VariantAnnotator used the plugin idea more heavily as well, so perhaps that'll get built out more when those are ported?  I will work with that and perhaps try to pull out an AbstractPluginDescriptor.

@droazen - in the earlier post you mentioned support on porting this.  i think we're almost done, but it would be really helpful to test this using the same test data as GATK3 to ensure identical behavior.  I dont know if there's any issues preventing sharing those files, but it seems like sharing those, at least privately wit us, should be a relatively straightforward thing.  We're happy to do all that testing, if we could just get that test data.  Sorry to keep bugging you on this point, but it'd be helpful if someone from GATK could reply on whether this is a possibility.  Thanks.

**Comment by bbimber** [comment] 2018-01-13 17:29
hi gatk team - i realize you have a lot of other issues and porting VariantEval isnt high on that, but I'm really hoping we can close this out.  We are thankful for the original offer of support by @droazen , but there's been no replies to this thread by GATK staff since then.  we have VariantEval essentially working on GATK4; however, I would really like to get the GATK3 test data used by VariantEval since that's probably the easiest way to verify behavior is consistent.  i dont plan to use those files verbatim in GATK4, but offline testing using them just makes sense.  Could we either find a way to get these files, or can you reply if there is some reason this is not possible?  We basically need the files referenced in VariantEvalIntegrationTest.  If any are public (like the genome or dbSNP builds?), pointers would be appreciated to make sure we're using the exact right file:

References: 
b37KGReference = "/humgen/1kg/reference/human_g1k_v37.fasta";
b37dbSNP132 = "/humgen/gsa-hpprojects/GATK/data/dbsnp_132_b37.vcf";
    
And then the contents of this directory, which seems to be VariantEval-specific files:
variantEvalTestDataRoot = privateTestDir + "VariantEval/";

Could we please find a way to get these files or definitively say we're not going to be able to get them?

Thanks.

**Comment by droazen** [comment] 2018-01-16 16:58
Apologies @bbimber -- your efforts to port this tool to GATK4 are much appreciated. Our team has been extremely busy with the lead up to the 4.0 release, which is why we haven't been as responsive lately. I'll have someone take a look at the test data in question to see if it can be publicly shared.

**Comment by bbimber** [comment] 2018-01-16 17:02
I fully understand, and realize this isnt a priority for the group.  Nonetheless, just getting the test data seems like it should be a simple thing if at all possible.  i dont know the full reasoning behind why the GATK3 test data are not public, but I have no need to share it beyond myself if that makes this easier.

**Comment by droazen** [comment] 2018-01-16 17:08
@bbimber Unfortunately it's not so simple -- some of the GATK3 test data cannot be shared externally at all due to, eg., IRB restrictions. Someone will have to look at the test data in question to make sure that it can be shared. We'll update you once we've done this.

**Comment by bbimber** [comment] 2018-01-16 17:14
Ok, glad this is not the case in GATK4. I tried to list the files I think I ideally need above. VCFs are unfortunately probably the most likely category of file to run into IRB concerns.

**Comment by droazen** [comment] 2018-01-16 17:16
Yes, with GATK4 we made the decision early on that all test data must be publicly-shareable and checked into the repo. This has often meant that when we port a tool from GATK3 to GATK4, we need to rewrite the tests to use different test data.

**Comment by bbimber** [comment] 2018-01-16 17:21
Yeah, I expect to need to rewrite tests for the final port. Thanks for any help on the validation data.

**Comment by ldgauthier** [comment] 2018-01-16 18:06
@droazen Those data are fine to share.  The resources/VariantsEval/*.vcf are all either anonymized or (public) 1000G samples.  @bbimber since we now include all the test data in the repo, we restrict ourselves to chromosomes 19 and 20 (there should already be a chromosome 19 and 20 reference fasta in the repo and probably the dbsnp too).  Most of the files use just variants from 20, but MendelianViolationEval data is on chromosome 1 and will need to be modified.  I'd love for all our test data to be valid VCFs, so I wouldn't want to just change 1 to 20 (because the reference allele won't match).  Maybe there's a quick and dirty way to change the alleles?

**Comment by droazen** [comment] 2018-01-16 18:09
@ldgauthier Great, thanks for checking. 

It's actually chromosomes 20 and 21 that we typically restrict ourselves too, by the way. The complete reference sequences for them for both b37 and hg38 are in `src/test/resources/large`

**Comment by droazen** [comment] 2018-01-16 18:11
Any test data larger than about 1-2 MB we typically put into `src/test/resources/large` and check into git lfs, by the way (see https://github.com/broadinstitute/gatk#lfs for setup/usage instructions)

**Comment by bbimber** [comment] 2018-01-17 20:23
OK, got lfs working.  I understand the reasoning for limiting to 20-21 and will do this when i rewrite the GATK3 tests in the port.  However, for the purpose of verifying consistent behavior of this ported tool would be great to use the same resources as GATK3.  Since it seems like this is shareable, would it still be possible to get the full genome versions of:

/humgen/1kg/reference/human_g1k_v37.fasta (and FAI, dict)
/humgen/gsa-hpprojects/GATK/data/dbsnp_132_b37.vcf + index?

While i can probably figure out the right version off public databases, these are outdated and it would be preferable to get exactly what GATK3 uses just in case there's a difference.  

Beyond that, glad to hear it seems like /VariantEval/* is OK to share too.  I'm happy to provide a place these could be uploaded, or download from you guys.  

Thanks again for the help.

**Comment by bbimber** [comment] 2018-01-25 19:46
Hi guys,

In case it helps, here's an upload site that could be used for these GATK3 test data, either uploading through the browser:

https://prime-seq.ohsu.edu/project/Internal/Bimber/GATK/begin.view?

or command line (-T for file name(s)), note the user/password:

curl --basic -T foo.txt -u "gatk_upload@gatk.com:genomes" https://prime-seq.ohsu.edu/_webdav/Internal/Bimber/GATK/@files/

I'll delete that temporary user and dropbox once finished, so i'm not that worried about posting credential in this public forum.  I'm also happy to download from somewhere if that's an option.

The post above summarizes the files we're hoping to get.

Thanks again for the help,
Ben

**Comment by droazen** [comment] 2018-01-25 19:51
@bbimber Thanks -- I think we'll upload the files to a public Google storage bucket instead, to avoid the need for sharing passwords out in the open like this. We should be able to get to this after the GATK point release goes out tomorrow. I'll make a post here once they're uploaded.

**Comment by bbimber** [comment] 2018-01-25 19:58
yes, not the best way to sharing passwords, but this particular account isnt much more than a guest for this one transaction.  google is fine - thanks for your help here.

**Comment by jamesemery** [comment] 2018-02-02 22:26
@bbimber I just uploaded the the test files from GATK3 and a copy of the reference and DBSNP to the following bucket gs://variant-eval-test-data/.

**Comment by bbimber** [comment] 2018-02-05 21:03
@jamesemery: thank you.  however, I am probably missing something obvious here.  i tried to access this using 'gsutil cp'; however, i get an AccessDeniedException: bbimber@gmail.com does not have storage.objects.list access to variant-eval-test-data.  Should I, and/or is there another way to access this?

**Comment by jamesemery** [comment] 2018-02-05 21:09
Can you try it again now? We might have fixed it.

**Comment by bbimber** [comment] 2018-02-16 04:19
Thanks, this largely worked.  However, would it be possible to also get the contents as validationDataLocation, which is 

/humgen/gsa-hpprojects/GATK/data/Validation_Data/

**Comment by bbimber** [comment] 2018-02-16 05:14
@jamesemery : i have run all integration tests, and I think this is a complete list of the remaining files I can hopefully get:

/private/gatk-tools-private/src/test/resources/withSymbolic.b37.vcf
/private/gatk-tools-private/src/test/resources/PhaseByTransmission/PhaseByTransmission.IntegrationTest.TP.vcf  
/private/gatk-tools-private/src/test/resources/yri.trio.gatk_glftrio.intersection.annotated.filtered.chr1.vcf 
/private/gatk-tools-private/src/test/resources/NA12878.HiSeq.WGS.b37_decoy.indel.recalibrated.vcf 
/private/gatk-tools-private/src/test/resources/validationReportEval.noGenotypes.vcf 
/private/gatk-tools-private/src/test/resources/validationReportEval.vcf 
/private/gatk-tools-private/src/test/resources/ac0.vcf 
/humgen/gsa-hpprojects/GATK/data/Comparisons/Validated/HapMap/3.3/genotypes_r27_nr.b37_fwd.vcf
/humgen/gsa-hpprojects/GATK/data/Validation_Data/snpEff2.0.5.AFR.unfiltered.VariantAnnotator.output.vcf

Thanks.

**Comment by jamesemery** [comment] 2018-02-16 19:09
@bbimber I think I uploaded them all though `/private/gatk-tools-private/src/test/resources/yri.trio.gatk_glftrio.intersection.annotated.filtered.chr1.vcf` doesn't exist in the gatk3 repo as named. I grabbed each of the versions that followed the naming convention for you though.

**Comment by bbimber** [comment] 2018-02-17 00:46
@jamesemery - Thanks.  In the code, that file is referenced both in VariantEvalIntegrationTest.testSelect1(), and also in CombineVariantsIntegrationTest.uniqueSNPs().  If those pass, it must exist somewhere?

**Comment by bbimber** [comment] 2018-02-19 20:49
@jamesemery - i will also look into whether this file is somehow created by subsetting another during tests.  in the meantime, would it be possible to also get these?  i'm pretty confident this is the final list:

gsa-hpprojects\GATK\data\Comparisons\Validated\HapMap\3.3\genotypes_r27_nr.b37_fwd.vcf

and the following are in privateTestDir:

overlapTest.bed
PhaseByTransmission/PhaseByTransmission.IntegrationTest.goodFamilies.ped
PhaseByTransmission/PhaseByTransmission.IntegrationTest.TP.vcf
NA12878.HiSeq.WGS.b37_decoy.indel.recalibrated.vcf
yri.trio.gatk.ug.head.vcf
NA12878.HiSeq.WGS.b37_decoy.indel.recalibrated.vcf
Mills_and_1000G_gold_standard.indels.b37.sites.vcf
validationReportComp.vcf
validationReportComp.noGenotypes.vcf

**Comment by bbimber** [comment] 2018-03-05 17:10
@jamesemery - sorry to keep bothering you on this, but is there any chance you could upload the files above?  I have GATK4 VariantEval passing using all the GATK3 tests, except for the handful of ones depending on these files.  Thanks.

**Comment by bbimber** [comment] 2018-03-05 18:55
Also - I just opened #4495 to start the process of merging this.  VariantEval is a pretty sprawling tool, so I thought it would be easier to try one PR with just those changes outside the varianteval package, and once these are worked out then I'll make another PR with VariantEval itself.

**Comment by jamesemery** [comment] 2018-03-05 19:58
@bbimber I have uploaded the files you asked for, though again I'm not finding certain files in private, namely these ones:
NA12878.HiSeq.WGS.b37_decoy.indel.recalibrated.vcf
Mills_and_1000G_gold_standard.indels.b37.sites.vcf

for the first group of files there are a number of files with the b37_decoy filename but mostly they have a different naming convention. I hope this was helpful.

**Comment by bbimber** [comment] 2018-03-05 22:25
thank you.  and those two unaccounted for files are actually in validationDataLocation, not private as I originally wrote.  That seems to be; /humgen/gsa-hpprojects/GATK/data/Validation_Data

**Comment by jamesemery** [comment] 2018-03-06 19:29
@bbimber Just uploaded the missing files from /humgen/gsa-hpprojects/GATK/data/Validation_Data. Hopefully that is everything.

**Closed** 2018-11-21 14:00 UTC
Labels: BestPracticesPipeline, PRIORITY_MEDIUM, SiteQC, VariantWalker
