### ISSUE TITLE
Non-informative error message when the reference dictionary (.dict) file is missing

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk#3492] opened 2017-08-23 18:45 UTC
Ran into this problem when the reference `.dict` file was not properly copied to the VM. The stderr reads:
```
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell_root/tmp.5EEmH0
[August 22, 2017 6:54:35 PM UTC] SparkGenomeReadCounts  --keepXYMT true --binsize 1000 --outputFile 8007540135.coverage.tsv --reference /cromwell_root/broad-dsde-methods/sv/reference/GRCh38/Homo_sapiens_assembly38.fasta --input /cromwell_root/broad-dsde-methods/mehrtash/cromwell-executions/CRAMCollectCoverage/29948994-7457-43b9-b6e3-5d188906595d/call-CramToBam/shard-0/8007540135.bam --disableSequenceDictionaryValidation true --verbosity DEBUG --disableReadFilter NotDuplicateReadFilter --disableToolDefaultReadFilters false  --readValidationStringency SILENT --interval_set_rule UNION --interval_padding 0 --interval_exclusion_padding 0 --bamPartitionSize 0 --shardedOutput false --numReducers 0 --sparkMaster local[*] --help false --version false --showHidden false --QUIET false --use_jdk_deflater false --use_jdk_inflater false
[August 22, 2017 6:54:35 PM UTC] Executing as root@d6d410d4b1c7 on Linux 4.9.0-0.bpo.3-amd64 amd64; OpenJDK 64-Bit Server VM 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11; Version: 4.beta.3-SNAPSHOT
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
17/08/22 18:54:38 INFO SparkContext: Running Spark version 2.0.2
17/08/22 18:54:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/08/22 18:54:40 INFO SecurityManager: Changing view acls to: root
17/08/22 18:54:40 INFO SecurityManager: Changing modify acls to: root
17/08/22 18:54:40 INFO SecurityManager: Changing view acls groups to: 
17/08/22 18:54:40 INFO SecurityManager: Changing modify acls groups to: 
17/08/22 18:54:40 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
17/08/22 18:54:41 INFO Utils: Successfully started service 'sparkDriver' on port 45651.
17/08/22 18:54:41 INFO SparkEnv: Registering MapOutputTracker
17/08/22 18:54:41 INFO SparkEnv: Registering BlockManagerMaster
17/08/22 18:54:41 INFO DiskBlockManager: Created local directory at /cromwell_root/tmp.5EEmH0/root/blockmgr-84cc8cba-fa27-4b62-a6f6-1c10377ddc86
17/08/22 18:54:41 INFO MemoryStore: MemoryStore started with capacity 4.1 GB
17/08/22 18:54:41 INFO SparkEnv: Registering OutputCommitCoordinator
17/08/22 18:54:42 INFO Utils: Successfully started service 'SparkUI' on port 4040.
17/08/22 18:54:42 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://172.17.0.2:4040
17/08/22 18:54:42 INFO Executor: Starting executor ID driver on host localhost
17/08/22 18:54:42 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33999.
17/08/22 18:54:42 INFO NettyBlockTransferService: Server created on 172.17.0.2:33999
17/08/22 18:54:42 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 172.17.0.2, 33999)
17/08/22 18:54:42 INFO BlockManagerMasterEndpoint: Registering block manager 172.17.0.2:33999 with 4.1 GB RAM, BlockManagerId(driver, 172.17.0.2, 33999)
17/08/22 18:54:42 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 172.17.0.2, 33999)
17/08/22 18:54:43 INFO SparkUI: Stopped Spark web UI at http://172.17.0.2:4040
17/08/22 18:54:43 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/08/22 18:54:43 INFO MemoryStore: MemoryStore cleared
17/08/22 18:54:43 INFO BlockManager: BlockManager stopped
17/08/22 18:54:43 INFO BlockManagerMaster: BlockManagerMaster stopped
17/08/22 18:54:43 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/08/22 18:54:43 INFO SparkContext: Successfully stopped SparkContext
[August 22, 2017 6:54:43 PM UTC] org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts done. Elapsed time: 0.13 minutes.
Runtime.totalMemory()=299892736
***********************************************************************

A USER ERROR has occurred: null

***********************************************************************
org.broadinstitute.hellbender.exceptions.UserException$MissingReferenceDictFile
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeReference(GATKSparkTool.java:396)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeToolInputs(GATKSparkTool.java:360)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:351)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:173)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
	at org.broadinstitute.hellbender.Main.main(Main.java:233)
17/08/22 18:54:43 INFO ShutdownHookManager: Shutdown hook called
17/08/22 18:54:43 INFO ShutdownHookManager: Deleting directory /cromwell_root/tmp.5EEmH0/root/spark-4900f4dd-59fb-4a6d-96c8-8b99edb608ab
```
I am using the docker image `broadinstitute/gatk:4.beta.3`. Here's the command line:
```
        java -DGATK_STACKTRACE_ON_USER_EXCEPTION=true -Xmx8g -jar /root/gatk.jar SparkGenomeReadCounts \
            --input /cromwell_root/broad-dsde-methods/mehrtash/cromwell-executions/CRAMCollectCoverage/29948994-7457-43b9-b6e3-5d188906595d/call-CramToBam/shard-0/8007540135.bam \
            --reference /cromwell_root/broad-dsde-methods/sv/reference/GRCh38/Homo_sapiens_assembly38.fasta \
            --binsize 1000 \
            --keepXYMT true \
            --disableToolDefaultReadFilters false \
            --disableSequenceDictionaryValidation true \
            $(if [ true = true ]; then echo " --disableReadFilter NotDuplicateReadFilter "; else echo ""; fi) \
            --outputFile 8007540135.coverage.tsv \
            --verbosity DEBUG
```

No NIO, no GCS -- everything is localized on the VM HDD at this stage.

**Comment by samuelklee** [comment] 2017-08-25 14:25
Is this the same issue as #2922?

**Comment by cmnbroad** [comment] 2017-08-27 13:50
This is caused by a bug in the MissingReferenceDictFile constructor. The code paths were different when #2922 was found, but the fix for this will fix both.

**Closed** 2017-08-29 12:23 UTC
Labels: bug, Engine, Spark
