### ISSUE TITLE
GATK4 ReadsPipelineSpark A USER ERROR: The input .bam file contains reads with no platform information

### ISSUE THREAD

**Issue by AriesLL** [broadinstitute/gatk#1949] opened 2016-06-27 21:58 UTC
Hi,
While I test a new data set from fastq using bwamem, samtools and gatk4, I use the following scripts:

% step1: bwa mem
>bwa mem -t 12 -Ma  -R '@RG     ID:HCC1954      LB:HCC1954      SM:HCC1954'  human_g1k_v37.fasta   HCC1954_1.fq     HCC1954_2.fq    >  HCC1954.sam

% step2: sort by queryname
>samtools sort -n HCC1954.sam -@ 24 > HCC1954.readnamesort.bam   

% step3: gatk4 ReadsPipelineSpark
>/gatk-launch \
ReadsPipelineSpark \
-I HCC1954.readnamesort.bam \
-R /benchmark/human_g1k_v37.2bit \
-O HCC1954.bam \
--knownSites /benchmark/dbsnp_138.b37.excluding_sites_after_129.vcf \
--shardedOutput false \
--emit_original_quals \
--duplicates_scoring_strategy SUM_OF_BASE_QUALITIES \
--sparkRunner SPARK \
--driver-memory 8G \
--executor-memory 60g \
--num-executors 1 \
--executor-cores 4 \
--sparkMaster local[4]

I encounter problem like this:

org.broadinstitute.hellbender.exceptions.UserException$MalformedRead: A USER ERROR has occurred: Read C097FACXX111207:2:2301:17281:179267 1:1139151-1139251 is malformed: The input .bam file contains reads with no platform information. First observed at read with name = C097FACXX111207:2:2301:17281:179267
        at org.broadinstitute.hellbender.utils.recalibration.RecalUtils.parsePlatformForRead(RecalUtils.java:510)
        at org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine.processRead(BaseRecalibrationEngine.java:122)
        at org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn.lambda$apply$26a6df3e$1(BaseRecalibratorSparkFn.java:33)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Then I check HCC1954.sam, and found 

@RG     ID:HCC1954      LB:HCC1954      SM:HCC1954

Since it complains no Platform information, I manually add PL:illumina to this line

then step3 works. 

My question is do you also manually add PL, platform information to the generated sam file from bwa mem?

**Comment by lbergelson** [comment] 2016-10-24 21:54
@AriesLL I think we missed this issue when it was first posted, sorry! 

I would add the read group when doing BWA mem like you suggest.  If you've already aligned the file you can manually edit the header and use `samtools reheader` with the edited header file to replace the header in a bam file.  

See [this page on read groups] for an example of all the data that tends to be put into Broad read groups (some of which GATK relies on as you discovered).

**Comment by lbergelson** [comment] 2016-10-24 21:55
I'm going to close this, let me know if that doesn't answer you're question.  (and sorry for the extremely slow response...)

**Closed by lbergelson** 2016-10-24 21:55 UTC
Labels: community-request

**Comment by vdauwera** [comment] 2016-10-24 21:58
FYI an easier way than reheadering the bam file, if there's only one or a subset of read group components missing, is to use Picard AddOrReplaceReadGroup.

**Comment by lbergelson** [comment] 2016-10-24 22:03
Ah, good point.  Forgot about that.

**Comment by PlatonB** [comment] 2020-07-27 11:28
@lbergelson The problem is reproduced with such serious and supervised FASTQs as 1000 Genomes reads and some of the SRRs. Why can't it be implemented as a warning in ReadsPipelineSpark instead of a crash?
