### ISSUE TITLE
CollectRnaSeqMetrics --IGNORE_SEQUENCE should not be required argument

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#4427] opened 2018-02-20 17:23 UTC
@chandrans commented on [Tue Feb 20 2018](https://github.com/broadinstitute/gsaweb/issues/89)

### Tool(s) involved
CollectRnaSeqMetrics

### Description
In Picard standalone version 2.16.0, --IGNORE_SEQUENCE is not required, but in GATK4 version, it is required and fails with an error if not provided. This should be an optional argument.

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/46016#Comment_46016

**Comment by cmnbroad** [comment] 2018-02-20 19:03
The `--IGNORE_SEQUENCE` field has type `Set`, but omits the `optional` attribute (so it defaults to false). Since the field is initialized to an empty collection, the legacy Picard parser treats it as optional (i.e., as having been provided a value). The Barclay parser treats the empty collection as if it had not been provided. Its not obvious to me which is better, but adding "optional=true" to the annotation would make it behave the same way for both.

**Comment by chandrans** [comment] 2018-02-20 19:59
That works for me Chris.

**Comment by chandrans** [comment] 2018-02-23 21:00
BTW Chris, is this okay here? I was going to move it to Picard repo, but realized you are okay taking this on. Thanks

**Comment by cmnbroad** [comment] 2018-02-23 21:41
This one is OK since even though its a Picard tool, the issue is specific to GATK.

**Comment by chandrans** [comment] 2018-02-25 19:32
Yep, got it :)

**Comment by anoronh4** [comment] 2020-02-28 21:52
i just tried your gatk docker version 4.1.4.1 and found that IGNORE_SEQUENCE is still required, as the new changes have not yet been approved. in the meantime, is there anything i can put in the parameter to make it work for the time being? empty quotes, for example? exact syntax would be helpful.

**Comment by cmnbroad** [comment] 2020-02-28 22:20
@anoronh4 You can try using the value "null", which resets the collection empty (assuming you're using the tool on the docker through gatk, as opposed to Picard directly, it would be `--IGNORE_SEQUENCE null`).

**Comment by cmnbroad** [comment] 2020-02-28 22:27
Closing this while I'm at it, since Michael fixed the underlying issue in Picard, and that Picard version has now been pulled into GATK and will surface in the next GATK release.

**Closed by cmnbroad** 2020-02-28 22:27 UTC
Labels: CLI, Picard
