### ISSUE TITLE
GenomicDB -> GenotypeGVFs -> NPE

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#6667] opened 2020-06-17 23:05 UTC
We created a GenomicsDB workspace using GenomicsDBImport, followed by 2 rounds of adding new samples using GenomicsDBImport.  We then ran GenotypeGVFs on it and received this NPE.  Is there any information or debugging you can suggest that would help diagnose this?

The command run was approximately this (filepaths have been simplified):

java -Xmx48g -Xms48g -Xss2m GenomeAnalysisTK4.jar GenotypeGVCFs -R 128_Mmul_10.fasta --variant gendb://CombinedGenotypes_WES.gdb -O Test_WES_variantcalling.vcf.gz --annotate-with-num-discovered-alleles -stand-call-conf 30 --max-alternate-alleles 12 --allow-old-rms-mapping-quality-annotation-data

and the error:

17 Jun 2020 15:49:59,410 DEBUG:     java.lang.NullPointerException
17 Jun 2020 15:49:59,412 DEBUG:         at htsjdk.variant.bcf2.BCF2Decoder.decodeInt(BCF2Decoder.java:226)
17 Jun 2020 15:49:59,413 DEBUG:         at htsjdk.variant.bcf2.BCF2Decoder.decodeSingleValue(BCF2Decoder.java:157)
17 Jun 2020 15:49:59,414 DEBUG:         at htsjdk.variant.bcf2.BCF2Decoder.decodeTypedValue(BCF2Decoder.java:146)
17 Jun 2020 15:49:59,416 DEBUG:         at htsjdk.variant.bcf2.BCF2Decoder.decodeTypedValue(BCF2Decoder.java:130)
17 Jun 2020 15:49:59,417 DEBUG:         at htsjdk.variant.bcf2.BCF2Decoder.decodeTypedValue(BCF2Decoder.java:125)
17 Jun 2020 15:49:59,419 DEBUG:         at htsjdk.variant.bcf2.BCF2Codec.decodeInfo(BCF2Codec.java:410)
17 Jun 2020 15:49:59,420 DEBUG:         at htsjdk.variant.bcf2.BCF2Codec.decodeSitesExtendedInfo(BCF2Codec.java:298)
17 Jun 2020 15:49:59,422 DEBUG:         at htsjdk.variant.bcf2.BCF2Codec.decode(BCF2Codec.java:132)
17 Jun 2020 15:49:59,423 DEBUG:         at htsjdk.variant.bcf2.BCF2Codec.decode(BCF2Codec.java:58)
17 Jun 2020 15:49:59,425 DEBUG:         at org.genomicsdb.reader.GenomicsDBFeatureIterator.next(GenomicsDBFeatureIterator.java:183)
17 Jun 2020 15:49:59,426 DEBUG:         at org.genomicsdb.reader.GenomicsDBFeatureIterator.next(GenomicsDBFeatureIterator.java:49)
17 Jun 2020 15:49:59,428 DEBUG:         at java.util.Iterator.forEachRemaining(Iterator.java:116)
17 Jun 2020 15:49:59,429 DEBUG:         at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
17 Jun 2020 15:49:59,431 DEBUG:         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
17 Jun 2020 15:49:59,432 DEBUG:         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
17 Jun 2020 15:49:59,433 DEBUG:         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
17 Jun 2020 15:49:59,435 DEBUG:         at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
17 Jun 2020 15:49:59,436 DEBUG:         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
17 Jun 2020 15:49:59,437 DEBUG:         at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
17 Jun 2020 15:49:59,438 DEBUG:         at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:132)
17 Jun 2020 15:49:59,439 DEBUG:         at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
17 Jun 2020 15:49:59,440 DEBUG:         at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
17 Jun 2020 15:49:59,441 DEBUG:         at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
17 Jun 2020 15:49:59,442 DEBUG:         at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
17 Jun 2020 15:49:59,443 DEBUG:         at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
17 Jun 2020 15:49:59,445 DEBUG:         at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
17 Jun 2020 15:49:59,446 DEBUG:         at org.broadinstitute.hellbender.Main.main(Main.java:292)
17 Jun 2020 15:50:00,408 WARN :     process exited with non-zero value: 3

Versions are:

The Genome Analysis Toolkit (GATK) v4.1.7.0
Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_60-b27
Picard Version: 2.21.9
HTSJDK Version: 2.21.2

Thanks for any help,
Ben

**Comment by droazen** [comment] 2020-06-18 15:01
@bbimber Can you try running `GenotypeGVCFs` with the `--genomicsdb-use-vcf-codec` argument and see if that resolves the NPE?

A second thing to try would be to see if the crash happens with the latest gatk/master, which was just updated to a newer version of the GenomicsDB library with many bug fixes.

**Comment by droazen** [comment] 2020-06-18 15:06
@nalinigans @mlathara This appears to be the same issue as https://github.com/broadinstitute/gatk/issues/6548. Was this fixed in the latest GenomicsDB version that we just updated to in GATK, or do users still need to run with `--genomicsdb-use-vcf-codec` as a stopgap measure?

**Comment by mlathara** [comment] 2020-06-18 16:52
@droazen this behavior hasn't changed in the most recent release. 

Short recap: this happens because bcf codec doesn't support the 64 bit values that GenomicsDB is returning. Running with `--genomicsdb-use-vcf-codec` will resolve it.

From our discussions in the office hours, I thought we had decided to change the behavior in htsjdk  so that it doesn't try to decode the type if it doesn't recognize it. (maybe I should have filed https://github.com/broadinstitute/gatk/issues/6548 in htsjdk instead? I thought I was told to do in GATK, but its been long enough that I can't remember).

Another possibility is to make `--genomicsdb-use-vcf-codec` the default - though I recall you had some potential performance concerns about that.

Lastly, we could change GenomicsDB to throw out a warning if a 64 bit value is needed and we're using bcf codec. Of course, this would still require the user to run with `--genomicsdb-use-vcf-codec` to avoid hitting the NPE (or whatever other failure would be hit if the NPE was changed to something a bit more meaningful).

**Comment by bbimber** [comment] 2020-06-18 17:44
OK, thanks for the quick reply.

**Comment by droazen** [comment] 2020-06-18 18:25
@mlathara Let's discuss our options at our next meeting...if the problem is common enough, and a proper fix is not coming in the short term, we might want to consider making the VCF codec the default despite the performance hit.

**Comment by droazen** [comment] 2020-06-24 16:25
We've decided to make the VCFCodec the default to address this issue (see https://github.com/broadinstitute/gatk/pull/6675).

**Comment by droazen** [comment] 2020-06-26 16:46
Resolved by https://github.com/broadinstitute/gatk/pull/6675

**Closed by droazen** 2020-06-26 16:46 UTC
Labels: GenomicsDB, bug
