### ISSUE TITLE
CommandLineException/CommandLineException.BadArgumentValue should be a UserException (or treated as one)

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2324] opened 2016-12-21 19:18 UTC
Providing a bad value for an argument is the definition of a "user exception" (an error that is the user's fault). If we can't make it a `UserException` directly because of the gatk/barclay split, then we should at least wrap these exceptions in `UserException` at the top level catch, and ensure that a full error message gets printed for the user for these exceptions. 

Currently I think `CommandLineException` can be silently caught and ignored with no output due to a bug in `Main.mainEntry()`:

```
   protected final void mainEntry(final String[] args) {
        try {
            final Object result = instanceMain(args);
            handleResult(result);
            System.exit(0);
        } catch (final CommandLineException e){
            //the usage has already been printed so don't print it here.
            if(printStackTraceOnUserExceptions()) {
                e.printStackTrace();
            }
            System.exit(COMMANDLINE_EXCEPTION_EXIT_VALUE);
        } catch (final UserException e){
            CommandLineProgram.printDecoratedUserExceptionMessage(System.err, e);

            if(printStackTraceOnUserExceptions()) {
                e.printStackTrace();
            }
```

We should fix this as part of this ticket.

**Comment by magicDGS** [comment] 2016-12-21 22:30
The `CommandLineException` is not failing silently except it is thrown out of the command line parsing and/or in the tool `customCommandLineValidation()`. This handling part of the code is in `CommandLineProgram`:

```java
    /**
    *
    * @return true if command line is valid
    */
    protected boolean parseArgs(final String[] argv) {

        commandLineParser = new CommandLineArgumentParser(this, getPluginDescriptors());
        try{
            final boolean ret = commandLineParser.parseArguments(System.err, argv);
            commandLine = commandLineParser.getCommandLine();
            if (!ret) {
                return false;
            }
            final String[] customErrorMessages = customCommandLineValidation();
            if (customErrorMessages != null) {
                for (final String msg : customErrorMessages) {
                    System.err.println(msg);
                }
                commandLineParser.usage(System.err, false);
                return false;
            }
            return true;
        } catch (final CommandLineException e){
            //The CommandLineException is treated specially - we display help and no blow up
            commandLineParser.usage(System.err, true);
            printDecoratedUserExceptionMessage(System.err, e);
            //rethrow e - this will be caught upstream and the right exit code will be used.
            //we don't exit here though - only Main.main is allowed to call System.exit.
            throw e;
        }
    }
```

I think that GATK should discourage the usage of `CommandLineException` outside the Barclay engine or `customCommandLineValidation()`, and no wrapping the exception to `UserException` because it is related with the parsing. For instance, `MissingArgument` could be considere also an user exception, and almost all `CommandLineException` except the internal ones.

I had the same problem when `CommandLineException` was part of `UserException` and I changed to use that one only to parts of the code related with arg parsing. That's why I included in the try-catch block the `customCommandLineValidation()` in #2226. I think that it makes more sense like this, because command line exceptions (e.g., bad or missing args) are printed with the usage of the tool, indicating why the argument is wrong and refering to the help; on the other hand, an user exception is more related with malformed files or other requirements not related with arg parsing.

**Comment by magicDGS** [comment] 2016-12-21 22:31
If there is any part of code which is throwing in GATK an `CommandLineException` outside `customCommandLineValidation()` I offer myself to create a PR to fix it for a proper `UserException`.

**Comment by droazen** [comment] 2016-12-22 03:58
The problem is that the catch block in `CommandLineProgram` is calling both `commandLineParser.usage()` and `printDecoratedUserExceptionMessage()` -- it should only be calling `commandLineParser.usage()`, and letting the catch block in `Main.mainEntry()` call `printDecoratedUserExceptionMessage()`. Otherwise there are cases where a `CommandLineException` will be caught without printing any error message. This is a bug and should be fixed.

The distinction between "errors that are the user's fault" and "errors that are not the user's fault" is very important for our support team -- it allows them to deal with bug reports and forum questions much more efficiently. Whatever solution we come up with here should maintain that distinction, and clearly label errors like "bad argument value" as being a user error.

**Comment by vdauwera** [comment] 2016-12-22 04:01
Yes please, thank you!

**Comment by magicDGS** [comment] 2016-12-22 10:40
Is this the only `CommandLineException` which should be an `UserException`? If not, how is going to work the development of new exceptions in Barclay. For instance, in https://github.com/broadinstitute/barclay/pull/11 there is a new exception that I made for values out of range, which extends `BadArgumentValue`.

I agree that this errors should be decoupled from the ones that are not, but in this case I think that this is already implemented:

* `UserException` are handled in the `mainEntry()`, distinguishing errors that comes from the user's side regarding some specifications in the tools/framework.
* `CommandLineException` are handled in `parseArgs()`, distinguishing errors that comes from the command line from the user side while parsing. I expect that any command line error that is not `CommandLineParserInternalException ` or `ShouldNeverReachHereException` comes from the user's side. The contract in Barclay says that are `CommandLineException` are _"Exceptions thrown by CommandLineParser implementations."_, and I think that if other parts of the code (outside arg parsing) is throwing this exception is a bug that does not come from the user. I guess that this is the problematic part.
* Any other `Exception` is thrown in `Main.handleNonUserException()`, which may be caused by non-user exceptions.

I propose that `CommandLineException` is handled as currently to separate "errors that are the user's fault regarding input and/or assumptions" (`UserException`), "errors that are the user's fault while providing parameters to the command line" (`CommandLineException`) and "errors that are not the user's fault" (other `Exception`s). Actually, this is reasonable because the exit status is different for any kind of errors in the current `Main`. The only problem that I see with this approach is the silently failing of a "bug" in tools/engine code, which can be rethrow easily in `CommandLineProgram.instanceMain`` as following:

```java
    public Object instanceMain(final String[] argv) {
        if (!parseArgs(argv)) {
            //an information only argument like help or version was specified, just exit
            return 0;
        }
        try {
            return instanceMainPostParseArgs();
        } catch (CommandLineException e) {
            // CommandLineExceptions are suposed to be only thrown while parsing arguments
            throw new GATKException("BUG: CommandLineException outside argument parsing code.", e);
        }
    }
```

If you think that this is a good idea, I could implement and workaround parts of the code where this bug is present. The solution is to pass the exception to the `customCommandLineValidation()` block and/or thrown a different `UserException`.

**Comment by cmnbroad** [comment] 2016-12-22 13:24
The Barclay exception hierarchy as it currently stands isn't correct, and it needs to be fixed in a way thats consistent with the LegacyParser, which also isn't consistent in it's separation of internal vs user exceptions. I'll propose a fix for that, followed by a GATK PR to address the other issues in this thread. These won't be until after the holiday break though.

**Comment by droazen** [comment] 2016-12-22 15:55
Unfortunately I don't think it's practical to try to enforce that "only the arg parser can throw `CommandLineException`" -- there's too much downstream code and too many tools that do so already, so it would be a bit painful to treat it as a bug.

Instead I think what we should do is:

* Make sure that barclay uses a separate exception class for internal errors that are not the user's fault. This internal exception class should not be usable outside of barclay (perhaps we can make it package-private?).
* Catch `CommandLineException` in GATK and present it as a user error (output should say "A USER ERROR HAS OCCURRED").
* Move the `printDecoratedUserExceptionMessage()` call for caught `CommandLineExceptions` from `CommandLineProgram.parseArgs()` to `Main.mainEntry()`, to ensure that a message always gets printed for `CommandLineException`

As @cmnbroad said, this will have to wait until after the holiday break (most of us are going to be away until early January).

**Closed** 2017-01-31 18:14 UTC
