### ISSUE TITLE
Request: package the testing framework into a module

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#2533] opened 2017-03-27 08:43 UTC
It will be nice to have the GATK testing framework in a different module and maven artifact to add it as a dependency only for testing, and do not include it in the uber-jar the TestNG dependecy (or the Mini-Cluster from Hadoop).

**Comment by droazen** [comment] 2017-03-27 20:20
Closing as duplicate of https://github.com/broadinstitute/gatk/issues/1481 -- please do a textual search of our issues for possible duplicates before opening a new one.

**Closed by droazen** 2017-03-27 20:20 UTC

**Comment by magicDGS** [comment] 2017-03-28 14:07
Sorry, I use to search but this time I forgot. My fault...

**Comment by lbergelson** [comment] 2017-03-28 14:51
I blame github's lack of autosearch when creating a new ticket.  Every other issue tracker has it...
