### ISSUE TITLE
Fix performance regression in BaseRecalibratorSparkOptimized

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1006] opened 2015-10-16 16:07 UTC
@jean-philippe-martin noticed that the performance of his optimized version of spark BQSR took a nosedive during one of the rebases of his branch. Since he's on leave, one of us will have to profile it in order to find out what the bottleneck is and submit a patch. This is a prerequisite to being able to do the broadcast vs. manual sharding comparison called for in https://github.com/broadinstitute/gatk/issues/995

**Comment by droazen** [comment] 2015-10-16 16:08
Giving this one to @akiezun (since he has https://github.com/broadinstitute/gatk/issues/995), but feel free to re-assign if you are swamped.

**Comment by akiezun** [comment] 2015-10-16 20:29
so the request here is to trace back a slowdown in code that that used to be fast before merge and got slow after the merge? Ie the master version was never fast?

**Comment by droazen** [comment] 2015-10-16 21:24
It got slow after the big rebase before the branch was code reviewed, I believe. Some dependent class may have been changed in a way that adversely affected the optimized BQSR.

**Comment by droazen** [comment] 2015-10-19 19:59
Our initial tests show the optimized version to be ~2x faster than the unoptimized version, which is much less of a gain than JP was initially seeing.

One issue we've identified so far is that the custom sharding code is not written in a way that is aware of the way spark is actually partitioning the RDDs, so it's very easy to end up with all the work in a small number of partitions and/or a disproportionate amount of data in a single partition (the protection JP built into his code against large shards is not partition-aware and so not effective).

**Comment by jean-philippe-martin** [comment] 2015-11-11 18:04
@droazen's [measurements in #995](https://github.com/broadinstitute/gatk/issues/995#issuecomment-152310985) show that for the 7GB input the optimized version ("sharding") is **9x faster** than the unoptimized version ("shuffle"). The code is fast as intended, I'm closing this bug.

**Closed by jean-philippe-martin** 2015-11-11 18:04 UTC
Labels: bug, profiling, Spark, tools
