### ISSUE TITLE
[Mutect2] Mutect2 error when use --disable-tool-default-read-filters

### ISSUE THREAD

**Issue by liuyihhha** [broadinstitute/gatk#8224] opened 2023-02-28 03:07 UTC
### Instructions

Dear GATK team,

I am encountering an error when using the mutect2 function in "gatk-4.2.6.1". Whenever I enable the "--disable-tool-default-read-filters" option, I receive a java.lang.ArrayIndexOutOfBoundsException error.

Since I need to call SNVs for RNA-seq data, I first split the bam file by chromosome, and then perform markduplicate and splitNcigar in two steps. I found that when I use the bam file obtained after using the splitNcigar function to run mutect2, the same error still occurs, even if I don't disable the -read-filters. Therefore, I suspect that the error may be introduced by splitNcigar. Thus, I tried running mutect2 directly on the bam file after markduplicate. If the --disable-tool-default-read-filters option is not set, the command runs successfully. However, once it is set, the same error occurs.

----

## Bug Report
[February 28, 2023 10:46:30 AM CST] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=2394947584
java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.broadinstitute.hellbender.utils.clipping.ClippingOp.applyHardClipBases(ClippingOp.java:216)
        at org.broadinstitute.hellbender.utils.clipping.ClippingOp.apply(ClippingOp.java:69)
        at org.broadinstitute.hellbender.utils.clipping.ReadClipper.clipRead(ReadClipper.java:142)
        at org.broadinstitute.hellbender.utils.clipping.ReadClipper.clipLowQualEnds(ReadClipper.java:251)
        at org.broadinstitute.hellbender.utils.clipping.ReadClipper.hardClipLowQualEnds(ReadClipper.java:255)
        at org.broadinstitute.hellbender.utils.clipping.ReadClipper.hardClipLowQualEnds(ReadClipper.java:263)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.finalizeRegion(AssemblyBasedCallerUtils.java:132)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:270)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:249)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:300)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)

#### Steps to reproduce
Step1:  Splitting bam files by chromosome using Pysam

Step2: Markduplicate for each bam file

Step3: SplitNcigar for each bam file
gatk-4.2.6.1/gatk SplitNCigarReads -R $fasta -I $Markduplicate_bam -O $splitNCigar_bam 

Step4: Mutect2
gatk-4.2.6.1/gatk Mutect2 -I $splitNCigar_bam -L $chrom -R $fasta -tumor xxxx --output $out_vcf --disable-tool-default-read-filters true

**Comment by jamesemery** [comment] 2023-03-01 14:43
Hello @liuyihhha, I'm sorry to hear that. We should probably include a more prominent warning that something like this could happen if you disable all of the readfilters for the tool some of them are there just to make sure everything is formatted correctly and doesn't crash. If you `--disable-tool-default-read-filters` it disables all of them including the basic "can the GATK even parse this read" style readfilters. I would recommend adding back in some of the more basic read filters and seeing if you still get this error. Specifically I would recommend trying with the following arguments:
```
--disable-tool-default-read-filters true
-RF WellformedReadFilter
-RF GoodCigarReadFilter
```
As for what about SplitNCigarReads could be causing the reads to be invalid I would like to have some idea of what the issue is. You could try running `ValidateSamFile` on your input to Mutect2 and hopefully that will spit back some readnames that are invalid which should make it easier to diagnose. Given the operations in SplitNCigarReads and the nature of your stacktrace it wouldn't surprise me if there is something wrong/messy about the cigars output by that tool in some cases.

**Comment by lbergelson** [comment] 2023-03-02 20:32
You can also individually disable tool default read filters using the `--disable-read-filter` or `-DF` argument.  

In general if you disable the basic safeguards the tool requires you're likely to run into issues though.

**Comment by droazen** [comment] 2023-03-13 19:25
Closing as resolved

**Closed** 2023-03-20 19:31 UTC
