### ISSUE TITLE
Add a mechanism to pass extra information to an annotation instance,

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1468] opened 2016-02-03 16:56 UTC
We need a mechanism to pass extra information to an annotation instance. For example, InbreedingCoeff can take a set of samples (founders) and be computed on those only. Right now (after https://github.com/broadinstitute/gatk/pull/890 is merged) there's no way to set this. GATK3 had an `initialize` method which meant that annotation classes were no longer immutable (as they locally are)

**Comment by akiezun** [comment] 2016-02-12 23:14
PossibleDeNovo is one of those annotations

**Comment by droazen** [comment] 2017-10-17 19:37
Relates to https://github.com/broadinstitute/gatk/issues/3287

**Comment by droazen** [comment] 2017-10-17 20:00
Closing -- duplicate of https://github.com/broadinstitute/gatk/issues/1880

**Closed by droazen** 2017-10-17 20:00 UTC
Labels: Annotations, Engine
