### ISSUE TITLE
GenotypeGVCFs run on GenomicsDB produces empty VCF

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#3429] opened 2017-08-10 15:00 UTC
We have received two independent reports of this problem. The latest by Brad Chapman, posted [here](https://gatkforums.broadinstitute.org/gatk/discussion/comment/41338#Comment_41338) includes a reproducible test case. Files are here: https://s3.amazonaws.com/chapmanb/testcases/gatk4_genotypegvcfs.tar.gz

#### Steps to reproduce:

Running an import, and then a GenotypeGVCFs and SelectVariants to test export:

```
gatk-launch GenomicsDBImport --genomicsDBWorkspace test_genomicsdb -L chrM:1-1000 --variant Test1.vcf.gz --variant Test2.vcf.gz
gatk-launch GenotypeGVCFs --variant gendb://test_genomicsdb -R hg19.fa --output joint.vcf.gz -L chrM:1-1000
gatk-launch SelectVariants -R hg19.fa -V gendb://test_genomicsdb -O extract.vcf.gz
```

The input GVCFs have calls within the chrM region being tested:

```
Test1.vcf.gz:chrM       150     .       T       C,<NON_REF>     49406.77        .       DP=1084;ExcessHet=3.0103;MLEAC=2,0;MLEAF=1.00,0.00;MQ0=0;RAW_MQ=3902400.00    GT:AD:DP:GQ:MCL:MMQ:PGT:PID:PL:SB       1/1:0,1081,0:1081:99:0,0,0:0,60,0:0|1:150_T_C:49435,3362,0,49435,3362,49435:0,0,483,598
```

But the `GenotypeGVCFs` output VCF is empty (file only contains the hdear; no records). Running `SelectVariants` shows the sample but with empty genotype calls:

```
extract.vcf.gz:chrM     150     .       T       C,<NON_REF>     .       .       DP=2168;ExcessHet=3.01;MQ0=0;RAW_MQ=7804800.00        GT:AD:DP:GQ:MCL ./.:0,1081,0:1081:99:0.00,0.00  ./.:0,1081,0:1081:99:0.00,0.00
```

**Comment by lbergelson** [comment] 2017-08-11 17:18
It's weird, it looks like all the format attributes after MCL are getting dropped from sites with an alt allele. That would explain why there are no genotypes. If a site has no PLs I think we don't demit it. 
 @kgururaj do you have any insight into why that's happening?

**Comment by lbergelson** [comment] 2017-08-11 17:20
Also, @vdauwera thank Brad Chapman for this excellent test case.  No one ever sends us such complete data to reproduce. It even has a run script that demonstrates the problem!

**Comment by lbergelson** [comment] 2017-08-14 16:13
@kdatta @kgururaj

**Comment by kdatta** [comment] 2017-08-16 18:43
@lbergelson @droazen I ran GenotypeGVCF in the debugger with the options as shown above and found that GenomicsDBFeatureReader iterator is returning the VCF records correctly. They match the output of the GenomicsDB standalone reader. The reason they are not printed to the output file is because vcfwriter.write() is not called with the VCF records. I think this might be a bug in the GenotypeGVCFs code.

**Comment by lbergelson** [comment] 2017-08-16 19:21
@kdatta Do the returned records have PLs?

**Comment by lbergelson** [comment] 2017-08-16 20:26
@kdatta I see records coming out of genomics db that seem invalid to me.  All of the records that have alt alleles other than <NON_REF> are missing the PL's and all the genotype attributes that aren't MCL.

**Comment by lbergelson** [comment] 2017-08-16 20:28
Although it's always possible there's a bug in the htsjdk bcf codec causing the issue...

**Comment by kdatta** [comment] 2017-08-16 21:16
Yes, all the records have PL values. For example, the PL values at 101 position as seen in the debugger are:
chrM:101-149 Q. of type=SYMBOLIC alleles=[G*, <NON_REF>] attr={END=149}
genotypes = {LazyGenotypesContext@3249}  size = 2
 0 = {FastGenotype@3259} "[Test1 ./. GQ 99 DP 1114 PL 0,120,1800 {MIN_DP=975}]"
 1 = {FastGenotype@3260} "[Test2 ./. GQ 99 DP 1114 PL 0,120,1800 {MIN_DP=975}]"

The object shown here is returned by codec.decode(). Does it mean the codec is working correctly?

**Comment by lbergelson** [comment] 2017-08-16 22:00
That doesn't have any alt alleles that are not <NON_REF>.  I only see the problem in the alleles that have real alts.  What do you see for position 150?  I see

[VC null @ chrM:150 Q. of type=MIXED alleles=[T*, <NON_REF>, C] attr={DP=2168, ExcessHet=3.0102999210357666, MQ0=0, RAW_MQ=7804800.0} GT=htsjdk.variant.bcf2.BCF2Codec$LazyData@2d119405
with genotypes:
genotypes = {LazyGenotypesContext@2969}  size = 2
 0 = {FastGenotype@2974} "[Test1 ./. GQ 99 DP 1081 AD 0,1081,0 {MCL=[0.0, 0.0]}]"
 1 = {FastGenotype@2975} "[Test2 ./. GQ 99 DP 1081 AD 0,1081,0 {MCL=[0.0, 0.0]}]"

**Comment by lbergelson** [comment] 2017-08-16 22:01
I'm running  `gatk-launch SelectVariants -R hg19.fa -V gendb://test_genomicsdb -O extract.vcf.gz` with the data supplied by the user.

**Comment by kdatta** [comment] 2017-08-17 00:07
Yup, see the same thing. Fields after MCL for positions with alt alleles that are not <NON_REF> are getting dropped. Need more debugging to do.

**Comment by kgururaj** [comment] 2017-08-23 00:32
The issue is that the field length descriptors are incorrect in the VCF header. MMQ and MCL field lengths are set to A in the header; however, in the data the length is equal to the total number of alleles (A+1). The field lengths should be set to R in the header as per the VCF spec.

The mismatch in length descriptors messes up buffer offsets in the query phase of GenomicsDB.

**Comment by chapmanb** [comment] 2017-08-23 16:26
Karthik, Kushal, Louis and Geraldine;
Thanks for all the help debugging this and Karthik thanks for identifying the underlying problem. If I fix the header than calling does work correctly. Brilliant.

I submitted a PR (#3490), which should fix this issue. In digging it looks like this intersects with other ongoing work with MuTect2 so I tried to reference that as well so it's coordinated. Thank you again.

**Comment by lbergelson** [comment] 2017-08-23 16:29
Thanks everyone for working this out.  Is there any chance we can detect this problem on load and fail rather than silently giving bad output?

**Comment by chapmanb** [comment] 2017-08-25 20:17
The GATK VCF header issue causing the underlying problem was fixed in #3351, so a new release of GATK4 should work correctly and avoid losing variants during GenomicsDB import/output for joint calling. I agree with Louis that failing with an error would be better than the current silent failures in case of any future issues.

Thank you all again for the help debugging this.

**Comment by droazen** [comment] 2017-10-17 16:17
Closing -- this was fixed in https://github.com/broadinstitute/gatk/pull/3490

**Closed by droazen** 2017-10-17 16:17 UTC
Labels: bug, GenomicsDB, PRIORITY_HIGH

**Comment by ksw9** [comment] 2018-08-15 04:17
Hi, 
I am encountering a similar issue in gatk-4.0.7.0, in which I find that the GenomicsDBImport combines gVCFs but leaves the majority of variants out of the final merged VCF. I called variants with DeepVariant I am not sure if the format is the problem as it was above. The header is below. Is there a fix for this or a temporary workaround?

Thank you!
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=RefCall,Description="Genotyping model thinks this site is reference.">
##FILTER=<ID=LowQual,Description="Confidence in this variant being real is below calling threshold.">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position (for use with symbolic alleles)">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Conditional genotype quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth">
##FORMAT=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum DP observed within the GVCF block.">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Read depth for each allele">
##FORMAT=<ID=VAF,Number=A,Type=Float,Description="Variant allele fractions.">
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Genotype likelihoods">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Phred-scaled genotype likelihoods rounded to the closest integer">
##contig=<ID=NC_000962.3,length=4411532>

```

**Comment by yangyxt** [comment] 2020-11-06 02:10
I'm using GATK 4.1.8.1. And I found a similar error when trying to use GenotypeGVCFs to consolidate genotyping variants on chrX. It does not give any error message. It silently fails. BTW, I'm dealing with WES data.

This is the code I used:
# For GenomicDBImport, I randomly select 50 samples from our history samples(using the same probe set) along with the current batch.
time ${gatk} --java-options "-Xmx8g -Xms2g" GenomicsDBImport \
                --tmp-dir /paedyl01/disk1/yangyxt/test_tmp \
                --genomicsdb-update-workspace-path ${vcf_dir}/genomicdbimport_chr${1} \
                -R ${ref_gen}/ucsc.hg19.fasta \
                --batch-size 0 \
                --sample-name-map ${gvcf}/batch_cohort.sample_map \
                --reader-threads 5
                check_return_code

# For GenotypeGVCFs
time ${gatk} --java-options "-Xmx8g -Xms2g -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" GenotypeGVCFs \
    -R ${ref_gen}/ucsc.hg19.fasta \
    -V gendb://${vcf_dir}/genomicdbimport_chr${1} \
    -G StandardAnnotation \
    -G AS_StandardAnnotation \
    -L chr${1} \
    -O ${bgvcf}/all_${seq_type}_samples_plus_${sample_batch}.chr${1}.HC.vcf

# These are log records:
02:07:51.286 WARN  GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
02:07:51.321 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/yangyxt/software/gatk-4.1.8.1/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl
Nov 06, 2020 2:07:56 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
02:07:56.529 INFO  GenotypeGVCFs - ------------------------------------------------------------
02:07:56.529 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.1.8.1
02:07:56.530 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
02:08:01.543 INFO  GenotypeGVCFs - Executing as yangyxt@paedyl01 on Linux v3.10.0-1062.18.1.el7.x86_64 amd64
02:08:01.543 INFO  GenotypeGVCFs - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_161-b12
02:08:01.543 INFO  GenotypeGVCFs - Start Date/Time: November 6, 2020 2:07:51 AM HKT
02:08:01.543 INFO  GenotypeGVCFs - ------------------------------------------------------------
02:08:01.544 INFO  GenotypeGVCFs - ------------------------------------------------------------
02:08:01.544 INFO  GenotypeGVCFs - HTSJDK Version: 2.23.0
02:08:01.545 INFO  GenotypeGVCFs - Picard Version: 2.22.8
02:08:01.545 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
02:08:01.545 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
02:08:01.545 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
02:08:01.545 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
02:08:01.545 INFO  GenotypeGVCFs - Deflater: IntelDeflater
02:08:01.545 INFO  GenotypeGVCFs - Inflater: IntelInflater
02:08:01.545 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
02:08:01.545 INFO  GenotypeGVCFs - Requester pays: disabled
02:08:01.546 INFO  GenotypeGVCFs - Initializing engine
02:08:02.257 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.3.0-e701905
02:08:02.331 info  NativeGenomicsDB - pid=161923 tid=161924 No valid combination operation found for INFO field DS  - the field will NOT be part of INFO fields in the generated VCF
02:08:02.331 info  NativeGenomicsDB - pid=161923 tid=161924 No valid combination operation found for INFO field InbreedingCoeff  - the field will NOT be part of INFO fields in the
02:08:02.331 info  NativeGenomicsDB - pid=161923 tid=161924 No valid combination operation found for INFO field MLEAC  - the field will NOT be part of INFO fields in the generated
02:08:02.331 info  NativeGenomicsDB - pid=161923 tid=161924 No valid combination operation found for INFO field MLEAF  - the field will NOT be part of INFO fields in the generated
02:08:02.380 INFO  IntervalArgumentCollection - Processing 155270560 bp from intervals
02:08:02.385 INFO  GenotypeGVCFs - Done initializing engine
02:08:02.426 INFO  ProgressMeter - Starting traversal
02:08:02.426 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),0.0,Cpu time(s),0.0
02:08:02.685 INFO  ProgressMeter -             unmapped              0.0                     0              0.0
02:08:02.685 INFO  ProgressMeter - Traversal complete. Processed 0 total variants in 0.0 minutes.
02:08:02.688 INFO  GenotypeGVCFs - Shutting down engine
[November 6, 2020 2:08:02 AM HKT] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 0.19 minutes.
Runtime.totalMemory()=2190999552
Using GATK jar /home/yangyxt/software/gatk-4.1.8.1/gatk-package-4.1.8.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx8g -Xms2g -D

real    0m18.775s
user    0m8.039s
sys     0m1.440s

According to the log, it seems the traversal never started. But I checked the gvcf file on chrX of the current batch and I'm pretty sure there are lot's of variant records (for a single sample, around 25000 variant records on chrX) looking like these:
chrX    2699968 .       A       G,<NON_REF>     894.06  .       AS_RAW_BaseQRankSum=||;AS_RAW_MQ=0.00|75600.00|0.00;AS_RAW_MQRankSum=||;AS_RAW_ReadPosRankSum=||;AS_SB_TABLE=0,0|21,
chrX    2700027 .       T       C,<NON_REF>     1681.06 .       AS_RAW_BaseQRankSum=||;AS_RAW_MQ=0.00|165600.00|0.00;AS_RAW_MQRankSum=||;AS_RAW_ReadPosRankSum=||;AS_SB_TABLE=0,0|34
chrX    2704469 .       T       C,<NON_REF>     70.64   .       AS_RAW_BaseQRankSum=|-0.8,1|NaN;AS_RAW_MQ=10800.00|14400.00|0.00;AS_RAW_MQRankSum=|0.0,1|NaN;AS_RAW_ReadPosRankSum=|
chrX    2704556 .       A       G,<NON_REF>     105.64  .       AS_RAW_BaseQRankSum=|-0.6,1|NaN;AS_RAW_MQ=7200.00|14400.00|0.00;AS_RAW_MQRankSum=|0.0,1|NaN;AS_RAW_ReadPosRankSum=|1
chrX    2706896 .       T       TA,<NON_REF>    44.27   .       AS_RAW_BaseQRankSum=||;AS_RAW_MQ=0.00|7200.00|0.00;AS_RAW_MQRankSum=||;AS_RAW_ReadPosRankSum=||;AS_SB_TABLE=0,0|0,0|
chrX    2707060 .       A       G,<NON_REF>     37.31   .       AS_RAW_BaseQRankSum=||;AS_RAW_MQ=0.00|7200.00|0.00;AS_RAW_MQRankSum=||;AS_RAW_ReadPosRankSum=||;AS_SB_TABLE=0,0|0,0|
chrX    2710840 .       C       T,<NON_REF>     73.83   .       AS_RAW_BaseQRankSum=||;AS_RAW_MQ=0.00|10800.00|0.00;AS_RAW_MQRankSum=||;AS_RAW_ReadPosRankSum=||;AS_SB_TABLE=0,0|2,1
chrX    2710995 .       C       T,<NON_REF>     192.97  .       AS_RAW_BaseQRankSum=||;AS_RAW_MQ=0.00|21600.00|0.00;AS_RAW_MQRankSum=||;AS_RAW_ReadPosRankSum=||;AS_SB_TABLE=0,0|4,2
chrX    2711528 .       T       A,<NON_REF>     29.64   .       AS_RAW_BaseQRankSum=|0.0,1|NaN;AS_RAW_MQ=7200.00|7200.00|0.00;AS_RAW_MQRankSum=|0.0,1|NaN;AS_RAW_ReadPosRankSum=|1.3
chrX    2711722 .       C       T,<NON_REF>     37.31   .       AS_RAW_BaseQRankSum=||;AS_RAW_MQ=0.00|7200.00|0.00;AS_RAW_MQRankSum=||;AS_RAW_ReadPosRankSum=||;AS_SB_TABLE=0,0|0,0|
chrX    2712283 .       C       T,<NON_REF>     66.31   .       AS_RAW_BaseQRankSum=||;AS_RAW_MQ=0.00|7200.00|0.00;AS_RAW_MQRankSum=||;AS_RAW_ReadPosRankSum=||;AS_SB_TABLE=0,0|0,0|


Every other chromosome works well except for chrX. The output file ${bgvcf}/all_${seq_type}_samples_plus_${sample_batch}.chr${1}.HC.vcf is just a vcf header file with no real records.

**Comment by ldgauthier** [comment] 2020-11-17 18:07
@yangyxt are your X calls all diploid?

If you look inside the genomicsdb workspace directory there should be subdirectories with names like `chrX$6737480$13895201` for the intervals they cover.  Do you see anything starting with chrX?
