### ISSUE TITLE
GenomicsDB instances must always have the same absolute file path

### ISSUE THREAD

**Issue by danking** [broadinstitute/gatk#3411] opened 2017-08-04 16:11 UTC
It has recently come to our (Hail team's) attention that GenomicsDB instances [cannot be moved from the creation location](https://github.com/Intel-HLS/GenomicsDB/issues/135).

Either GenomicsDB will need to generalize to work on instances stored at absolute paths differing from their creation location, or GATK will need to provide the absolute path of the creation location so that Hail can construct the appropriate directory structure to read from a GenomicsDB instance.

Please advise as to GATK's plan with respect to delivering GenomicsDB instances and their absolute creation paths.

cc: @cseed @jackgoldsmith4

**Comment by vdauwera** [comment] 2017-08-04 16:15
Ouch, I didn't know about this limitation. Thanks for bringing this up, @danking. 

@droazen were you aware of this? Any plans on the current roadmap to deal with this?

**Comment by droazen** [comment] 2017-08-04 16:18
@kgururaj @kdatta Can you comment? Would this limitation be easy to remove?

**Comment by kdatta** [comment] 2017-08-04 17:19
We had already planned to remove this limitation. The limitation comes from using an older version of TileDB in GenomicsDB. The latest version of TileDB has an API called array_move() to do this correctly which we will expose in GenomicsDB.

**Comment by lbergelson** [comment] 2017-08-04 17:27
Ideally this would work without calling into any special api..  
ex: I copy a workspace somewhere and then refer to that workspace and everything is computed relative to the workspace.  Having to use a special tiledbmv tool to copy files is going to be quiet painful I think.

**Comment by vdauwera** [comment] 2017-08-04 17:49
I second @lbergelson's comment -- requiring the use of a special tool to move the data would be a really hard sell to users.

**Comment by kdatta** [comment] 2017-08-04 18:19
I see. Once created, the full path to the GenomicsDB array is hard-coded into the schema. This is the reason we suggest that if you are copying to a different machine follow the full path of workspace where it was originally created. Merely copying to a different location will break the reads. An utility array move or copy command will enable you to move an array to any location.

The other way to solve this without a special api is to create a symbolic link with the creation workspace path which links to the copy location.

**Comment by cseed** [comment] 2017-08-04 18:26
@kdatta The issue here is that machines are ephemeral and arrays are going to be moved as a matter of course.  GATK is going to produce arrays for dataset shards on ephemeral machines/clusters, deliver them to us in e.g. object storage (This is the correct model, right?  @droazen @lbergelson) which we will again copy to machines of an ephemeral cluster to analyze.

**Comment by droazen** [comment] 2017-08-04 18:29
Yes, I think that's right @cseed. @kdatta why does the absolute path need to be hardcoded into the schema? Is there a technical reason why relative paths would not work?

**Comment by lbergelson** [comment] 2017-08-04 18:30
It's never made sense to me that the full path to the array has to be hard coded into anything.  It seems like you should be able to compute the path to the array given a full path to the workspace, which is what we provide at runtime.

@cseed That matches my expectations.  It's actually less of a problem for something like our production environment which can probably be arranged to keep these things at the same path, and more of a problem for general users who might for instance want to send a genomicsDB file to us for debugging purposes.

**Comment by kdatta** [comment] 2017-08-04 18:44
@droazen the reason for hardcoding the full path is to handle grouping of arrays. In TileDB manages arrays hierarchically. A workspace can contain arrays or groups of arrays. Groups can have different arrays with same name. When you read from an existing array or update it with a given workspace path, you need to figure out which array in the the group you are referring to, hence the full path. More information [here](http://istc-bigdata.org/tiledb/tutorials/index.html#workspaces_groups)

The real issue here is to figure out a way to package TileDB arrays to ship it to some other location. The problem is the data and fragments inside the array directory is self-contained. If we replace the full path in the schema it will other conventions for groups and workspace. I will discuss more on this with @kgururaj and come up with a solution.

**Comment by droazen** [comment] 2017-08-04 18:49
@kdatta Why not use some kind of globally-unique identifier for the arrays if name collision is an issue (such as a hash or UUID)? Would that solve the problem?

**Comment by kdatta** [comment] 2017-08-04 18:52
@lbergelson actually many databases do such hardcoded directory management and provide tools to migrate data to other locations. The reason is they want to maintain writeahead logs, updates and other temporary files per database or table or array. We also followed the method in TileDB. Other storage formats like HDF5 are completely self-contained and stores everything in one file. Each method comes with its set of challenges :)

**Comment by cseed** [comment] 2017-08-04 19:12
I'm not sure we have a "production environment".  Our users at Broad run Hail on a variety of systems from laptops to the Broad Spark cluster to GCP.  In most of the environments, at the privilege level we normally run, we can't control the absolute location of files.  As @vdauwera notes, this will be even more onerous for external users who want to run GATK => Hail.

**Comment by kdatta** [comment] 2017-08-04 21:22
@droazen actually removing the hard-coded path in TileDB might be the best option long term. I will check over the weekend what's the complexity of this work and how soon we can turn this around.

**Comment by droazen** [comment] 2017-09-25 18:29
Co-assigning to @jamesemery to ensure this gets done next quarter.

**Closed** 2018-01-03 16:10 UTC
Labels: GenomicsDB

**Comment by danking** [comment] 2018-01-08 16:54
@lbergelson I see that 7298392 closed this issue. Does this mean that the `genomicsdb` artifact version `0.8.1-proto-3.0.0-beta-1` in maven central supports reading of genomics db instances stored at paths arbitrarily different form their creation location?

Thanks for the update!

**Comment by lbergelson** [comment] 2018-01-08 17:23
@danking That's the idea.  I may have closed this prematurely because I didn't wait for the pr with tests (#4000). You're supposed to be able to pick up the workspace directory and move it around no problem now.
