### ISSUE TITLE
update dist commands to include gatk-launch and sparkJar

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1779] opened 2016-04-27 17:15 UTC
Update the gradle distribution commands to include the sparkJar, gatk-launch, and settings.gradle in the zipped archive so we can have a single command to build a distributable zip.

**Comment by droazen** [comment] 2016-08-01 14:42
Closing as dupe of https://github.com/broadinstitute/gatk/issues/1987

**Closed by droazen** 2016-08-01 14:42 UTC
Labels: ReleaseEngineering
