### ISSUE TITLE
MarkDuplicatesSpark produces an empty bam file when run on a stand alone spark

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1448] opened 2016-01-25 20:24 UTC
This was reported by @geetduggal in #1444.  

If you run MarkDuplicatesSpark using a local standalone spark cluster it can run to completion, but produces an empty bam file that has only a header.

```
./gatk-launch MarkDuplicatesSpark -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -O testoutput.bam -- --sparkRunner SPARK --sparkMaster spark://wm1b0-8ab:7077
```

produces an empty bam

**Comment by droazen** [comment] 2016-01-25 20:34
Duplicate of https://github.com/broadinstitute/gatk/issues/1444? :)

**Comment by lbergelson** [comment] 2016-01-25 22:39
#1444 is several related issues.  This is more specific.  1444 depends on this.

**Comment by lbergelson** [comment] 2016-01-26 19:35
So I've tracked this down to being a problem with line 193 in `ReadSparkSink`.  

```
       finalOut.saveAsNewAPIHadoopFile(outputFile, SAMRecord.class, SAMRecordWritable.class, SparkHeaderlessBAMOutputFormat.class);
```

saveAsNewAPIHadoopFile is not writing any part files when `outputFile` (a `String`) is a relative path.  i.e. `test.bam`.  

If you change it to a fully specified path  i.e. `/Users/louisb/Workspace/gatk/testoutput.bam` then it works as expected.

I discovered this by running the driver in the debugger which is possible using 

```
--driver-java-options -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
``` 

as an option to spark-submit (or gatk-launch)

The quick fix is to have input paths be converted into absolute paths always.  Also to add a check in `mergeBam()` to make sure that there's at least 1 part file specified.

The longer fix is to 
1. understand why this is happening only in certain spark configurations
2. figure out how to unit test for this

**Comment by geetduggal** [comment] 2016-01-27 00:18
I went ahead and made a build based on the branch associated with this issue and it looks like it worked for me on the test BAM discussed in https://github.com/broadinstitute/gatk/issues/1444.  Thanks for your prompt effort!

**Closed** 2016-01-28 23:05 UTC
Labels: bug, Spark
