### ISSUE TITLE
reading data from GCS fails on travis

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1820] opened 2016-05-14 00:32 UTC
see disabled tests like  `testBQSRBucket(BQSRTest params)` in `BaseRecalibratorSparkIntegrationTest.java` - they fail to read data from buckets

**Comment by droazen** [comment] 2017-10-17 19:56
Closing -- this is a duplicate of https://github.com/broadinstitute/gatk/issues/2481

**Closed by droazen** 2017-10-17 19:56 UTC
Labels: bug, Spark
