### ISSUE TITLE
Funcotator returns a nullpointer exception when trying to output compressed VCF

### ISSUE THREAD

**Issue by fpbarthel** [broadinstitute/gatk#5683] opened 2019-02-15 20:37 UTC
### Affected tool(s) or class(es)
`Funcotator`

### Affected version(s)
GATK 4.1.0.0 release

### Description 
Funcotator returns a `NullPointerException` when trying to output compressed VCF:

```
15:35:26.085 INFO  Funcotator - Creating a VCF file for output: XXXX
15:35:26.125 INFO  ProgressMeter - Starting traversal
15:35:26.125 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
log4j:WARN No appenders could be found for logger (org.broadinstitute.hellbender.tools.funcotator.dataSources.vcf.VcfFuncotationFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
15:35:26.328 INFO  Funcotator - Shutting down engine
[February 15, 2019 3:35:26 PM EST] org.broadinstitute.hellbender.tools.funcotator.Funcotator done. Elapsed time: 0.18 minutes.
Runtime.totalMemory()=3391094784
java.lang.NullPointerException
        at htsjdk.tribble.index.tabix.TabixIndexCreator.finalizeFeature(TabixIndexCreator.java:106)
        at htsjdk.tribble.index.tabix.TabixIndexCreator.finalizeIndex(TabixIndexCreator.java:129)
        at htsjdk.variant.variantcontext.writer.IndexingVariantContextWriter.close(IndexingVariantContextWriter.java:177)
        at htsjdk.variant.variantcontext.writer.VCFWriter.close(VCFWriter.java:231)
        at org.broadinstitute.hellbender.tools.funcotator.vcfOutput.VcfOutputRenderer.close(VcfOutputRenderer.java:137)
        at org.broadinstitute.hellbender.tools.funcotator.Funcotator.closeTool(Funcotator.java:883)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:970)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
        at org.broadinstitute.hellbender.Main.main(Main.java:291)
```

#### Steps to reproduce

Does not work
```
gatk Funcotator --variant input.vcf.gz --reference /path/to/human_g1k_v37_decoy.fasta --ref-version hg19 --data-sources-path /path/to/funcotator_dataSources.v1.6.20190124s/ --output output.vcf.gz --output-file-format VCF
```

Works
```
gatk Funcotator --variant input.vcf.gz --reference /path/to/human_g1k_v37_decoy.fasta --ref-version hg19 --data-sources-path /path/to/funcotator_dataSources.v1.6.20190124s/ --output output.vcf --output-file-format VCF
```

(note that the `--output` parameter is different)

#### Expected behavior
It should either give an error/warning saying outputting compressed VCF output is not supported, or output a compressed VCF like other GATK tools

#### Actual behavior
See examples above

**Comment by droazen** [comment] 2021-07-16 16:22
Re-assigning to @haileypfox

**Comment by haileypfox** [comment] 2021-07-27 23:24
I have been unable to reproduce this error. I have tried a few different things but none of them have resulted in this null pointer exception.

**Comment by fpbarthel** [comment] 2021-07-27 23:45
Thanks for looking into this @haileypfox, as I submitted this bug report in Feb 2019 using GATK 4.1.0.0 I have since used a workaround (add an additional compression step after outputting uncompressed, eg. https://github.com/fpbarthel/GLASS/blob/333d5d01477e49bb2cf87be459d4161d4cde4483/snakemake/mutect2-post.smk#L188-L206).

Did you use 4.1.0.0 to test this? Perhaps this was since fixed?

**Comment by haileypfox** [comment] 2021-07-28 14:36
@fpbarthel I did use 4.1.0.0 to test this as well as 4.0.9.0. I think that it must have been fixed, but I am glad that you were able to find a workaround. Let us know if this error occurs again though.

**Closed** 2021-08-04 22:37 UTC
Labels: Engine, Funcotator, bug
