### ISSUE TITLE
FlagStatSpark causes NPE when output file is not set

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#1282] opened 2015-12-09 13:19 UTC
The output file (`-O`/`--output`) is optional, but if not set you get a NPE:

```
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at org.broadinstitute.hellbender.tools.spark.pipelines.FlagStatSpark.runTool(FlagStatSpark.java:41)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:257)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:36)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:98)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:165)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)
	at org.broadinstitute.hellbender.Main.main(Main.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
```

This is the command I ran:

```
./gatk-launch FlagStatSpark \
  --input hdfs:///user/$USER/bam/CEUTrio.HiSeq.WGS.b37.ch1.1m-65m.NA12878.bam \
  -bps 134217728 \
  -- \
  --sparkRunner SUBMIT --sparkMaster yarn-client \
  --driver-memory 3G \
  --num-executors 14 \
  --executor-cores 1 \
  --executor-memory 3G
```

**Comment by tomwhite** [comment] 2015-12-09 13:32
Note that the stats are still printed to the console; the NPE happens after that.

**Comment by lbergelson** [comment] 2015-12-09 13:47
Closing this as a duplicate of #1202

**Closed by lbergelson** 2015-12-09 13:47 UTC
Labels: AlphaTesting, bug
