### ISSUE TITLE
Expose vid_mapping_file JSON in GenomicsDB

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#3689] opened 2017-10-11 20:06 UTC
In order to produce the 68K WGS callset, we need to add new INFO annotations (relevant combine operations for these already exist.)  However, there's no easy way to specify how to combine them without manually editing that file. It would be great if there was a way to do that in the GATK tool args for GenomicsDBImport.

**Comment by cmnbroad** [comment] 2017-10-16 17:34
Per discussion with @kgururaj, the proposal is to have GenomicsDB expose/document the existing protocol buffers already used internally, along with protobuf-based constructors for both GenomicsDBImporter and GenomicsDBFeatureReader.

**Comment by droazen** [comment] 2018-07-06 17:40
This is a dupe of https://github.com/broadinstitute/gatk/issues/4541, I believe -- closing.

**Closed by droazen** 2018-07-06 17:40 UTC
Labels: GenomicsDB

**Comment by ldgauthier** [comment] 2018-07-06 18:12
Agreed.  #4541 is a better description of the desired behavior.
