### ISSUE TITLE
fix spark performance regression on jenkins

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3437] opened 2017-08-11 19:41 UTC
We see a massive (18x) slowdown of our spark performance tests on jenkins.  The failures started on July 20th.

The last good build was of a21447f.  Which leaves one of:
 - 4c697e06ea33c9179840c81c843658442c82a951:  Move to google-cloud-java snapshot with more robust retries, and set …  
 - 1bc0bbfc5a2240e85fd4b9f9010673c7242552a0 Filter Mutect2 artifacts that arise from apparent-duplicate reads

as the culprit.  It seems more likely that the google cloud changes are causing the slowdown.
It seems like the slowdown is happening because of a change in the scattering, going from many partitions to fewer partitions which then all get scheduled on the same shard.
It's not immediately obvious what's causing this

**Comment by tomwhite** [comment] 2017-08-15 14:32
I can confirm this too. When I reverted https://github.com/broadinstitute/gatk/commit/4c697e06ea33c9179840c81c843658442c82a951 the problem disappeared, so that seems to be the culprit.

This is definitely a GCS issue, as I don't see the problem when running with HDFS inputs.

More details: for ReadsPipelineSpark, the first job has the following stages when running OK:
* Stage ID 0, mapToPair at MarkDuplicatesSparkUtils.java:56, 147 partitions
* Stage ID 1, flatMapToPair at MarkDuplicatesSparkUtils.java:60, 1880 partitions

And the following when there's only a single partition:
* Stage ID 0, mapToPair at MarkDuplicatesSparkUtils.java:56, 294 partitions
* Stage ID 1, flatMapToPair at MarkDuplicatesSparkUtils.java:60, **_1 partition_**

I wonder if the GCS code called by `BucketUtils.dirSize` has changed somehow, since it's used by `GATKSparkTool.getRecommendedNumReducers()` to get the number of reducers.

**Comment by tomwhite** [comment] 2017-08-15 14:56
It looks like the problem is that the GCS behaviour of [Files.list](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#list-java.nio.file.Path-) has changed for a regular file - it used to return the file itself (even though it's not a directory), but now it returns nothing. The fix is to add a case to check if the path is a regular file here: https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java#L294.

**Comment by droazen** [comment] 2017-08-15 14:57
@tomwhite Nice catch -- possibly a side effect of the fix in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2124?

**Comment by lbergelson** [comment] 2017-08-15 15:10
Yes, nice find indeed!

**Comment by tomwhite** [comment] 2017-08-31 13:03
@lbergelson I've created a PR in #3539 that fixes this.

**Comment by tomwhite** [comment] 2017-09-01 15:55
@lbergelson do any of the Jenkins jobs need reenabling? I see gatk-perf-test-spark-markeddupe and gatk-perf-test-spark-readpipeline are disabled - or were they disabled for another reason?

**Comment by lbergelson** [comment] 2017-09-01 15:59
@tomwhite Yes, they need to be re-enabled, they were disabled because of this issue.

**Comment by lbergelson** [comment] 2017-09-01 20:00
Hmn, sparktests on jenkins are still failing.  We may have declared victory too early.

**Comment by tomwhite** [comment] 2017-09-05 09:03
Both gatk-perf-test-spark-markeddupe and gatk-perf-test-spark-readpipeline have been passing for the last few days, so I'll close this now.

**Closed by tomwhite** 2017-09-05 09:03 UTC
Labels: bug, performance, Spark, tests
