### ISSUE TITLE
Null pointer exception in FastaAlternateReferenceMaker

### ISSUE THREAD

**Issue by kdmurray91** [broadinstitute/gatk#6434] opened 2020-02-03 04:48 UTC
### Affected tool(s) or class(es)

FastaAlternateReferenceMaker

### Affected version(s)
- [x] Latest public release version 4.1.4.1
- [ ] Latest master branch as of [date of test?]

### Description 

A null pointer exception in 

#### Steps to reproduce

We called variants with HaplotypeCaller & use resulting VCF with FastaAlternateReferenceMaker. See command below, but only reference fasta & HC vcf are given as input (no snp masking or interval list, though error also occurs when using interval list with multiple -L calls).

#### Expected behavior

Alternate-adjusted reference file or at least a helpful error message.

#### Actual behavior

```
+ latest-gatk/gatk-4.1.4.1/gatk FastaAlternateReferenceMaker -R /g/data/xe2/references/eucalyptus/emel_scott/Emelliodora_CSIROg1_SISH00000000.1.fasta -O consensus_sequences_gatk//CCA0704.fasta.tmp -V pergene_gatk/CCA0704/CCA0704.vcf.gz
Using GATK jar /g/data/xe2/users/stephen-rodgers/latest-gatk/gatk-4.1.4.1/gatk-package-4.1.4.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /g/data/xe2/users/stephen-rodgers/latest-gatk/gatk-4.1.4.1/gatk-package-4.1.4.1-local.jar FastaAlternateReferenceMaker -R /g/data/xe2/references/eucalyptus/emel_scott/Emelliodora_CSIROg1_SISH00000000.1.fasta -O consensus_sequences_gatk//CCA0704.fasta.tmp -V pergene_gatk/CCA0704/CCA0704.vcf.gz
15:43:14.276 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/g/data/xe2/users/stephen-rodgers/latest-gatk/gatk-4.1.4.1/gatk-package-4.1.4.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
Feb 03, 2020 3:43:15 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
15:43:15.230 INFO  FastaAlternateReferenceMaker - ------------------------------------------------------------
15:43:15.230 INFO  FastaAlternateReferenceMaker - The Genome Analysis Toolkit (GATK) v4.1.4.1
15:43:15.230 INFO  FastaAlternateReferenceMaker - For support and documentation go to https://software.broadinstitute.org/gatk/
15:43:15.231 INFO  FastaAlternateReferenceMaker - Executing as kdm801@gadi-login-01.gadi.nci.org.au on Linux v4.18.0-80.11.2.el8_0.x86_64 amd64
15:43:15.240 INFO  FastaAlternateReferenceMaker - Java runtime: OpenJDK 64-Bit Server VM v13+33
15:43:15.240 INFO  FastaAlternateReferenceMaker - Start Date/Time: 3 February 2020 at 3:43:14 pm AEDT
15:43:15.240 INFO  FastaAlternateReferenceMaker - ------------------------------------------------------------
15:43:15.240 INFO  FastaAlternateReferenceMaker - ------------------------------------------------------------
15:43:15.241 INFO  FastaAlternateReferenceMaker - HTSJDK Version: 2.21.0
15:43:15.241 INFO  FastaAlternateReferenceMaker - Picard Version: 2.21.2
15:43:15.241 INFO  FastaAlternateReferenceMaker - HTSJDK Defaults.COMPRESSION_LEVEL : 2
15:43:15.241 INFO  FastaAlternateReferenceMaker - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
15:43:15.241 INFO  FastaAlternateReferenceMaker - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
15:43:15.241 INFO  FastaAlternateReferenceMaker - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
15:43:15.241 INFO  FastaAlternateReferenceMaker - Deflater: IntelDeflater
15:43:15.241 INFO  FastaAlternateReferenceMaker - Inflater: IntelInflater
15:43:15.241 INFO  FastaAlternateReferenceMaker - GCS max retries/reopens: 20
15:43:15.241 INFO  FastaAlternateReferenceMaker - Requester pays: disabled
15:43:15.241 INFO  FastaAlternateReferenceMaker - Initializing engine
15:43:17.851 INFO  FeatureManager - Using codec VCFCodec to read file file:///g/data/xe2/users/stephen-rodgers/pergene_gatk/CCA0704/CCA0704.vcf.gz
15:43:17.912 INFO  FastaAlternateReferenceMaker - Done initializing engine
15:43:17.913 INFO  FastaAlternateReferenceMaker - Shutting down engine
[3 February 2020 at 3:43:17 pm AEDT] org.broadinstitute.hellbender.tools.walkers.fasta.FastaAlternateReferenceMaker done. Elapsed time: 0.06 minutes.
Runtime.totalMemory()=118489088
java.lang.NullPointerException
        at org.broadinstitute.hellbender.tools.walkers.fasta.FastaReferenceMaker.closeTool(FastaReferenceMaker.java:141)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1052)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)

```

**Comment by lbergelson** [comment] 2020-02-03 16:56
@kdmurray91 Thanks for reporting this.  This is caused by a dumb oversight in the code.  I made a branch to fix it here: https://github.com/broadinstitute/gatk/pull/6435

I suspect you may have a different underlying error that was being hidden by this bug.  Please update if you have additional issues.

**Comment by kdmurray91** [comment] 2020-02-03 21:12
Great, thanks @lbergelson . Is there a nightly build of the .jar somewhere online? I'll post back with any additional errors if it seems as though I'm not the cause of them.

**Comment by lbergelson** [comment] 2020-02-03 22:43
@kdmurray91 Our nightly builds are kind of janky at the moment.  I built one for you and uploaded it [here](https://storage.googleapis.com/hellbender-test-logs/tmp/gatk-4.1.4.1-57-ga78bf17-SNAPSHOT.zip) to test it.  

I think this bug is fixed so I'm going to close this issue, feel free to reopen or open a new issue if you have further issues.

**Closed by lbergelson** 2020-02-03 22:43 UTC
Labels: bug
