### ISSUE TITLE
GenotypeGVCFs outputs samples with no reads as reference genotypes

### ISSUE THREAD

**Issue by mgrzy** [broadinstitute/gatk#7792] opened 2022-04-19 13:07 UTC
### Affected tool(s) or class(es)
GenotypeGVCFs

### Affected version(s)
- [X] Latest public release version

### Description 
GenotypeGVCFs outputs samples (individuals) with no reads (depth) as reference genotypes: 
0/0:0,0:0:0:.:.:0,0,0

or with very small number of reads, like 1:
0/0:1,0:1:3:.:.:0,3,31

I believe that this issue was also reported here:
https://gatk.broadinstitute.org/hc/en-us/community/posts/4476803114779-GenotypeGVCFs-Output-no-call-as-reference-genotypes

#### Steps to reproduce
I have followed all GATK steps with default settings. 

#### Expected behavior
I believe that samples with no reads (or very small number of reads) should be reported as missing, like:
./.

Thank you for your help,
Marcin

**Comment by droazen** [comment] 2022-04-25 18:34
@mgrzy Can you please confirm that you're running the latest released version of GATK (4.2.6.1)?

@ldgauthier Was this one of the issues from 4.2.5.0 that we fixed in 4.2.6.0 / 4.2.6.1?

**Comment by ldgauthier** [comment] 2022-04-25 18:56
@mgrzy are you running ReblockGVCF first?

This may be a break from previous behavior, but it gives all the information you need.  The genotype quality is zero in both cases, meaning we can't determine between two (or more) genotypes.  You can use the FORMAT DP value instead of looking for a no-call genotype.

**Comment by droazen** [comment] 2022-05-02 18:18
@ldgauthier Should this one be closed as "works as intended" then?

**Closed** 2022-05-09 17:46 UTC

**Comment by ldgauthier** [comment] 2022-05-19 14:25
Derek wrote a blog post with details and justification: https://gatk.broadinstitute.org/hc/en-us/articles/6012243429531
