### ISSUE TITLE
I am running sortsam and getting error Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/LoadSnappy

### ISSUE THREAD

**Issue by tushu1232** [broadinstitute/gatk#2300] opened 2016-12-07 08:47 UTC
[December 7, 2016 11:43:32 AM AST] Executing as root@hpc1 on Linux 2.6.32-358.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_66-b17; Version: Version:4.alpha.2-116-gdd7e19a-SNAPSHOT
11:43:32.131 INFO  SortSam - Defaults.BUFFER_SIZE : 131072
11:43:32.131 INFO  SortSam - Defaults.COMPRESSION_LEVEL : 5
11:43:32.131 INFO  SortSam - Defaults.CREATE_INDEX : false
11:43:32.131 INFO  SortSam - Defaults.CREATE_MD5 : false
11:43:32.131 INFO  SortSam - Defaults.CUSTOM_READER_FACTORY : 
11:43:32.131 INFO  SortSam - Defaults.EBI_REFERENCE_SERVICE_URL_MASK : http://www.ebi.ac.uk/ena/cram/md5/%s
11:43:32.131 INFO  SortSam - Defaults.NON_ZERO_BUFFER_SIZE : 131072
11:43:32.131 INFO  SortSam - Defaults.REFERENCE_FASTA : null
11:43:32.131 INFO  SortSam - Defaults.SAM_FLAG_FIELD_FORMAT : DECIMAL
11:43:32.131 INFO  SortSam - Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
11:43:32.131 INFO  SortSam - Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : false
11:43:32.131 INFO  SortSam - Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
11:43:32.131 INFO  SortSam - Defaults.USE_CRAM_REF_DOWNLOAD : false
11:43:32.131 INFO  SortSam - Deflater IntelDeflater
11:43:32.131 INFO  SortSam - Initializing engine
11:43:32.131 INFO  SortSam - Done initializing engine
11:43:42.134 INFO  SortSam - Shutting down engine
[December 7, 2016 11:43:42 AM AST] org.broadinstitute.hellbender.tools.picard.sam.SortSam done. Elapsed time: 0.17 minutes.
Runtime.totalMemory()=1890058240
Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/LoadSnappy
	at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:86)
	at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:52)
	at htsjdk.samtools.util.TempStreamFactory.getSnappyLoader(TempStreamFactory.java:42)
	at htsjdk.samtools.util.TempStreamFactory.wrapTempOutputStream(TempStreamFactory.java:74)
	at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:223)
	at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:166)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:192)
	at org.broadinstitute.hellbender.tools.picard.sam.SortSam.doWork(SortSam.java:52)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:112)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:62)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:96)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:103)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:116)
	at org.broadinstitute.hellbender.Main.main(Main.java:158)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.LoadSnappy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

**Comment by lbergelson** [comment] 2016-12-07 14:54
@tushu1232 Could you include your command line that you used to launch gatk?  Are you using the `gatk-launch` wrapper?

**Comment by lbergelson** [comment] 2016-12-07 14:56
I ask because it sounds very similar to #2026 which was fixed by adding  "-Dsnappy.disable=true" to the default jvm args in `gatk-launch` .

**Comment by tushu1232** [comment] 2016-12-07 15:05
I am executing the following command @lbergelson 
software/spark/gatk4latest/gatk-launch SortSam --input BAM_BWA/SRR2.sorted.bam --output hpcinfra/hadoop/test.bam --SORT_ORDER queryname

**Comment by zhipan** [comment] 2016-12-08 05:57
no... it is not related to #2026. it is a backward compatibility issue of snappy jar.

**Comment by tushu1232** [comment] 2016-12-13 16:29
Hello Team Any fixes on this issue.
So that we can test the BWASpark tool

**Comment by lbergelson** [comment] 2016-12-14 18:45
@tushu1232 Sorry for the delay.  I'm looking into this.  I think you've hit a serious bug in the gatk-launch script.  Do you have $GATK_LOCAL_JAR set in your environment?  

It looks like the case where a local jar is used instead of the wrapper script results in the environment variables not being properly defined, which means you end up hitting #2026.  If they were properly defined you should be seeing the line `Snappy is disabled via system property` included in your standard out.  

I've opened #2316 to deal with the issue.  Until that's fixed though, the workaround is to invoke the jars directly and add `-Dsnappy.disable=true`

i.e. `java -Dsnappy.disable=true  -jar $GATK_LOCAL_JAR SortSam --input BAM_BWA/SRR2.sorted.bam --output hpcinfra/hadoop/test.bam --SORT_ORDER queryname`

**Comment by lbergelson** [comment] 2016-12-14 18:47
If you're interested in BWASpark tool I might wait a bit.  There are a lot of issues with it as it currently stands, it's one of the least tested tools we have.  We have someone working on a different more efficient implementation of the bwa bindings that may eventually be integrated into mainline gatk, so we've sort of stopped most development on BWASparkEngine until we're clear on the direction that the new work is going to take.

**Comment by tushu1232** [comment] 2017-01-22 07:54
Hello Team,
Any update on this bug.Are there any fixes.

Thanks

**Comment by lbergelson** [comment] 2017-01-24 18:54
This bug has become part of a bigger effort to address how configure the gatk.  We're working on a general solution to avoid this sort of issue in the future.  We haven't addressed this specific subcase yet though.  For now the workaround I described above should work for you.  If it doesn't, let me know.

**Comment by tushu1232** [comment] 2017-02-21 12:30
I came across a new parameter related to bwamemIndexImage.How does one generate this.
Thanks

**Comment by lbergelson** [comment] 2017-03-21 19:12
@tushu1232 We've addressed this bug and I believe it should work now correctly if you run gatk-launch with the package jars.   I'm going to close this issue, feel free to reopen if it isn't solved for you.

 As to your other question about bwaMemIndexImage, there's a current pull request with a tool to generate this index from a set of bwa indexes.  See https://github.com/broadinstitute/gatk/pull/2452 which will be merged to master soon.

**Closed** 2017-03-21 19:12 UTC
Labels: bug

**Comment by bbimber** [comment] 2017-10-02 15:58
I've created a third party JAR that depends on GATK4 (4.beta.2).  I believe I just hit a similar issue; however, what's odd is that it seems intermittent (though i have n=2 on this tool so far):

[October 2, 2017 6:10:01 AM PDT] com.github.discvrseq.walkers.BackportLiftedVcf done. Elapsed time: 6.27 minutes.
Runtime.totalMemory()=45813334016
Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/LoadSnappy
	at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:86)
	at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:52)
	at htsjdk.samtools.util.TempStreamFactory.getSnappyLoader(TempStreamFactory.java:42)
	at htsjdk.samtools.util.TempStreamFactory.wrapTempOutputStream(TempStreamFactory.java:74)
	at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:223)
	at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:166)
	at com.github.discvrseq.walkers.BackportLiftedVcf.apply(BackportLiftedVcf.java:156)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:110)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:108)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:838)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:115)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:189)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
	at com.github.discvrseq.Main.main(Main.java:51)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.LoadSnappy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more

**Comment by lbergelson** [comment] 2017-10-02 18:43
@bbimber This issue is caused by an incompatibility between the version of snappy htsjdk uses and the versions that the rest of the world use.  The workaround was to add the system property`-Dsnappy.disable=true` which is set automatically by gatk-launch.  However, we just fixed the underlying problem in htsjdk and upgraded to use new version of snappy there, so it's a better idea to update to a newer gatk version that incorporates the newest htsjdk.  

Annoyingly, we've been unable to publish the newer beta releases to maven central because they rely on snapshot builds of dependencies that aren't in central.  We're working  to fix that issue, but until then, we publish continuous snapshots of every commit on our artifactory https://broadinstitute.jfrog.io/.

If you're using gradle you can add our repository to your project by adding this in your `repositories` block of the build file.

```
 maven {
        url "https://broadinstitute.jfrog.io/artifactory/libs-snapshot/" 
}
```

Then you can add a newer gatk dependency to your project:

```
compile(group: 'org.broadinstitute', name: 'gatk', version: '4.beta.5-53-g0598843-20170929.153234-1')
```

**Comment by bbimber** [comment] 2017-10-02 18:54
Great - i was hoping there might be this kind of a solution.  I will try this out.

**Comment by bbimber** [comment] 2017-10-02 19:04
in case someone else reads this, i think you mean:

url "https://broadinstitute.jfrog.io/broadinstitute/libs-snapshot/"

or at least that's what's successful on my machine.

**Comment by lbergelson** [comment] 2017-10-02 19:56
@bbimber Ack!  Sorry. The url changed at some point, and I copied an old version and updated it by hand and obviously messed it up.
