### ISSUE TITLE
Verbosity of Spark tools question

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3231] opened 2017-07-08 17:33 UTC
I'm using:

```
gatk-launch CreatePanelOfNormals \
    -I combinedcoverage_C.tsv \
    -O ponC.pon \
```
With or without `--disableSpark`.

The stdout logging is super verbose when using Spark. Changing with `--verbosity` does not allow for a summary level stdout that I can get with `--disableSpark`. 

@samuelklee notes that many of the Spark tools are very verbose. Is there a reason why we need the Spark mode to be so verbose @droazen @lbergelson?

**Comment by lbergelson** [comment] 2017-07-10 14:26
It's probably a consequence of #1370 which I don't think we've ever resolved.

**Comment by droazen** [comment] 2017-07-10 14:46
Closing as duplicate of https://github.com/broadinstitute/gatk/issues/1370

**Closed by droazen** 2017-07-10 14:46 UTC
