### ISSUE TITLE
gatk v4.14.0 does not recognize mathematical operators; " Invalid argument '>'"

### ISSUE THREAD

**Issue by efr3m** [broadinstitute/gatk#6241] opened 2019-11-01 10:46 UTC
I am using gatk v4.14.0. I want to filter the rawSNPs obtained from ```SelectVariants``` using the ```VariantFiltration``` function.
My vcf looks like this:
```contig00001     8227    .       A       G       40.68   .       AC=1;AF=0.100;AN=10;BaseQRankSum=-0.861;ClippingRankSum=0.000;DP=88;FS=13.035;MLEAC=1;MLEAF=0.100;MQ=60.00;MQRankSum=0.000;QD=0.46;ReadPosRankSum=-0.300;SOR=2.792      GT:AD:DP:GQ:PL  0/0/0/0/0/0/0/0/0/1:85,3:88:34:66,0,34,78,132,196,276,380,528,782,6199
    contig00001     8244    .       T       C       43.68   .       AC=1;AF=0.100;AN=10;BaseQRankSum=-0.838;ClippingRankSum=0.000;DP=80;FS=15.529;MLEAC=1;MLEAF=0.100;MQ=60.00;MQRankSum=0.000;QD=0.55;ReadPosRankSum=-1.716;SOR=2.783      GT:AD:DP:GQ:PL  0/0/0/0/0/0/0/0/0/1:77,3:80:31:69,0,31,71,119,178,251,347,482,716,5872
    contig00001     8846    .       C       T       72.68   .       AC=1;AF=0.100;AN=10;BaseQRankSum=0.659;ClippingRankSum=0.000;DP=88;FS=2.385;MLEAC=1;MLEAF=0.100;MQ=59.93;MQRankSum=0.273;QD=0.83;ReadPosRankSum=-4.696;SOR=1.102        GT:AD:DP:GQ:PL  0/0/0/0/0/0/0/0/0/1:84,4:88:31:98,0,31,72,124,186,264,366,510,759,3392
    contig00001     9854    .       A       G       42.69   .       AC=1;AF=0.100;AN=10;BaseQRankSum=0.463;ClippingRankSum=0.000;DP=79;FS=11.687;MLEAC=1;MLEAF=0.100;MQ=60.00;MQRankSum=0.000;QD=0.55;ReadPosRankSum=1.267;SOR=2.799        GT:AD:DP:GQ:PL  0/0/0/0/0/0/0/0/0/1:74,3:77:29:68,0,29,66,111,166,235,324,450,665,2970
    contig00001     19796   .       A       G       34.70   .       AC=1;AF=0.100;AN=10;BaseQRankSum=-2.543;ClippingRankSum=0.000;DP=66;FS=10.825;MLEAC=1;MLEAF=0.100;MQ=60.00;MQRankSum=0.000;QD=0.53;ReadPosRankSum=-0.600;SOR=0.829      GT:AD:DP:GQ:PL  0/0/0/0/0/0/0/0/0/1:63,3:66:23:60,0,23,54,93,140,199,275,384,572,2745
    contig00001     20699   .       T       C       47.70   .       AC=1;AF=0.100;AN=10;BaseQRankSum=0.326;ClippingRankSum=0.000;DP=66;FS=2.442;MLEAC=1;MLEAF=0.1
```

When I run 

```gatk VariantFiltration -V GenomeA.rawSNPs.vcf -filter "QD < 20.0"  --filter-name "snp_def" -O test.vcf```

or

```gatk VariantFiltration -R ../GenomeA_contigs.fa -V GenomeA.rawSNPs.vcf -filter "QD < 20.0"  --filter-name "snp_def" -O test.vcf```

I get the following error:

```A USER ERROR has occurred: Invalid argument '>'.```

I tried to use different operators and style ```""``` rather than ```''``` but the error is still the same.
I was hoping that there is a mistake in my code but it seems to be a bug to me.
I run on a HPC with a slurm managing system. 
Thank you

**Comment by cmnbroad** [comment] 2019-11-01 12:55
@efr3m This syntax seems to work fine for me using both single and double quotes (and bash), so I don't see any evidence of a bug. Have you tried running the same command directly ? Do you see the same error ?

**Comment by efr3m** [comment] 2019-11-01 12:59
I run the same command directly without submitting to a the HPC. Might this be a Java issue? I am not quite sure how to check that. Thank you very much for your help

**Comment by cmnbroad** [comment] 2019-11-01 13:00
Can you post the entire command line output from a local run ?

**Comment by efr3m** [comment] 2019-11-01 13:05
````
[romano@NBI-HPC interactive output.HW10snps.515963]$ gatk VariantFiltration -R ../GenomeA_contigs.fa -V GenomeA.rawSNPs.vcf -O test.vcf --filter-name "snp" --filter-expression "QD < 20.0"
Using GATK jar /gatk/gatk-package-4.1.4.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gatk/gatk-package-4.1.4.0-local.jar VariantFiltration -R ../GenomeA_contigs.fa -V GenomeA.rawSNPs.vcf -O test.vcf --filter-name snp --filter-expression QD < 20.0
USAGE: VariantFiltration [arguments]

Filter variant calls based on INFO and/or FORMAT annotations.
Version:4.1.4.0


Required Arguments:

--output,-O:String            File to which variants should be written  Required.

--variant,-V:String           A VCF file containing variants  Required.


Optional Arguments:

--add-output-sam-program-record,-add-output-sam-program-record:Boolean
                              If true, adds a PG tag to created SAM/BAM/CRAM files.  Default value: true. Possible
                              values: {true, false}

--add-output-vcf-command-line,-add-output-vcf-command-line:Boolean
                              If true, adds a command line header line to created VCF files.  Default value: true.
                              Possible values: {true, false}

--arguments_file:File         read one or more arguments files and add them to the command line  This argument may be
                              specified 0 or more times. Default value: null.

--cloud-index-prefetch-buffer,-CIPB:Integer
                              Size of the cloud-only prefetch buffer (in MB; 0 to disable). Defaults to
                              cloudPrefetchBuffer if unset.  Default value: -1.

--cloud-prefetch-buffer,-CPB:Integer
                              Size of the cloud-only prefetch buffer (in MB; 0 to disable).  Default value: 40.

--cluster-size,-cluster:Integer
                              The number of SNPs which make up a cluster. Must be at least 2  Default value: 3.

--cluster-window-size,-window:Integer
                              The window size (in bases) in which to evaluate clustered SNPs  Default value: 0.

--create-output-bam-index,-OBI:Boolean
                              If true, create a BAM/CRAM index when writing a coordinate-sorted BAM/CRAM file.  Default
                              value: true. Possible values: {true, false}

--create-output-bam-md5,-OBM:Boolean
                              If true, create a MD5 digest for any BAM/SAM/CRAM file created  Default value: false.
                              Possible values: {true, false}

--create-output-variant-index,-OVI:Boolean
                              If true, create a VCF index when writing a coordinate-sorted VCF file.  Default value:
                              true. Possible values: {true, false}

--create-output-variant-md5,-OVM:Boolean
                              If true, create a a MD5 digest any VCF file created.  Default value: false. Possible
                              values: {true, false}

--disable-bam-index-caching,-DBIC:Boolean
                              If true, don't cache bam indexes, this will reduce memory requirements but may harm
                              performance if many intervals are specified.  Caching is automatically disabled if there
                              are no intervals specified.  Default value: false. Possible values: {true, false}

--disable-read-filter,-DF:String
                              Read filters to be disabled before analysis  This argument may be specified 0 or more
                              times. Default value: null. Possible Values: {WellformedReadFilter}

--disable-sequence-dictionary-validation,-disable-sequence-dictionary-validation:Boolean
                              If specified, do not check the sequence dictionaries from our inputs for compatibility.
                              Use at your own risk!  Default value: false. Possible values: {true, false}

--exclude-intervals,-XL:StringOne or more genomic intervals to exclude from processing  This argument may be specified 0
                              or more times. Default value: null.

--filter-expression,-filter:String
                              One or more expressions used with INFO fields to filter  This argument may be specified 0
                              or more times. Default value: null.

--filter-name:String          Names to use for the list of filters  This argument may be specified 0 or more times.
                              Default value: null.

--filter-not-in-mask:Boolean  Filter records NOT in given input mask.  Default value: false. Possible values: {true,
                              false}

--gatk-config-file:String     A configuration file to use with the GATK.  Default value: null.

--gcs-max-retries,-gcs-retries:Integer
                              If the GCS bucket channel errors out, how many times it will attempt to re-initiate the
                              connection  Default value: 20.

--gcs-project-for-requester-pays:String
                              Project to bill when accessing "requester pays" buckets. If unset, these buckets cannot be
                              accessed.  Default value: .

--genotype-filter-expression,-G-filter:String
                              One or more expressions used with FORMAT (sample/genotype-level) fields to filter (see
                              documentation guide for more info)  This argument may be specified 0 or more times.
                              Default value: null.

--genotype-filter-name,-G-filter-name:String
                              Names to use for the list of sample/genotype filters (must be a 1-to-1 mapping); this name
                              is put in the FILTER field for variants that get filtered  This argument may be specified
                              0 or more times. Default value: null.

--help,-h:Boolean             display the help message  Default value: false. Possible values: {true, false}

--input,-I:String             BAM/SAM/CRAM file containing reads  This argument may be specified 0 or more times.
                              Default value: null.

--interval-exclusion-padding,-ixp:Integer
                              Amount of padding (in bp) to add to each interval you are excluding.  Default value: 0.

--interval-merging-rule,-imr:IntervalMergingRule
                              Interval merging rule for abutting intervals  Default value: ALL. Possible values: {ALL,
                              OVERLAPPING_ONLY}

--interval-padding,-ip:IntegerAmount of padding (in bp) to add to each interval you are including.  Default value: 0.

--interval-set-rule,-isr:IntervalSetRule
                              Set merging approach to use for combining interval inputs  Default value: UNION. Possible
                              values: {UNION, INTERSECTION}

--intervals,-L:String         One or more genomic intervals over which to operate  This argument may be specified 0 or
                              more times. Default value: null.

--invalidate-previous-filters:Boolean
                              Remove previous filters applied to the VCF  Default value: false. Possible values: {true,
                              false}

--invert-filter-expression,-invfilter:Boolean
                              Invert the selection criteria for --filter-expression  Default value: false. Possible
                              values: {true, false}

--invert-genotype-filter-expression,-invG-filter:Boolean
                              Invert the selection criteria for --genotype-filter-expression  Default value: false.
                              Possible values: {true, false}

--lenient,-LE:Boolean         Lenient processing of VCF files  Default value: false. Possible values: {true, false}

--mask,-mask:FeatureInput     Input mask  Default value: null.

--mask-extension:Integer      How many bases beyond records from a provided 'mask' should variants be filtered  Default
                              value: 0.

--mask-name:String            The text to put in the FILTER field if a 'mask' is provided and overlaps with a variant
                              call  Default value: Mask.

--missing-values-evaluate-as-failing:Boolean
                              When evaluating the JEXL expressions, missing values should be considered failing the
                              expression  Default value: false. Possible values: {true, false}

--QUIET:Boolean               Whether to suppress job-summary info on System.err.  Default value: false. Possible
                              values: {true, false}

--read-filter,-RF:String      Read filters to be applied before analysis  This argument may be specified 0 or more
                              times. Default value: null. Possible Values: {AlignmentAgreesWithHeaderReadFilter,
                              AllowAllReadsReadFilter, AmbiguousBaseReadFilter, CigarContainsNoNOperator,
                              FirstOfPairReadFilter, FragmentLengthReadFilter, GoodCigarReadFilter,
                              HasReadGroupReadFilter, IntervalOverlapReadFilter, LibraryReadFilter, MappedReadFilter,
                              MappingQualityAvailableReadFilter, MappingQualityNotZeroReadFilter,
                              MappingQualityReadFilter, MatchingBasesAndQualsReadFilter, MateDifferentStrandReadFilter,
                              MateOnSameContigOrNoMappedMateReadFilter, MateUnmappedAndUnmappedReadFilter,
                              MetricsReadFilter, NonChimericOriginalAlignmentReadFilter,
                              NonZeroFragmentLengthReadFilter, NonZeroReferenceLengthAlignmentReadFilter,
                              NotDuplicateReadFilter, NotOpticalDuplicateReadFilter, NotSecondaryAlignmentReadFilter,
                              NotSupplementaryAlignmentReadFilter, OverclippedReadFilter, PairedReadFilter,
                              PassesVendorQualityCheckReadFilter, PlatformReadFilter, PlatformUnitReadFilter,
                              PrimaryLineReadFilter, ProperlyPairedReadFilter, ReadGroupBlackListReadFilter,
                              ReadGroupReadFilter, ReadLengthEqualsCigarLengthReadFilter, ReadLengthReadFilter,
                              ReadNameReadFilter, ReadStrandFilter, SampleReadFilter, SecondOfPairReadFilter,
                              SeqIsStoredReadFilter, SoftClippedReadFilter, ValidAlignmentEndReadFilter,
                              ValidAlignmentStartReadFilter, WellformedReadFilter}

--read-index,-read-index:String
                              Indices to use for the read inputs. If specified, an index must be provided for every read
                              input and in the same order as the read inputs. If this argument is not specified, the
                              path to the index for each input will be inferred automatically.  This argument may be
                              specified 0 or more times. Default value: null.

--read-validation-stringency,-VS:ValidationStringency
                              Validation stringency for all SAM/BAM/CRAM/SRA files read by this program.  The default
                              stringency value SILENT can improve performance when processing a BAM file in which
                              variable-length data (read, qualities, tags) do not otherwise need to be decoded.  Default
                              value: SILENT. Possible values: {STRICT, LENIENT, SILENT}

--reference,-R:String         Reference sequence  Default value: null.

--seconds-between-progress-updates,-seconds-between-progress-updates:Double
                              Output traversal statistics every time this many seconds elapse  Default value: 10.0.

--sequence-dictionary,-sequence-dictionary:String
                              Use the given sequence dictionary as the master/canonical sequence dictionary.  Must be a
                              .dict file.  Default value: null.

--set-filtered-genotype-to-no-call:Boolean
                              Set filtered genotypes to no-call  Default value: false. Possible values: {true, false}

--sites-only-vcf-output:Boolean
                              If true, don't emit genotype fields when writing vcf file output.  Default value: false.
                              Possible values: {true, false}

--tmp-dir:GATKPathSpecifier   Temp directory to use.  Default value: null.

--use-jdk-deflater,-jdk-deflater:Boolean
                              Whether to use the JdkDeflater (as opposed to IntelDeflater)  Default value: false.
                              Possible values: {true, false}

--use-jdk-inflater,-jdk-inflater:Boolean
                              Whether to use the JdkInflater (as opposed to IntelInflater)  Default value: false.
                              Possible values: {true, false}

--verbosity,-verbosity:LogLevel
                              Control verbosity of logging.  Default value: INFO. Possible values: {ERROR, WARNING,
                              INFO, DEBUG}

--version:Boolean             display the version number for this tool  Default value: false. Possible values: {true,
                              false}


Advanced Arguments:

--disable-tool-default-read-filters,-disable-tool-default-read-filters:Boolean
                              Disable all tool default read filters (WARNING: many tools will not function correctly
                              without their default read filters on)  Default value: false. Possible values: {true,
                              false}

--showHidden,-showHidden:Boolean
                              display hidden arguments  Default value: false. Possible values: {true, false}

Conditional Arguments for readFilter:

Valid only if "AmbiguousBaseReadFilter" is specified:
--ambig-filter-bases:Integer  Threshold number of ambiguous bases. If null, uses threshold fraction; otherwise,
                              overrides threshold fraction.  Default value: null.  Cannot be used in conjuction with
                              argument(s) maxAmbiguousBaseFraction

--ambig-filter-frac:Double    Threshold fraction of ambiguous bases  Default value: 0.05.  Cannot be used in conjuction
                              with argument(s) maxAmbiguousBases

Valid only if "FragmentLengthReadFilter" is specified:
--max-fragment-length:Integer Maximum length of fragment (insert size)  Default value: 1000000.

--min-fragment-length:Integer Minimum length of fragment (insert size)  Default value: 0.

Valid only if "IntervalOverlapReadFilter" is specified:
--keep-intervals:String       One or more genomic intervals to keep  This argument must be specified at least once.
                              Required.

Valid only if "LibraryReadFilter" is specified:
--library,-library:String     Name of the library to keep  This argument must be specified at least once. Required.

Valid only if "MappingQualityReadFilter" is specified:
--maximum-mapping-quality:Integer
                              Maximum mapping quality to keep (inclusive)  Default value: null.

--minimum-mapping-quality:Integer
                              Minimum mapping quality to keep (inclusive)  Default value: 10.

Valid only if "OverclippedReadFilter" is specified:
--dont-require-soft-clips-both-ends:Boolean
                              Allow a read to be filtered out based on having only 1 soft-clipped block. By default,
                              both ends must have a soft-clipped block, setting this flag requires only 1 soft-clipped
                              block  Default value: false. Possible values: {true, false}

--filter-too-short:Integer    Minimum number of aligned bases  Default value: 30.

Valid only if "PlatformReadFilter" is specified:
--platform-filter-name:String Platform attribute (PL) to match  This argument must be specified at least once. Required.

Valid only if "PlatformUnitReadFilter" is specified:
--black-listed-lanes:String   Platform unit (PU) to filter out  This argument must be specified at least once. Required.

Valid only if "ReadGroupBlackListReadFilter" is specified:
--read-group-black-list:StringThe name of the read group to filter out  This argument must be specified at least once.
                              Required.

Valid only if "ReadGroupReadFilter" is specified:
--keep-read-group:String      The name of the read group to keep  Required.

Valid only if "ReadLengthReadFilter" is specified:
--max-read-length:Integer     Keep only reads with length at most equal to the specified value  Required.

--min-read-length:Integer     Keep only reads with length at least equal to the specified value  Default value: 1.

Valid only if "ReadNameReadFilter" is specified:
--read-name:String            Keep only reads with this read name  Required.

Valid only if "ReadStrandFilter" is specified:
--keep-reverse-strand-only:Boolean
                              Keep only reads on the reverse strand  Required. Possible values: {true, false}

Valid only if "SampleReadFilter" is specified:
--sample,-sample:String       The name of the sample(s) to keep, filtering out all others  This argument must be
                              specified at least once. Required.

Valid only if "SoftClippedReadFilter" is specified:
--invert-soft-clip-ratio-filter:Boolean
                              Inverts the results from this filter, causing all variants that would pass to fail and
                              visa-versa.  Default value: false. Possible values: {true, false}

--soft-clipped-leading-trailing-ratio:Double
                              Threshold ratio of soft clipped bases (leading / trailing the cigar string) to total bases
                              in read for read to be filtered.  Default value: null.  Cannot be used in conjuction with
                              argument(s) minimumSoftClippedRatio

--soft-clipped-ratio-threshold:Double
                              Threshold ratio of soft clipped bases (anywhere in the cigar string) to total bases in
                              read for read to be filtered.  Default value: null.  Cannot be used in conjuction with
                              argument(s) minimumLeadingTrailingSoftClippedRatio


***********************************************************************

A USER ERROR has occurred: Invalid argument '<'.

***********************************************************************
````

**Comment by cmnbroad** [comment] 2019-11-01 16:02
Hm, not sure why thats happening. The parser doesn't seem to be seeing the full expression as a single argument value (though as I mentioned that command line works fine for me). I'd suggest trying a few alternatives/permutations, such as using `"QD lt 2.0"` instead of `"QD < 2.0"`; using the long name for the arg `--filter-expression`, or changing the order of the args, to see how/if you get different results.

**Comment by efr3m** [comment] 2019-11-01 16:09
Thank you very much @cmnbroad . I really appreciate your help. I tried all the things you suggested, but I still get the error.
The program was installed in a singularity container using docker img. Do you think tha it might be a java issue?

**Comment by cmnbroad** [comment] 2019-11-01 18:05
Not sure how java could cause this, but what version of java are you running. Above you said you ran it locally without submitting, but you didn't say whether or not that worked. Does it work locally for you ? When you use `lt` instead of `<`, is the error message exactly the same except for the `lt` ? (i.e., is it `A USER ERROR has occurred: Invalid argument 'lt'`)

**Comment by cmnbroad** [comment] 2020-02-10 17:20
Closing this since we can't seem to reproduce it without more info. @efr3m please feel free to reopen if you have more info or continue to see this.

**Closed by cmnbroad** 2020-02-10 17:20 UTC
