### ISSUE TITLE
The covariates table is missing ReadGroup

### ISSUE THREAD

**Issue by DuyDN** [broadinstitute/gatk#7549] opened 2021-11-08 13:39 UTC
Hi
I tried to run the recalibration using the gatk-generated vcf file as a known vcf file. I got an error which has been previously described "The covariates table is missing ReadGroup V300019285_L2_  in RecalTable0" but without the solution. 
I am wondering if the solution has been found. Anyone has the experience to fix this issue.
Thank 
**This is the batch file** 
java -Xmx16g -jar /scratch/ddo/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar ApplyBQSR \
-R /scratch/ddo/refgenomenew/New_IDs.fasta \
-I /scratch/ddo/markedsam/C18-436P.sort.rmdup.bam \
--bqsr-recal-file /scratch/ddo/reclibration/gatkmf01_C18-436P.recal_data.table \
-O /scratch/ddo/reclibration/C18-436P.bqsr.maf01.bam 

**This is the log file**
-----------------------------------------------------------------------------------------------------
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
04:59:42.641 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/scratch/ddo/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Nov 08, 2021 4:59:43 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
04:59:43.044 INFO  ApplyBQSR - ------------------------------------------------------------
04:59:43.045 INFO  ApplyBQSR - The Genome Analysis Toolkit (GATK) v4.1.9.0
04:59:43.045 INFO  ApplyBQSR - For support and documentation go to https://software.broadinstitute.org/gatk/
04:59:43.045 INFO  ApplyBQSR - Executing as  on Linux v3.10.0-1160.36.2.el7.x86_64 amd64
04:59:43.045 INFO  ApplyBQSR - Java runtime: OpenJDK 64-Bit Server VM v13.0.2+8
04:59:43.045 INFO  ApplyBQSR - Start Date/Time: November 8, 2021 at 4:59:42 a.m. PST
04:59:43.045 INFO  ApplyBQSR - ------------------------------------------------------------
04:59:43.045 INFO  ApplyBQSR - ------------------------------------------------------------
04:59:43.046 INFO  ApplyBQSR - HTSJDK Version: 2.23.0
04:59:43.046 INFO  ApplyBQSR - Picard Version: 2.23.3
04:59:43.046 INFO  ApplyBQSR - HTSJDK Defaults.COMPRESSION_LEVEL : 2
04:59:43.046 INFO  ApplyBQSR - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
04:59:43.046 INFO  ApplyBQSR - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
04:59:43.046 INFO  ApplyBQSR - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
04:59:43.046 INFO  ApplyBQSR - Deflater: IntelDeflater
04:59:43.046 INFO  ApplyBQSR - Inflater: IntelInflater
04:59:43.046 INFO  ApplyBQSR - GCS max retries/reopens: 20
04:59:43.046 INFO  ApplyBQSR - Requester pays: disabled
04:59:43.047 INFO  ApplyBQSR - Initializing engine
WARNING: BAM index file /scratch/ddo/markedsam/C18-436P.sort.rmdup.bam.bai is older than BAM /scratch/ddo/markedsam/C18-436P.sort.rmdup.bam
04:59:43.556 INFO  ApplyBQSR - Done initializing engine
04:59:43.592 WARN  ApplyBQSR - This tool has only been well tested on ILLUMINA-based sequencing data. For other data use at your own risk.
04:59:43.592 INFO  ProgressMeter - Starting traversal
04:59:43.592 INFO  ProgressMeter -        Current Locus  Elapsed Minutes       Reads Processed     Reads/Minute
04:59:45.014 INFO  ApplyBQSR - Shutting down engine
[November 8, 2021 at 4:59:45 a.m. PST] org.broadinstitute.hellbender.tools.walkers.bqsr.ApplyBQSR done. Elapsed time: 0.05 minutes.
Runtime.totalMemory()=557842432
java.lang.IllegalStateException: **The covariates table is missing ReadGroup V300019285_L2_  in RecalTable0**
	at org.broadinstitute.hellbender.utils.Utils.validate(Utils.java:750)
	at org.broadinstitute.hellbender.utils.recalibration.covariates.ReadGroupCovariate.keyForReadGroup(ReadGroupCovariate.java:81)
	at org.broadinstitute.hellbender.utils.recalibration.covariates.ReadGroupCovariate.recordValues(ReadGroupCovariate.java:53)
	at org.broadinstitute.hellbender.utils.recalibration.covariates.StandardCovariateList.recordAllValuesInStorage(StandardCovariateList.java:133)
	at org.broadinstitute.hellbender.utils.recalibration.RecalUtils.computeCovariates(RecalUtils.java:546)
	at org.broadinstitute.hellbender.utils.recalibration.RecalUtils.computeCovariates(RecalUtils.java:527)
	at org.broadinstitute.hellbender.transformers.BQSRReadTransformer.apply(BQSRReadTransformer.java:145)
	at org.broadinstitute.hellbender.transformers.BQSRReadTransformer.apply(BQSRReadTransformer.java:27)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:94)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by droazen** [comment] 2021-11-08 19:20
@DuyDN This is a known issue in BQSR -- see https://github.com/broadinstitute/gatk/issues/6242. Sorry for the inconvenience! We hope to be able to develop a fix within the next several months.

The fact that you ran into this error indicates that there may not actually be any usable reads in that particular read group -- they were likely all filtered out by one of the BQSR filters, which filter out malformed, low mapping quality, unmapped, and secondary alignments. You could likely avoid the error by filtering out that read group using the `ReadGroupBlackListReadFilter` in GATK while running ApplyBQSR (`--read-filter ReadGroupBlackListReadFilter`)

**Comment by droazen** [comment] 2021-11-08 19:20
Closing as duplicate of https://github.com/broadinstitute/gatk/issues/6242

**Closed by droazen** 2021-11-08 19:20 UTC
