### ISSUE TITLE
Fix outdated usage examples copied from GATK3

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1632] opened 2016-03-25 19:06 UTC
Some tools have had usage examples ported from GATK3 that don't work in GATK4.  We should fix 
these. 

As well as fixing errors, it would be good to change the javadoc so it references parameters by the constant values instead of hardcoding them. (use `{@value StandardArgumentDefinitions#SOME_NAME}` )

These occur in at least the following tools, (found by `find in path -T`):
- [ ] ValidateVariants
- [ ] VariantFiltration
- [ ] AnalyzeCovariates
- [ ] BaseRecalibrator
- [ ] LeftAlignIndels

**Comment by droazen** [comment] 2017-03-22 19:06
Closing -- duplicate of https://github.com/broadinstitute/gatk/issues/182

**Closed by droazen** 2017-03-22 19:06 UTC
Labels: UserDoc
