### ISSUE TITLE
ASECountReader "sites" argument of GATK-3.8 

### ISSUE THREAD

**Issue by Erich-Hartm** [broadinstitute/gatk#7712] opened 2022-03-09 16:23 UTC
I calculated ASECount of genome resequence data by GATK-3.8 , but I want do the same test by GATK-4.0 ,  It's so strange when I use GATK-4.0 argument "--variants" to substitute "sites" of GATK-3.8 , the ERROR remaind me that the "SNP site is not hetero" , so l want to ask  
What is the mean of ASECountReader "sites" argument of GATK-3.8 ? and what is the corresponding argument in GATK-4.0 ? the answer is undocumented in instruction of "GATK-3.8 --help", so l want get exact answer, thank you !

**Comment by droazen** [comment] 2022-03-21 18:24
@meganshand Since you ported `ASEReadCounter` to GATK4, would you mind commenting on this one? Thanks!

**Comment by meganshand** [comment] 2022-03-31 13:05
I believe sites and variants should be equivalent. I see that there is a warning emitted by GATK4 at sites that are not het, but it shouldn't be an error. If you're getting an error can you please post the full message in this thread? 

ASEReadCounter will only process het sites in both GATK3 and GATK4, but it's possible that GATK3 silently skipped non-het sites rather than emitting a warning.

**Comment by meganshand** [comment] 2022-04-05 16:01
Duplicate of #7747

**Closed by meganshand** 2022-04-05 16:01 UTC
Labels: RNASeq
