### ISSUE TITLE
Section on GATK CNV caller needs to be added to methods doc.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2857] opened 2017-06-05 17:49 UTC
@samuelklee commented on [Fri May 20 2016](https://github.com/broadinstitute/gatk-protected/issues/521)

Also perhaps details of coverage collection?

---

@samuelklee commented on [Wed Oct 19 2016](https://github.com/broadinstitute/gatk-protected/issues/521#issuecomment-254861195)

Also coverage collection.

**Comment by sooheelee** [comment] 2017-12-11 23:21
Am I still needed on this one given the workflow has completely changed?

**Comment by samuelklee** [comment] 2017-12-12 03:08
@sooheelee Sorry, you weren't meant to be assigned to this.  The doc this issue refers to is the white paper on CNV methods.  Much of that will need to be rewritten for the new workflows.

**Comment by samuelklee** [comment] 2018-01-10 21:17
Dupe of #3005.

**Closed by samuelklee** 2018-01-10 21:17 UTC
Labels: Copy Number tools, UserDoc
