### ISSUE TITLE
GATK4 & Spark local memory error

### ISSUE THREAD

**Issue by hh1985** [broadinstitute/gatk#3465] opened 2017-08-21 07:52 UTC
Hi,
 I recently used GATK4 Spark local version for somatic variant call.  The machine has 40 cores and 160g mem.  I tried 20 and 10 cores for each tumor/normal pair in the BQSR step (BaseRecalibratorSpark)  and the two samples are processed at the same time.  However, the pipeline frequently failes (errors like outofmemory, cannot allocate a page) unless I use 4 cores for each sample. I think the problem should be solved by tuning Spark and JAVA parameters.   I considered options like `--conf spark.driver.memory=10g`, `-XX:ParallelGCThreads=10` but had no luck. Can someone suggest the parameter options that I should look at? 

Thanks,

-Han

**Comment by lbergelson** [comment] 2017-08-22 15:34
Hi @hh1985 

Memory tuning is pretty tricky and can depend on a lot of things.  How is your cluster configured  Are you using YARN?  Are you running in client or cluster mode?  

I'm assuming you're running with YARN.  Mesos should also work but I don't have any experience configuring it.  

BQSR should run safely with 4g of memory per core. (It should really work with much less I think, but 4 should definitely be sufficient.)  There are a few different parameters that can help you adjust the memory ratios.
A good tuning might be something like
 
```
--num-executors 5 
--executor-cores 8 
--executor-memory 32g 
```

if you're not running with gatk-launch you'll need to set
```
--conf spark.yarn.executor.memoryOverhead=600
```
Without setting a higher than default yarn memory overhead like this we see consistent crashes, it's included in the settings gatk-launch applies already.

That should run 5 separate executors with 8 cores each and give each one 32g, so 4g / core. 

If you're running in cluster mode you'll have to carve out some memory and cores for the driver.  You can set the driver settings with 
```
--driver-cores 2
--driver-memory 4g
``` 
or something along those lines.  The driver doesn't need much memory or computer for BQSR

In general we've had better luck using the entire cluster for one job and running jobs in sequence rather than trying to run two jobs simultaneously using a subset of the cluster.

**Comment by lbergelson** [comment] 2017-08-22 15:42
It just occured to me that you probably meant you were running with `--sparkMaster local[4]` not, on a local cluster (vs a cluster in the cloud).  In that case disregard my previous advice.  Running a single process spark isn't going to scale well to 40 cores whatever you do, you'd be better off installing spark locally on your machine and running it as a single node cluster than running in the local mode. 

If you want to run with master local, the biggest thing is probably to set -Xmx high enough, I'd set it as all of your memory - some overhead for the OS.

Maybe try something like:
`-Xmx 140G -XX:ParallelGCThreads=6 --sparkMasterLocal[40]

**Comment by hh1985** [comment] 2017-08-22 21:29
@lbergelson Thanks a lot for your suggestion!

**Comment by lbergelson** [comment] 2017-09-29 20:33
Closing this ticket since there hasn't been any discussion in a while.  Hopefully the problem is resolved.

**Closed by lbergelson** 2017-09-29 20:33 UTC
Labels: Spark
