### ISSUE TITLE
modify build.gradle to give a reasonable error if R isn't found

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#351] opened 2015-04-03 18:36 UTC
Basically the same issue as #336.  It stems from the same misunderstanding of how gradle exec works.

**Comment by akiezun** [comment] 2015-04-15 16:10
@lbergelson can you clarify the expected behavior? Why should it not fail - the build (tests) cannot complete without RScript

**Comment by lbergelson** [comment] 2015-04-15 16:13
It crashes with an exception instead of doing a partial build with failing
tests.

**Comment by akiezun** [comment] 2015-04-15 17:34
is this a bug? sounds like a feature

**Comment by lbergelson** [comment] 2015-04-15 17:37
It needs to be addressed to at least give a proper error message.  Right now it will confuse people.

**Comment by akiezun** [comment] 2015-04-19 17:16
not a bug then

**Comment by akiezun** [comment] 2015-04-20 01:39
@lbergelson please rename the issue to reflect what needs to be done

**Comment by akiezun** [comment] 2015-10-06 20:28
alpha candidate?

**Comment by droazen** [comment] 2017-03-22 17:50
@lbergelson Can we close this?

**Comment by droazen** [comment] 2017-03-22 17:54
This is done -- closing

**Closed by droazen** 2017-03-22 17:54 UTC
Labels: DeveloperDoc, ReleaseEngineering
