### ISSUE TITLE
AlignmentUtils.leftAlignIndel would remove a leading D without updating a read's start position

### ISSUE THREAD

**Issue by luoqi-git** [broadinstitute/gatk#1470] opened 2016-02-04 02:45 UTC
If the first element of a read's cigar becomes a D after left adjustment, it would be removed by cleanUpCigar(), but the caller has no way to know about this and fails to adjust the read's start position accordingly. The end result, a misaligned read.

**Comment by akiezun** [comment] 2016-02-06 02:10
@luoqi-git can you provide an input file and the commandline or code to reproduce the problem?

**Comment by luoqi-git** [comment] 2016-02-08 23:11
@akiezun it is a little hard to distill into a piece of executable code, but could be explained very easily: say you have a read with bases 'ACGT' mapped at position 100 of a reference sequence (AAACGT) with a cigar of 1M2D3M, and deletion could be left adjusted by one base, to a cigar of 2D4M (the read is still aligned to the reference correctly at this point); if you then drop the leading D in the cigar but without updating the read start position, you'd get the read (ACGT) mapped 4M at position 100 of the reference (AAAC), which is obviously incorrect. The correct result is, the read mapped at position 102 with a cigar of 4M.

**Comment by akiezun** [comment] 2016-02-13 01:55
`AlignmentUtils.leftAlignIndel' only returns the updated cigar and does not change the read's alignment. It does return 4M as you mention. I'm closing this - this is not a bug in AlignmentUtils.leftAlignIndel

**Closed by akiezun** 2016-02-13 01:55 UTC

**Comment by luoqi-git** [comment] 2016-02-13 02:21
Granted it is not AlignmentUtils.leftAlignIndel's problem alone. An API is a contract between the caller and the callee, this bug is a misunderstanding on this contract between the two parties. The caller doesn't expect the read start position needs to be changed, the callee has this information but unable to return to the caller with the current API form. The API needs updated so the callee can convey the information back to the caller.

A good example for such a caller can be found in the same AlignmentUtils class, the createReadAlignedToRef() function, it could return an incorrectly aligned read back to its caller.
