### ISSUE TITLE
implement non-raw annotations in AS_* classes

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1881] opened 2016-06-06 16:29 UTC
the allele-specific annotation only support the 'raw' mode now. this should be expanded to the normal mode too (ie annotation of vcf files, not gvcfs).

**Comment by droazen** [comment] 2017-03-22 19:46
Closing as duplicate of https://github.com/broadinstitute/gatk/issues/1893

**Closed by droazen** 2017-03-22 19:46 UTC
