### ISSUE TITLE
HaplotypeCaller consult for Laura

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#4561] opened 2018-03-22 20:13 UTC
For @ldgauthier, upon her return from the Montreal workshop. We would like to know if this is expected behavior from HaplotypeCaller.

Researcher has uploaded read-level data to our FTP site. I've recapitulated their results with GATK4 in a dsde-docs issue ticket at https://github.com/broadinstitute/dsde-docs/issues/3008. Data may be private so please follow up in the dsde-docs repo.

- original forum post: https://gatkforums.broadinstitute.org/gatk/discussion/comment/46939#Comment_46939

**Comment by ldgauthier** [comment] 2018-03-27 13:59
We were still making changes to the assembly in versions 3.2 and 3.3.  For example: https://github.com/broadinstitute/gsa-unstable/pull/582  Nothing is popping out at me as being the breaking change after 3.3 though.

I think the problem is that there are too many haplotypes in that region.  There are at least 8 plausible variants, which makes for ~256 haplotypes.  We pick the "best" 128 to evaluate likelihoods against.  Here it seems that what we're choosing as the best don't include the SNP.  But actually it's not even in the graph.
![image](https://user-images.githubusercontent.com/6578548/37971915-20641488-31a5-11e8-94aa-97086c219dd7.png)
(The 280 ref vs 211 split is the het SNP at 89,100,730 so the missing variant should be split out of the big reference string above but it's not)

The raw graph has the variant on a dangling head (I highlighted the base in the middle path in the figure of the raw_readthreading_graph), but it must not be merged back in properly.
![image](https://user-images.githubusercontent.com/6578548/37972067-790a6cf4-31a5-11e8-9e73-4f1ee12c982f.png)

I wonder if that PR above was the one that changed things.  Maybe @vruano will take a look?

**Comment by chandrans** [comment] 2018-03-28 16:30
Thank you Laura and Valentin for looking into this. @ldgauthier @vruano

**Comment by vruano** [comment] 2018-04-03 20:28
@ldgauthier do you still have the full image for the raw graph around? Is it possible for you to post it without make it blow up the screen (I guess there might be a markdown option to chose the disply size.

**Comment by ldgauthier** [comment] 2018-04-04 14:56
Yep, that looks like exactly what happens.
![image](https://user-images.githubusercontent.com/6578548/38315491-99590130-37f6-11e8-8ee3-22f274cd7db0.png)
(If that's not enough context, I can email you the .dot files -- github won't let me attach them)

I've never understood what it means when the whole branch has weight 1/1 with dashed arrow, like for the rightmost path.  Is that just to show that that will get pruned eventually?

**Closed** 2020-01-08 19:08 UTC
