### ISSUE TITLE
Contig ordering in VCF header is scrambled by either GenomicsDB, GenomicsDBImport, or GenotypeGVCFs

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2753] opened 2017-05-25 14:13 UTC
Broad production is finding that after running HG38 GVCFs through `GenomicsDBImport`, `GenomicsDB`, and then `GenotypeGVCFs`, the sort order of the contigs in the header is scrambled. Specifically, the contig names appear to be sorted by ASCII value, so, eg., "chr10" comes before "chr9". 

This is a problem, since there are tools that use the contig ordering in the header to generate contig indices used for comparison of relative contig ordering. `GatherVcfs` in Picard is one example.

We need to identify which of the three possible suspects above (`GenomicsDBImport`, `GenomicsDB`, or `GenotypeGVCFs`) is clobbering the contig ordering, and patch it quickly.

**Comment by droazen** [comment] 2017-05-25 14:15
@kgururaj @kdatta Can you guys comment on this? Do you think it's possible that `GenomicsDB` is failing to preserve the ordering of the contig header lines? We need a fix for this soon, as it's causing a bit of havoc in our pipeline.

**Comment by droazen** [comment] 2017-05-25 14:18
@lbergelson please also comment on whether it's possible that `GenotypeGVCFs` itself could be responsible.

**Comment by droazen** [comment] 2017-05-25 15:33
Another possible culprit here is the `VCFUtils.smartMergeHeaders()` call in `GenomicsDBImport` when running without a sample name map file (which is how production was running, in this case) -- @cmnbroad can you comment on this possibility?

**Comment by ronlevine** [comment] 2017-05-25 15:36
@droazen I fixed a similar issue in https://github.com/samtools/htsjdk/pull/848. The header from the input VCF or dictionary is put into a `TreeMap`, which stores the data in natural order. Since the key is a String, it's lexicographical. It should be stored in a `LinkedHashMap`, which maintains the order.

**Comment by ronlevine** [comment] 2017-05-25 15:39
@droazen `VCFUtils.smartMergeHeaders()` was fixed in https://github.com/samtools/htsjdk/pull/848.

**Comment by cmnbroad** [comment] 2017-05-25 15:55
@droazen Yeah, what @ronlevine mentioned could possibly do it, depending on where the data flows to next, i.e., if the header lines are then put back into a header, the contig line list in the new header should be correct (the big metadata list would still be off) though.

**Comment by cmnbroad** [comment] 2017-05-25 16:02
Hm. It looks like GDB importer merges, then creates a header from the resulting lines, then retrieves a sequence dictionary, which doesn't correct the order. So that may be it.

**Comment by cmnbroad** [comment] 2017-05-25 16:10
Candidate quick-fix [here](https://github.com/broadinstitute/gatk/tree/cn_gdb_import), if we determine that the problem.

**Comment by lbergelson** [comment] 2017-05-25 19:40
I can confirm that it's not GenotypeGVCFs on it's own.  Going to test @cmnbroad's branch now.

**Comment by ronlevine** [comment] 2017-05-25 19:48
@lbergelson Wouldn't a new release of HTSJDK fix the problem?

**Comment by lbergelson** [comment] 2017-05-25 19:53
@ronlevine Oohh, is that not yet in an htsjdk release?  It's one of the ones you've been waiting forever to have a proper release of?

**Comment by ronlevine** [comment] 2017-05-25 20:03
Not that I know of: https://github.com/samtools/htsjdk/releases. https://github.com/samtools/htsjdk/pull/848 was merged on April 8, 2017 and the last release was on February 21, 2017.

**Comment by droazen** [comment] 2017-05-26 21:09
Thanks @ronlevine ! Switching to an updated HTSJDK snapshot appears to fix this issue.

**Closed** 2017-05-26 21:49 UTC
Labels: bug, GenomicsDB, PRIORITY_HIGH
