### ISSUE TITLE
gCNV WDLs should clean up intermediate files and directories.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#5382] opened 2018-10-31 16:56 UTC
Due to the way the calling process is sharded upstream ... the current wdl expends 80-90% of the time copying files over ... so a job that takes around 1h only 10 minutes are expend in running the GATK Tool, the result is used to stage the input files. 

For example if the genome intervals where shared into 600 ~ different batches this results in 3600 ~ files transferred one by one using their own gsutil command. The reason why these are not batched is in part because files share name and multi-file gsutil cp does not provide the means to indicate indepedendent destination names for each input file. Recursive copy of a parent directory would drag the information from all the samples when the each task just deals with one.

**Comment by samuelklee** [comment] 2018-11-01 14:06
Yes, recall that @asmirnov239 tried to address #4397, but that led to #5217, so we reverted.  We can try to address this again correctly if it's low-hanging fruit (which it probably is) and if it'll bring the overall cost of the pipeline down significantly.  However, for the most part, I think bringing down costs in the gCNV step will have more impact.

Thanks for diagnosing and pointing out these issues.  You should feel free to open PRs against the gCNV code as well!

**Comment by samuelklee** [comment] 2018-11-07 18:14
@vruano As pointed out by @sooheelee, the current WDL does not clean up the intermediate CALLS_* and MODEL_* directories.  This is fine for running on the cloud, but we should clean them up when running locally.  Can you take care of this as well?

**Comment by samuelklee** [comment] 2019-01-31 15:40
Dupe of #4397, but changing the name to reflect the issue mentioned in the previous comment.

**Comment by samuelklee** [comment] 2019-02-15 13:50
CALLS_* and MODEL_* directories are actually cleaned up in #5414, but there are a few places where contig-ploidy calls are not cleaned up.

**Closed** 2019-03-12 20:31 UTC
Labels: Copy Number tools, Germline CNV, wdl
