### ISSUE TITLE
CompareBaseQualitiesSpark complains about reference for cram files even though i gave it one

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1321] opened 2015-12-09 18:17 UTC
`./gatk-launch CompareBaseQualities -I HCC1143.bqsr.bam -I2 HCC1143.bqsr.cram -R ../human_g1k_v37.fasta --disableSequenceDictionaryValidation`

results in 
`A USER ERROR has occurred: A reference file is required when using CRAM files.`

which is bogus because i passed in a reference

**Comment by droazen** [comment] 2015-12-09 23:19
alpha

**Comment by akiezun** [comment] 2015-12-10 15:37
I think the problem is that it uses a non-standard way to specify the second read input (using a new field rather than the standard input collection). 

I think this can wait past alpha - not a critical tool and not a standard way of using it. @droazen wdyt?

**Comment by droazen** [comment] 2015-12-11 21:00
Agreed @akiezun -- moving to beta

**Comment by droazen** [comment] 2016-03-10 21:22
@cmnbroad if you have time, feel free to have a look

**Comment by cmnbroad** [comment] 2016-03-11 21:30
I can't reproduce this problem. CompareBaseQualities accepts positional arguments for the two inputs, and rejects -I..-I2 altogether (I don't get the CRAM reference error, it fails on the -I). I've added some integration tests that use 2 CRAMs and a mix of CRAM and BAM, and the reference seems to be accepted fine. Let me know if I'm missing something.

**Comment by droazen** [comment] 2016-03-17 19:41
@akiezun Can you clarify -- is this bug invalid?

**Comment by droazen** [comment] 2016-03-18 13:43
@akiezun Perhaps you meant `CompareBaseQualitiesSpark` rather than `CompareBaseQualities`? The spark version takes `-I` and `-I2` args

**Comment by akiezun** [comment] 2016-03-18 13:43
yes, the tool got renamed in the meantime. The commandline is:
```
/gatk-launch CompareBaseQualitiesSpark -I ./src/test/resources/org/broadinstitute/hellbender/tools/print_reads.bam -I2 ./src/test/resources/org/broadinstitute/hellbender/tools/print_reads.cram -R ./src/test/resources/org/broadinstitute/hellbender/tools/print_reads.fasta --disableSequenceDictionaryValidation
```

the error is `A USER ERROR has occurred: A reference is required for CRAM input`

**Comment by akiezun** [comment] 2016-03-18 13:43
back to @cmnbroad

**Closed** 2016-03-25 19:14 UTC
Labels: bug, tests
