### ISSUE TITLE
Spark performance regression in BQSR and HC

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#4376] opened 2018-02-08 13:47 UTC
Running the reads pipeline on latest master on GCP on an exome shows a major performance regression. At the end of last year this took 40 minutes for the whole job, now using master BQSR is taking 1.4 hours, and HC is taking well over an hour (it hasn't finished yet).

#4278 is the likely culprit for the HC slowdown. Not sure about BQSR.

cc @lbergelson @droazen

**Comment by frank-y-liu** [comment] 2018-02-08 15:52
@tomwhite How many physical cores are you using? Is it a whole genome task? I was able  to finish BQSR in about an hour. From monitored activities, the CPU utilization rates are very high across all physical cores (so it's not bad). There is the long runtime of creating KnownSitesCache, as in #4264

**Comment by droazen** [comment] 2018-02-08 17:03
@tomwhite That's interesting -- @lbergelson 's profiling on `HaplotypeCallerSpark` in isolation did not show any noticeable slowdown as a result of the switch to the new code path (in addition to the output being much more correct than before), and the walker version which uses the same codepath is as fast or faster than GATK3 at this point in all modes. We should try to see whether we can replicate your results on our end. Can you provide more details on how you ran the tools?

The new `HaplotypeCaller` code path does result in the tool doing more work in some cases as compared to the early betas, particularly for genomic locations not covered by any reads -- but this work is necessary in order to produce correct output without boundary effects, and the fact that the early betas didn't do it was an oversight. I wonder if that could explain what you're seeing -- see the full discussion in https://github.com/broadinstitute/gatk/issues/4169.

There are also several ways in which `HaplotypeCallerSpark` currently makes suboptimal use of the new code path introduced in https://github.com/broadinstitute/gatk/pull/4278:

1. It uses only a single interval per shard, instead of many intervals as the walker version does (https://github.com/broadinstitute/gatk/issues/4299).

2. It materializes all of the assembly regions in a shard at once (https://github.com/broadinstitute/gatk/issues/4301), as opposed to the walker version which materializes the regions in a shard as lazily as possible.

3. The default read shard size may need adjusting (https://github.com/broadinstitute/gatk/issues/4298). The walker version creates one shard per contig, and lazily creates the assembly regions within that shard. That's obviously not possible for the Spark version, but I don't think that the effect of the shard size on performance has been measured yet for the Spark version.

**Comment by lbergelson** [comment] 2018-02-08 17:32
@tomwhite My tests were running HaplotypeCallerSpark on an exome on gcs.  It took ~40 minutes with and without the changes.

**Comment by lbergelson** [comment] 2018-02-08 17:34
Also, interestingly, if you look at the pipeline we run nightly in jenkins, there hasn't been any performance regression there.  https://gatk-jenkins.broadinstitute.org/view/Performance/job/gatk-perf-test-spark-readpipeline/buildTimeTrend

**Comment by droazen** [comment] 2018-02-08 18:00
Is it possible that the slowdown Tom is seeing is specific to the HDFS codepath, I wonder?

**Comment by tomwhite** [comment] 2018-02-09 09:31
This is what I ran (note it's not using the HDFS codepath). Can you try reproducing please? I used to be able to run this in 40 minutes (the whole pipeline, not just HC, and even BQSR is taking a lot longer now).

```bash
gatk ReadsPipelineSpark -I gs://broad-spark-eval-test-data/exome/NA12878.ga2.exome.maq.raw.bam -O gs://broad-spark-eval-test-data/exome/NA12878.ga2.exome.maq.raw.vcf -R
 gs://broad-spark-eval-test-data/exome/Homo_sapiens_assembly18.2bit --known-sites gs://broad-spark-eval-test-data/exome/dbsnp_138.hg18.vcf -pairHMM AVX_LOGLESS_CACHING --max-
reads-per-alignment-start 10 \
    -- \
    --spark-runner GCS --cluster tw-cluster-2 \
    --num-executors 8 --executor-cores 8 --executor-memory 32g \
    --driver-memory 4g \
    --conf spark.dynamicAllocation.enabled=false
```

**Comment by tomwhite** [comment] 2018-02-15 15:51
Using git bisect I found the commit that caused the performance regression: 8a366c7ba570c61338f7109b86c3284b80d5cf47.

If I revert this, then both BQSR and HC both take the expected amount of time running on an exome (~15 min, ~10 min, respectively).

**Comment by droazen** [comment] 2018-02-15 17:00
@tomwhite Very glad to hear that the cause of the regression is the same for both BQSR and HC! Could you test whether https://github.com/broadinstitute/gatk/pull/4314 resolves the issue as well (as opposed to an actual revert of https://github.com/broadinstitute/gatk/commit/8a366c7ba570c61338f7109b86c3284b80d5cf47)

**Comment by fnothaft** [comment] 2018-02-15 21:47
@tomwhite OOC, do you have any comment as to why bumping the ADAM version caused a performance regression? I'm not aware of any changes we've made in ADAM that would have impacted either BQSR or HC.

**Comment by fnothaft** [comment] 2018-02-15 22:10
IIRC, the main commit in ADAM that would effect BQSR or HC was https://github.com/bigdatagenomics/adam/commit/1eed8e8e464f8f92a6e87afc1d334e751423e810#diff-abb5cd690409453a589fa8aadbfd7151 which _improved_ the performance of extracting regions from a 2 bit file. I run GATK4 HC pretty regularly with this change and haven't seen performance issues on datasets ranging in size from small targeted datasets up to WGS. Anywho, let me know if there's anything I can do to help debug the perf issue.

**Comment by tomwhite** [comment] 2018-02-16 16:58
@droazen I ran #4314 and it did not solve the problem. When I reverted the ADAM patch from the #4314 branch I got the normal performance.

@fnothaft I wish I knew. @lbergelson said he saw more logs being produced. Another (untested) theory is that the Kryo registrations changed somehow. GATK only uses the 2bit code from ADAM, so it is surprising that it is having such an effect. I'm not sure how to track down the problem at this point.

**Comment by fnothaft** [comment] 2018-02-16 17:51
Hi @tomwhite! The serializer registrations in ADAM shouldn't effect any GATK serialization, unless you're serializing classes from ADAM (such as `org.bdgenomics.format.avro.AlignmentRecord`); additionally, we haven't seen any performance issues with serialization in ADAM 0.23.0 outside of the GATK. We actually made a number of patches to eliminate logging in 0.23.0 (relative to 0.22.0), so I'd doubt that is the culprit. The one exception to this is logging when writing Parquet out to disk, which greatly increased sometime between ADAM 0.21.0 and 0.23.0, due to a change in Parquet versions upstream in Spark. However, this would only impact you if you were writing Parquet, and additionally this issue was resolved with the release of Spark 2.2.0, so you should see the logging go away with #4314.

If I had to hypothesize anything, I'd suggest that the 2bit file change is the one thing that could be biting you. That said, we've been running with this 2bit file code quite frequently on AWS and Azure for at least the last 6 months using GATK HC on WES and WGS data and haven't seen any performance issues. I show that the changes in the 2bit file code between ADAM 0.20.0 and 0.23.0 are API compatible, so if you check out ADAM 0.23.0 and then `git checkout adam-parent-spark2_2.11-0.20.0 adam-core/src/main/scala/org/bdgenomics/adam/util/TwoBitFile.scala` and build the ADAM JAR (and then package that jar into GATK), you should be able to test that hypothesis.

**Comment by droazen** [comment] 2018-02-20 17:12
@tomwhite Can you check whether https://github.com/broadinstitute/gatk/pull/4314 has an effect? If not, we may need to revert the ADAM upgrade for now.

**Comment by droazen** [comment] 2018-02-20 18:19
@tomwhite Ignore my previous message, sorry -- I see that you commented above that you tested https://github.com/broadinstitute/gatk/pull/4314 and it had no effect. I've opened https://github.com/broadinstitute/gatk/pull/4428 to revert the ADAM upgrade for now until we understand the underlying cause of the performance regression.

@fnothaft It seems to me that the serializer registrations in ADAM could in theory affect the GATK, since we both register serializers for core classes in htsjdk. It seems worth investigating as a possibility, at least, as it's the only candidate mentioned so far that seems to have the potential to cause such as massive performance difference.

**Comment by fnothaft** [comment] 2018-02-20 20:44
Hi @droazen! Again, I'm skeptical that it would be a serialization change as we have only made one change to serializer registration for htsjdk classes since 0.20.0:

```
$ git diff adam-parent_2.10-0.20.0 adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala  | grep htsjdk
     kryo.register(classOf[scala.Array[htsjdk.variant.vcf.VCFHeader]])
```

Additionally, the [Kryo version used in ADAM has been unchanged since 0.20.0](https://github.com/bigdatagenomics/adam/commit/295fb5cf7bf1f089e82a1624e2056053e817b5f3). Since we do not shuffle `SAMRecord`s, we do not register a serializer for `SAMRecord`, which would presumably be the main record that HaplotypeCaller is serializing.

The GATK's implementation of BQSR doesn't perform any shuffles other than when reducing the recalibration tables, correct? If so, any performance regression in GATK's BQSR would be exceedingly unlikely to be caused by serializer registrations in ADAM.

**Comment by fnothaft** [comment] 2018-02-20 21:17
I would like to reiterate that the one code path in ADAM that is

1. changed between 0.20.0 and 0.23.0 and
2. that is used in both the GATK BQSR and HC engines

is the two bit file parsing and extraction engine. The main commit that changed in that code path was https://github.com/bigdatagenomics/adam/commit/1eed8e8e464f8f92a6e87afc1d334e751423e810, which reverts cleanly on ADAM trunk. There are also some changes in the `ReferenceRegion` class, they appear to be mostly cosmetic, but this necessitated changing one parameter from `null` to `Strand.INDEPENDENT` in https://github.com/broadinstitute/gatk/commit/8a366c7ba570c61338f7109b86c3284b80d5cf47. The GATK does one lookup into the TwoBitFile (which creates one ReferenceRegion along the way) per read during BQSR and two per assembly region during HC, so this code is inside your inner loop.

Again, all it should take to test this hypothesis is:

```
git clone git@github.com:bigdatagenomics/adam.git
cd adam
git checkout adam-parent-spark2_2.10-0.23.0
git revert 1eed8e8e464f8f92a6e87afc1d334e751423e810
mvn install -DskipTests
```

You'd then need to build the GATK with the JAR this generates. If this makes the perf regression go away, then we can easily revert this change in ADAM 0.24.0, which will release two weeks from now.

Let me know if there's any way I can be of help.

**Comment by fnothaft** [comment] 2018-02-20 22:55
I'd also note that in the example command that @tomwhite is running uses just 4GB of memory on the driver while using a broadcast join strategy, which I believe is the default strategy used by BQSR. The [GZIP'ed dbSnp build 138 VCF in the hg18 GATK bundle](ftp://ftp.broadinstitute.org/bundle/hg18/) is ~1.4GB, and the hg18 2bit file is probably going to be ballpark 1GB of data. That's a lot of data to collect onto a driver with just 4GB of memory, so I wouldn't be surprised if the driver is OOMing.

@lbergelson you'd mentioned [above](https://github.com/broadinstitute/gatk/issues/4376#issuecomment-364187885) that you haven't seen said performance regression and that it isn't showing up in the regression tests kicked off by CI. Can you confirm what driver memory settings you are using?

**Comment by heuermh** [comment] 2018-02-20 23:36
I've been looking at 2bit performance today, comparing ADAM release version 0.20.0 to release version 0.23.0 and to git HEAD (0.24.0-SNAPSHOT), in various use cases, and do not see any performance differences.

@tomwhite `loadReferenceFile` in ADAM only supports local 2bit files, what happens in between the file in `gs://` cloud storage to when you load it via ADAM APIs?

**Comment by tomwhite** [comment] 2018-02-26 16:38
@fnothaft I tried reverting 1eed8e8 and the performance was back to normal! So it would be worth reverting in ADAM for the next release if possible.

**Closed** 2018-02-26 19:29 UTC
Labels: PRIORITY_HIGH, Spark
