### ISSUE TITLE
 GATKOrder vs ReadCoordinateComparator

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1250] opened 2015-12-04 16:11 UTC
what's the relation of GATKOrder to ReadCoordinateComparator? We should not have 2 comparators like this or at least rename GATKOrder to something more MarkDuplicate-specific

**Comment by droazen** [comment] 2016-01-05 22:49
Closing as dupe of https://github.com/broadinstitute/gatk/issues/620

**Closed by droazen** 2016-01-05 22:49 UTC
Labels: coding
