### ISSUE TITLE
default read filters are excluded from the help output for --disableReadFilters

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2398] opened 2017-02-07 23:21 UTC
Tool default ReadFilters are not included in the help output as possible values for either `--readFilter` or `--disableReadFilter`.

It makes some sense to not include default read filters in the list of read filters to enable, but we definitely need them in the list to disable.

**Comment by magicDGS** [comment] 2017-02-08 06:15
I think that https://github.com/broadinstitute/gatk/pull/2360 fix it.

**Comment by magicDGS** [comment] 2017-02-08 16:42
This is kind of a duplicate of #2358

**Comment by cmnbroad** [comment] 2017-03-13 15:50
Closed via #2401.

**Closed by cmnbroad** 2017-03-13 15:50 UTC
