### ISSUE TITLE
Automate performance testing (including Spark)

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1609] opened 2016-03-22 17:11 UTC
the goal is to have automated performance tests for representative commandlines and datasizes - details of when to run them etc remain to be decided

**Comment by akiezun** [comment] 2016-06-01 18:26
@lbergelson let's chat with @davidbernick and figure out how to set this up (we need spark ones too)

**Comment by akiezun** [comment] 2016-06-09 18:32
i will send the right commandlines and accepted times to @davidbernick

**Comment by akiezun** [comment] 2016-06-17 15:52
Let's start with those 4. You need to fetch and build GATK by clone and `./gradlew clean installAll` and get the data from the location I indicated here. For accepted times, let's first run it a few times and we'll see.

Assigning to @davidbernick 

Non-spark Commandline for BaseRecalibrator (you may want to copy the input files onto a local drive)

```
bamIn=/dsde/working/akiezun/data/CEUTrio.HiSeq.WEx.b37.NA12892.bam
vcfIn=/dsde/working/akiezun/data/dbsnp_138.b37.excluding_sites_after_129.vcf
refIn=/dsde/working/akiezun/data/human_g1k_v37.fasta
./gatk-launch BaseRecalibrator -I $bamIn  -O output.table --useOriginalQualities --knownSites $vcfIn -R $refIn
```

Non-spark Commandline for ApplyBQSR  (you may want to copy the input files onto a local drive)
```
bamIn=/dsde/working/akiezun/data/CEUTrio.HiSeq.WEx.b37.NA12892.bam
refIn=/dsde/working/akiezun/data/human_g1k_v37.fasta
recaFile=/dsde/working/akiezun/data/CEUTrio.HiSeq.WEx.b37.NA12892.noIndelsGATK4.recal
./gatk-launch ApplyBQSR -R $refIn -I $bamIn --useOriginalQualities -O out.bam -bqsr $recalFile --emit_original_quals
```

Spark Commandline for MarkDuplicatesSpark 
```
bamIn=/user/akiezun/CEUTrio.HiSeq.WEx.b37.NA12892.readnamesort.bam 
#Note: bamIn is the same as gs://hellbender/test/resources/benchmark/CEUTrio.HiSeq.WEx.b37.NA12892.readnamesort.bam copied to HDFS
./gatk-launch MarkDuplicatesSpark \
	      --shardedOutput true \
	      -O /user/akiezun/tmp.md.bam \
	      --numReducers 0 \
	      --apiKey <THE_API_KEY> \
	      -I $bamIn \
	      -- \
	      --sparkRunner GCS \
	      --driver-memory 8G \
	      --cluster <THE_CLUSTER_ON_GSC> \
	      --executor-cores 3 \
	      --executor-memory 25G \
	      --conf spark.yarn.executor.memoryOverhead=2500
```

Spark Commandline for ReadsPipelineSpark  (input files CEUTrio.HiSeq.WEx.b37.NA12892.readnamesort.bam, human_g1k_v37.2bit and dbsnp_138.b37.excluding_sites_after_129.vcf are copied from gs://hellbender/test/resources/benchmark/ down to hdfs on a dataproc cluster)

```
./gatk-launch ReadsPipelineSpark \
-I hdfs:///user/akiezun/CEUTrio.HiSeq.WEx.b37.NA12892.readnamesort.bam \
-R hdfs:///user/akiezun/human_g1k_v37.2bit \
-O hdfs:///user/akiezun/CEUTrio.HiSeq.WEx.b37.NA12892.readnamesort.bam.md.bqsr \
--knownSites hdfs:////user/akiezun/dbsnp_138.b37.excluding_sites_after_129.vcf \
--shardedOutput true \
--apiKey <THE_API_KEY> \
--emit_original_quals \
--duplicates_scoring_strategy SUM_OF_BASE_QUALITIES \
--numReducers 0 \
-- \
--sparkRunner GCS \
--cluster <THE_CLUSTER_ON_GSC> \
--driver-memory 8G \
--conf "spark.yarn.executor.memoryOverhead=2000" \
--executor-memory 18g \
--executor-cores 6 \
--conf spark.yarn.executor.memoryOverhead=2000
```

**Comment by davidbernick** [comment] 2016-06-20 16:43
Any # of CPUs to use?

**Comment by akiezun** [comment] 2016-06-20 17:58
you mean, for spark? Up to you - we'll only be comparing results between runs on your setup anyway. For my experiments I used 10 nodes of 16 CPUs each and stuff runs in <10-15 minutes then. If you go for fewer cores, it'll simply take longer - not a big deal here because the requirement is that those run overnight

**Comment by davidbernick** [comment] 2016-06-20 18:07
Actually i mean for the Non-Spark machines -- how many CPUs should be available for the job?

**Comment by davidbernick** [comment] 2016-06-20 18:25
@akiezun this will sound dumb because you'd assume i have access to the internal infrastructure but i've been All Cloud since I got here. Are these files at these locations on the Isilon or do they reside elsewhere?

```bamIn=/dsde/working/akiezun/data/CEUTrio.HiSeq.WEx.b37.NA12892.bam
vcfIn=/dsde/working/akiezun/data/dbsnp_138.b37.excluding_sites_after_129.vcf
refIn=/dsde/working/akiezun/data/human_g1k_v37.fasta
```

**Comment by akiezun** [comment] 2016-06-20 20:52
/dsde/working/akiezun/data/ is on the broad nfs

**Comment by akiezun** [comment] 2016-06-20 20:53
about non-spark number of machines and their kinds - please consult with Jose to use the same exact kinds as production uses.

**Comment by davidbernick** [comment] 2016-06-21 19:59
@akiezun which java version?

**Comment by akiezun** [comment] 2016-06-21 20:02
oracle java8

**Comment by davidbernick** [comment] 2016-06-22 03:51
@akiezun to run this command, what files do I actually need localized?
```
JAVA_OPTS="-Xmx4000m -Xms4000m" ./gatk-launch BaseRecalibrator -I $bamIn  -O output.table --useOriginalQualities --knownSites $vcfIn -R $refIn
```

For instance, I don't need just these files:
```
bamIn=/dsde/working/akiezun/data/CEUTrio.HiSeq.WEx.b37.NA12892.bam
vcfIn=/dsde/working/akiezun/data/dbsnp_138.b37.excluding_sites_after_129.vcf
refIn=/dsde/working/akiezun/data/human_g1k_v37.fasta
```

I need the matching fai file, too. What else?

**Comment by akiezun** [comment] 2016-06-22 03:55
probably nothing else but just in case, copy
/dsde/working/akiezun/data/CEUTrio.HiSeq.WEx.b37.NA12892.ba*

/dsde/working/akiezun/data/dbsnp_138.b37.excluding_sites_after_129.vc*

Adam

**Comment by droazen** [comment] 2016-06-22 12:09
@davidbernick You need the companion indices for each of those inputs (the `bai`, `idx`, and `fai` files for  the bam, vcf, and fasta respectively), as well as the `dict` file for the fasta.

**Comment by davidbernick** [comment] 2016-06-22 15:13
Running the ApplyBQSR command from above. I get this error:
```
A USER ERROR has occurred: Couldn't read file. Error was: --emit_original_quals with exception: --emit_original_quals
```
This is the commandline:
```
./gatk-launch ApplyBQSR -R human_g1k_v37.fasta -I CEUTrio.HiSeq.WEx.b37.NA12892.bam --useOriginalQualities -O out.bam -bqsr --emit_original_quals
```

**Comment by droazen** [comment] 2016-06-22 15:19
@davidbernick You are missing the file argument for the `-bqsr` option.

**Comment by davidbernick** [comment] 2016-06-22 15:22
No, i have it -- 
```
./gatk-launch ApplyBQSR -R human_g1k_v37.fasta -I CEUTrio.HiSeq.WEx.b37.NA12892.bam --useOriginalQualities -O out.bam -bqsr --emit_original_quals
``` 
after the out.bam...

**Comment by droazen** [comment] 2016-06-22 15:23
@davidbernick I mean that the `-bqsr` argument takes a file. Eg., `-bqsr recal_file`

**Comment by davidbernick** [comment] 2016-06-22 15:36
that worked, thanks. I had a typo in the variable "recaFile" vs "recalFile".  

how does this group want to proceed with alerting on failures? email? hipchat? slack? carrier pigeon? and who should be on the list?

**Comment by droazen** [comment] 2016-06-22 15:43
@davidbernick My vote would be for a github badge showing current status on master + email alerts on failure. Core dev team of myself, @lbergelson, and @akiezun should be fine for now as long as we can easily add additional recipients.

**Comment by davidbernick** [comment] 2016-06-22 17:46
https://gatk-jenkins.broadinstitute.org/view/Performance/ -- running non-spark tests over and over while I build the spark tests. I'll run about 5 times (take about 2 hours each in parallel) so we can get an average. I've constrained each test to 1 CPU at a time.

**Comment by akiezun** [comment] 2016-06-23 01:58
@davidbernick this is great. Can you describe somewhere how to add new commandlines to this? Eventally, we'll want to have at least 10 commandlines that we run regularly. Eventually, I'd like to post the link to the perf stats on the README (+a badge and email alerts to devs when things fail)

**Comment by davidbernick** [comment] 2016-06-23 15:07
What mechanism is being used to put files into HDFS in dataproc?

**Comment by davidbernick** [comment] 2016-06-23 15:33
Or, importantly, can the `./gatk-launch ReadsPipelineSpark` take gs:// paths instead of hdfs paths?

**Comment by droazen** [comment] 2016-06-23 15:36
We don't currently have an easy way to put files into HDFS on dataproc -- `gs://` should work provided you specify an `--apiKey` in your `gatk-launch` command.

**Comment by akiezun** [comment] 2016-06-23 17:13
I just used gustil and then hdfs dfs

Running from Gs buckets is super slow so let's use hdfs for this test. We
use hdfs for development

On Thursday, June 23, 2016, droazen <notifications@github.com> wrote:

> We don't currently have an easy way to put files into HDFS on dataproc --
> gs:// should work provided you specify an --apiKey in your gatk-launch
> command.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/broadinstitute/gatk/issues/1609#issuecomment-228090381>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB5rL3_hROXOmUmZW9W0d-CjIMYzfy7_ks5qOqgbgaJpZM4H2UOY>
> .
>


-- 
Sent from Gmail Mobile

**Comment by droazen** [comment] 2016-06-23 17:19
@akiezun But do you know of an *automated* way of putting the files into hdfs on dataproc?

**Comment by akiezun** [comment] 2016-06-23 17:37
Can't you just script gsutil followed by hdfs dfs?

On Thursday, June 23, 2016, droazen <notifications@github.com> wrote:

> @akiezun <https://github.com/akiezun> But do you know of an *automated*
> way of putting the files into hdfs on dataproc?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/broadinstitute/gatk/issues/1609#issuecomment-228119711>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB5rL3MbAZroT8ldWlSoKuUzb2c4ArOvks5qOsAUgaJpZM4H2UOY>
> .
>


-- 
Sent from Gmail Mobile

**Comment by droazen** [comment] 2016-06-23 18:20
@akiezun Isn't the problem though that you'd have to actually log in to the dataproc instances to do this? How would you auto-discover the machines to log in to?

**Comment by davidbernick** [comment] 2016-06-23 18:20
Exactly -- i can figure it out but i have to write some stuff around it. Just didn't know if something already existed.

**Comment by davidbernick** [comment] 2016-06-24 17:52
@droazen where are you getting your APIKey from?

**Comment by davidbernick** [comment] 2016-06-24 18:36
Ok -- caveat for all -- objects in bucket that are accessed via simple API Key need to have: User:allUsers:reader ACL permissions. if you need more complex access control, we'll have to support the "secretFile" attribute in `gcloud dataproc` -- not just the apiKey.

**Comment by davidbernick** [comment] 2016-06-24 19:37
All 4 of the above tests are running consistently in Jenkins. Will keep an eye on them for avg time.

**Comment by akiezun** [comment] 2016-06-24 19:44
can you add all 4 to
https://gatk-jenkins.broadinstitute.org/view/Performance/ (i only see 2).

also, can you write up instructions on how to add more? (we need to be able
to add more without bothering devops)

**Comment by davidbernick** [comment] 2016-06-25 01:46
Added. 

I'll write instructions on how to add more next week. Essentially you just make a "new item" in Jenkins and make it a "copy" instead of a blank project. You'd base it on either the "-spark-" jobs or the other kind of jobs and just alter the commandline. 

It's at a point now, though, where if I have to, I can reproduce them in a few minutes so it's not a bother in the long term to have me do it. But I *WILL* be writing up some docs on how this all works.

As it is now, every push to master kicks off the setup, as encapsulated in "gatk-perf-test". That sets up the master node and grabs necessary files and builds the code. If that's successful, it launches the downstream tests. Whether these succeed or fail, it tears it all down when it's done so we don't burn money.

As it stands today, the average times are:
applybqsr	 - 1hr 30 min (1 cpu)
baserecalibrator - 2 hr 45 min (1 cpu)
spark-markeddupe - 10 min (10 nodes, 16 cpu each)
spark-readpipeline - 30 min (5 nodes, 16 cpu each)

**Comment by davidbernick** [comment] 2016-06-27 18:01
Also, it's set up that if any job takes 5% longer than the above times, it will "fail" the job and send email.

**Comment by akiezun** [comment] 2016-06-29 17:51
thanks @davidbernick - i do see them fail sometimes on the email send step, which is sad

**Comment by davidbernick** [comment] 2016-06-29 17:56
Actually -- I'm just waiting for BITS to give me credentials so i can do it

**Comment by davidbernick** [comment] 2016-06-29 18:52
@akiezun (that's why i haven't closed it -- waiting on my email credentials so i can fiinish that up)

**Comment by davidbernick** [comment] 2016-06-30 17:08
Now email alerting will work. 

@akiezun I'm all done with this if you are. I'm not sure what your organization does for "closing" so it's up to you. Flag me down in real life for a 30 minute overview on how to replicate this stuff for future tests.

**Comment by akiezun** [comment] 2016-06-30 20:22
I added a paragraph to the README. Please review and then i'll close this ticket

**Closed** 2016-07-01 01:59 UTC
Labels: DevOps, performance, PRIORITY_HIGH, tests
