### ISSUE TITLE
Picard version doesn't print correctly when running a Picard tool from GATK

### ISSUE THREAD

**Issue by romagnolid** [broadinstitute/gatk#4733] opened 2018-05-03 09:37 UTC
I was wondering what version of Picard is bundled with GATK. I assume it's the latest available (2.18.4 at this time) but apparently there's no way to tell:
`$ gatk MergeSamFiles -version` output `Version:4.0.4.0`

**Comment by magicDGS** [comment] 2018-05-03 10:06
When you run a tool, a message with the bundled versions should show in the log.

**Comment by droazen** [comment] 2018-05-03 19:55
You can also find the Picard version for a given version of GATK by inspecting `build.gradle`, if you have the source checked out. But the easiest way is just to run any GATK tool, and check for "Picard version" in the log output.

Closing as resolved

**Comment by romagnolid** [comment] 2018-05-07 07:01
Sorry but it doesn't seem to be resolved.
```
$ gatk ViewSam -I /data/MCF7_PDS/MCF7_PDS.bam --ALIGNMENT_STATUS=Aligned --PF_STATUS PF --HEADER_ONLY true 
Using GATK jar /resources/tools/gatk-4.0.4.0/gatk-package-4.0.4.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /resources/
tools/gatk-4.0.4.0/gatk-package-4.0.4.0-local.jar ViewSam -I /data/MCF7_PDS.bam --ALIGNMENT_STATUS=Aligned --PF_STATUS PF --HEADER_ONLY
 true
08:51:42.543 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/resources/tools/gatk-4.0.4.0/gatk-package-4.0.4.0-local.jar!/com/intel/gkl/native/libgkl_compr
ession.so
[Mon May 07 08:51:42 CEST 2018] ViewSam  --INPUT /data/MCF7_PDS.bam --ALIGNMENT_STATUS Aligned --PF_STATUS PF --HEADER_ONLY true  --REC
ORDS_ONLY false --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH
_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Mon May 07 08:51:42 CEST 2018] Executing as [...] on Linux 4.4.0-87-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12; Deflater
: Intel; Inflater: Intel; Provider GCS is available; **Picard version: Version:4.0.4.0**
```
And if I use `--version true`:
```
$ gatk ViewSam -I /data/MCF7_PDS.bam --ALIGNMENT_STATUS=Aligned --PF_STATUS PF --HEADER_ONLY true --version true
Using GATK jar /resources/tools/gatk-4.0.4.0/gatk-package-4.0.4.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /resources/tools/gatk-4.0.4.0/gatk-package-4.0.4.0-local.jar ViewSam -I /data/MCF7_PDS.bam --ALIGNMENT_STATUS=Aligned --PF_STATUS PF --HEADER_ONLY true --version true
Version:4.0.4.0
Tool returned:
1
```

**Comment by droazen** [comment] 2018-05-07 14:33
@romagnolid Yes, you're right -- the Picard version isn't printing correctly when running a Picard tool. If you run a GATK tool, such as `PrintReads`, it should print both the GATK and Picard versions correctly.

Re-opening, as we should really fix this.

**Comment by droazen** [comment] 2018-05-07 14:33
@cmnbroad Could you have a look at this one? Should be a quick fix.

**Comment by romagnolid** [comment] 2018-05-07 14:43
@cmnbroad ok, I see the difference, coincidentally I used only Picard tools as a test.
Running PrintReads as you suggested definitely displays the right version
`Picard Version: 2.18.2`
Thank you

**Comment by lbergelson** [comment] 2018-05-07 15:54
It's because of the way we package things, you only get a single version in the manifest.  There's a better way to add package level versions to the manifest that would be maintained when repacking the jars, but it doesn't work with picard because it assumes a package name convention which picard doesn't follow.  We could define version strings somewhere in the jar and look them up manually though.

**Comment by magicDGS** [comment] 2018-05-08 09:55
The problem is in https://github.com/broadinstitute/picard/blob/aa911f9440e70f59a32dddadd90e5a07c7764d87/src/main/java/picard/cmdline/CommandLineProgram.java#L267-L274, which is using barclays `CommandLineParser.getVersion`, which implementation uses the `this.callerOptions.getClass().getPackage().getImplementationVersion()` (see https://github.com/broadinstitute/barclay/blob/master/src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java#L268)

I think that in general is a good idea to include the versions in the `MANIFEST`, but it should be somehow extensible for downstream projects - and I guess that it should be done at the barclay level to do not populate directly the `Version` attribute but the `ToolkitName-Version` attribute...

**Comment by azzaea** [comment] 2019-03-01 07:34
To add to this, with GATK4.1.0.0 no Picard version shows up regardless of whether it is a GATK or Picard tool I'm invoking now. Below is a snippet:
For a Picard tool:
``` 
$ gatk MarkDuplicates -version
Using GATK jar /usr/src/gatk/gatk-4.1.0.0/gatk-package-4.1.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /usr/src/gatk/gatk-4.1.0.0/gatk-package-4.1.0.0-local.jar MarkDuplicates -version
Version:4.1.0.0
Tool returned:
1
```
And for a GATK tool:
```
$ gatk HaplotypeCaller --version
Using GATK jar /usr/src/gatk/gatk-4.1.0.0/gatk-package-4.1.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /usr/src/gatk/gatk-4.1.0.0/gatk-package-4.1.0.0-local.jar HaplotypeCaller --version
Version:4.1.0.0
Tool returned:
0
```

**Comment by droazen** [comment] 2019-03-05 18:36
@azzaea If you run just `gatk --version`, it will print both the GATK and the Picard versions:

```
$ ./gatk --version
The Genome Analysis Toolkit (GATK) v4.1.0.0-44-g0f0c22b-SNAPSHOT
HTSJDK Version: 2.18.2
Picard Version: 2.18.25
```

We should make the output of `gatk ToolName --version` consistent with the output of `gatk --version`.

**Comment by droazen** [comment] 2019-03-05 19:00
Fixed in https://github.com/broadinstitute/gatk/pull/5757

**Closed** 2019-03-05 20:12 UTC
Labels: Engine, Maintenance, bug

**Comment by azzaea** [comment] 2019-03-06 10:19
Thanks @droazen . That works
