### ISSUE TITLE
HaplotypeCaller outputting variants with an ALT of .

### ISSUE THREAD

**Issue by roryk** [broadinstitute/gatk#5650] opened 2019-02-06 20:05 UTC
### Affected tool(s) or class(es)
GATK Haplotype caller

### Affected version(s)
- [x] Latest public release version [4.1.0.0]
- [ ] Latest master branch as of [date of test?]

The Genome Analysis Toolkit (GATK) v4.1.0.0
HTSJDK Version: 2.18.2
Picard Version: 2.18.25

### Description 
HaplotypeCaller is outputting variants which have a no-call as the ALT, which breaks a bunch of downstream tools, this is new behavior in 4.1, AFAICT.

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	s1564	s1741	s1851	s1852	s1862	s1901	s1912	s1971	s2017	s2021	s2026	s2056	s2100	s2102	s2104	s2122	s2124	s2151	s2157
1	937796	.	T	.	179.65	.	AN=38;DP=31;MMQ=60;MQ=60.00	GT:AD:DP	0/0:0:0	0/0:0:0	0/0:4:4	0/0:0:0	0/0:1:1	0/0:1:1	0/0:0:0	0/0:0:0	0/0:2:2	0/0:0:0	0/0:1:1	0/0:3:3	0/0:1:1	0/0:8:8	0/0:1:1	0/0:0:0	0/0:2:2	0/0:7:7	0/0:0:0
```

#### Steps to reproduce
I'm not doing anything special, so I suspect these variants should exist in other projects as well. I'm doing batch calling on several samples simultaneously; an example:

```
unset JAVA_HOME && export PATH=/home/rdk4/local/share/bcbio/anaconda/bin:$PATH && gatk --java-options '-Xms4g -Xmx5000m -XX:+UseSerialGC -Djava.io.tmpdir=/n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/bcbiotx/tmpTSg0hJ' HaplotypeCaller -R /n/app/bcbio/dev/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2017/s2017-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2056/s2056-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2122/s2122-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1741/s1741-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2124/s2124-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1862/s1862-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1971/s1971-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1851/s1851-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1564/s1564-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2104/s2104-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1852/s1852-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1912/s1912-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2100/s2100-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2157/s2157-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2151/s2151-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1901/s1901-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2026/s2026-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2102/s2102-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2021/s2021-sort.bam -L /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/gatk-haplotype/Y/tau-Y_0_58820452-regions.bed --interval-set-rule INTERSECTION --disable-read-filter NotDuplicateReadFilter --annotation ClippingRankSumTest --annotation DepthPerSampleHC --native-pair-hmm-threads 1 -ploidy 1 --output /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/bcbiotx/tmpTSg0hJ/tau-Y_0_58820452.vcf.gz
```

#### Expected behavior
These no-call of an ALT allele variants to be dropped.

#### Actual behavior
They are still included.

If this is expected behavior going forward, though, that would be good to know and we can remove these after calling. Thanks!

**Comment by ldgauthier** [comment] 2019-02-07 13:21
Hi @roryk,
This is probably an oversight since so much of our development is focused on gvcfs. I agree that the expected behavior should be no output for AC=0. I can probably put together a fix tomorrow. Unfortunately our nightly docker builds have been unreliable - would you be able to build your own jar off the master branch once the fix is in?

**Comment by roryk** [comment] 2019-02-07 14:23
Hi @ldgauthier,

Awesome! Yup, can do.

**Comment by ldgauthier** [comment] 2019-02-08 14:19
Now that I'm looking at this more carefully, I see a `-ploidy 1` in your command, but you're getting diploid genotypes.  I'm going to operate on the assumption that that's part of the bug unless you tell me otherwise.

**Comment by ldgauthier** [comment] 2019-02-08 15:35
I suspect this is because we switched to the new QUAL as default in 4.1 . For the time being, you can probably use the `--use-old-qual-calculator` to get around the issue.  Can you share some of the reads to reproduce the issue?  I'm concerned this is a numerical precision issue in the new model and I hesitate to put a bandaid on it by just dropping these sites.

**Comment by roryk** [comment] 2019-02-08 15:37
Great-- can do, it will take a little bit for me to put together a small test case. While I'm doing that I'll see if passing that flag will fix it. Thanks so much.

**Comment by sooheelee** [comment] 2019-02-08 17:12
I think this might be a related bug. I see two values for AD when genotyping with GenotypeGVCFs in `--include-non-variant-sites` mode for a homozygous-reference site. The command I use and an example output VCF record are at https://gatkforums.broadinstitute.org/gatk/discussion/23371/calling-variants-at-known-sites-with-haplotypecaller.

**Comment by roryk** [comment] 2019-02-10 16:21
Hi everyone,

I put together as small a test case as I could here: https://www.dropbox.com/s/p7x3jt6lgxesc23/gatk-missingalt-testdata.tar.gz?dl=1

Some observations that might help track down the source of the bug:

1. Subsetting the BAM file to within 100 bases of the call with the missing alt results in files that cannot reproduce this behavior, it needs to be a larger window.
2. If you call individually instead of in batch mode none of the individual calls have the missing variant on this test data.

This example dataset results in one call with a missing ALT:

```
GL000216.1	67968	.	C	.	39.74	.	AN=38;DP=74;MMQ=60;MQ=59.82	GT:AD:DP	0/0:1:1	0/0:0:0	0/0:5:5	0/0:3:3	0/0:6:6	0/0:6:6	0/0:2:2	0/0:1:1	0/0:2:2	0/0:5:5	0/0:5:5	0/0:4:4	0/0:9:9	0/0:4:4	0/0:2:2	0/0:2:2	0/0:0:0	0/0:10:10	0/0:7:7
```

**Comment by droazen** [comment] 2019-02-10 18:29
@roryk Did this bug occur in the previous GATK release (4.0.12.0) as well, or is 4.1.0.0 literally the very first release with this issue?

**Comment by roryk** [comment] 2019-02-10 18:55
Hi @droazen,

Sorry, I'm not sure-- I'm about 90% certain that it is specific to 4.1.0.0 because we probably would have run into the bug if it existed prior to that, but I'm not 100% sure.

**Comment by ldgauthier** [comment] 2019-02-11 19:35
Thanks for the beautifully svelte test data @roryk !  I'll take a look this week.  Did the workaround I suggested fix your issue?

**Comment by droazen** [comment] 2019-02-11 19:44
@roryk What version were you running just before 4.1.0.0?

**Comment by roryk** [comment] 2019-02-11 20:05
Sorry @ldgauthier, I forgot to test that, I'll do it now. Props for using the word svelte. @droazen-- we have gatk4 installed and updated via bioconda, so I'm not super sure exactly which versions had this problem, just that the current version. If it would help I could roll back `gatk4` to `4.0.12.0` and see if the issue was there as well.

**Comment by ldgauthier** [comment] 2019-02-11 21:28
The workaround looked good on the sample you gave me, but I'm pretty sure I found the issue so a fix is not far off.  The * allele is causing problems again.  It happens at a multi-allelic with a low quality alt, so it's not a *-only site, but the real alt gets dropped by the QUAL filter.  I just need to put in a regression test before I submit the PR.

Also, I'm taking out the repeated instances of `DepthPerSampleHC - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null` (i.e. there will be just one in the log) because that was annoying me.

**Comment by roryk** [comment] 2019-02-11 21:30
Awesome, thanks so much. Your workaround does work on that test set. That's a bonus: that warning spam was annoying the heck out of me too.

**Comment by roryk** [comment] 2019-02-13 22:52
Thanks so much for the fix @ldgauthier, you rock.

**Comment by droazen** [comment] 2019-03-28 18:55
Reopening -- the PR that went in that purported to fix this (https://github.com/broadinstitute/gatk/pull/5661) did not actually contain the fix in the final version. Re-assigning back to @ldgauthier

**Closed** 2019-03-28 21:07 UTC
Labels: HaplotypeCaller, bug
