### ISSUE TITLE
gatk IndexFeatureFile for gencode.v37.annotation.REORDERED.gtf does not work

### ISSUE THREAD

**Issue by robby81** [broadinstitute/gatk#7134] opened 2021-03-08 18:00 UTC
## Bug Report

Dear developers,

I tried to update the GENCODE database and used the getGencode.sh scripts to get the data. However, I was not able to index the feature-file: Do you have any idea why that happens and how to get it done?

Code:
/home/robby/Tools/NGS/gatk-4.2.0.0/gatk IndexFeatureFile -I /home/robby/Tools/NGS/gatk-master4_2_src/scripts/funcotator/data_sources/gencode/hg19/gencode.v37lift37.annotation.REORDERED.gtf
Using GATK jar /home/robby/Tools/NGS/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/robby/Tools/NGS/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar IndexFeatureFile -I /home/robby/Tools/NGS/gatk-master4_2_src/scripts/funcotator/data_sources/gencode/hg19/gencode.v37lift37.annotation.REORDERED.gtf
18:53:59.113 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/robby/Tools/NGS/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Mar 08, 2021 6:53:59 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
18:53:59.283 INFO  IndexFeatureFile - ------------------------------------------------------------
18:53:59.283 INFO  IndexFeatureFile - The Genome Analysis Toolkit (GATK) v4.2.0.0
18:53:59.284 INFO  IndexFeatureFile - For support and documentation go to https://software.broadinstitute.org/gatk/
18:53:59.290 INFO  IndexFeatureFile - Initializing engine
18:53:59.290 INFO  IndexFeatureFile - Done initializing engine
18:53:59.417 WARN  GencodeGtfCodec - GENCODE GTF Header line 1 has a version number that is above maximum tested version (v 34) (given: 37): ##description: evidence-based annotation of the human genome (GRCh38), version 37 (Ensembl 103), mapped to GRCh37 with gencode-backmap   Continuing, but errors may occur.
18:53:59.419 WARN  GencodeGtfCodec - GENCODE GTF Header line 1 has a version number that is above maximum tested version (v 34) (given: 37): ##description: evidence-based annotation of the human genome (GRCh38), version 37 (Ensembl 103), mapped to GRCh37 with gencode-backmap   Continuing, but errors may occur.
18:53:59.422 INFO  FeatureManager - Using codec EnsemblGtfCodec to read file file:///home/robby/Tools/NGS/gatk-master4_2_src/scripts/funcotator/data_sources/gencode/hg19/gencode.v37lift37.annotation.REORDERED.gtf
18:53:59.433 INFO  ProgressMeter - Starting traversal
18:53:59.433 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
18:54:01.952 INFO  IndexFeatureFile - Shutting down engine
[March 8, 2021 at 6:54:01 PM CET] org.broadinstitute.hellbender.tools.IndexFeatureFile done. Elapsed time: 0.05 minutes.
Runtime.totalMemory()=473956352
java.lang.IllegalArgumentException: Unexpected value: MANE_Plus_Clinical
        at org.broadinstitute.hellbender.utils.codecs.gtf.GencodeGtfFeature$FeatureTag.getEnum(GencodeGtfFeature.java:1388)
        at org.broadinstitute.hellbender.utils.codecs.gtf.GencodeGtfFeature.<init>(GencodeGtfFeature.java:197)
        at org.broadinstitute.hellbender.utils.codecs.gtf.GencodeGtfTranscriptFeature.<init>(GencodeGtfTranscriptFeature.java:19)
        at org.broadinstitute.hellbender.utils.codecs.gtf.GencodeGtfTranscriptFeature.create(GencodeGtfTranscriptFeature.java:23)
        at org.broadinstitute.hellbender.utils.codecs.gtf.GencodeGtfFeature$FeatureType$2.create(GencodeGtfFeature.java:768)
        at org.broadinstitute.hellbender.utils.codecs.gtf.GencodeGtfFeature.create(GencodeGtfFeature.java:327)
        at org.broadinstitute.hellbender.utils.codecs.gtf.AbstractGtfCodec.decode(AbstractGtfCodec.java:138)
        at org.broadinstitute.hellbender.utils.codecs.gtf.AbstractGtfCodec.decode(AbstractGtfCodec.java:23)
        at htsjdk.tribble.AbstractFeatureCodec.decodeLoc(AbstractFeatureCodec.java:43)
        at org.broadinstitute.hellbender.utils.codecs.ProgressReportingDelegatingCodec.decodeLoc(ProgressReportingDelegatingCodec.java:46)
        at htsjdk.tribble.index.IndexFactory$FeatureIterator.readNextFeature(IndexFactory.java:689)
        at htsjdk.tribble.index.IndexFactory$FeatureIterator.next(IndexFactory.java:650)
        at htsjdk.tribble.index.IndexFactory.createIndex(IndexFactory.java:511)
        at htsjdk.tribble.index.IndexFactory.createDynamicIndex(IndexFactory.java:446)
        at org.broadinstitute.hellbender.tools.IndexFeatureFile.createAppropriateIndexInMemory(IndexFeatureFile.java:118)
        at org.broadinstitute.hellbender.tools.IndexFeatureFile.doWork(IndexFeatureFile.java:75)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by jonn-smith** [comment] 2021-03-15 16:43
Hi!  This issue is a duplicate of #7054 - under the hood a few changes need to be made to support arbitrary `FeatureTag`s. 
 As gencode is updated they seem to be adding more `FeatureTag`s, which Funcotator doesn't expect.  The fix is relatively straight-forward, but requires several other changes as well.  Unfortunately there isn't a good workaround right now.

As a side-note, the `getGencode.sh` script you referenced (and all scripts in that same folder: `scripts/funcotator/data_sources`) are not supported and are designed to be for internal use (I have a file in that folder to indicate this, but I'll admit it's not 100% clear).  That said, `getGencode.sh` should work properly - the issue is in the GATK itself (specifically in `org.broadinstitute.hellbender.utils.codecs.gtf.GencodeGtfTranscriptFeature` and associated classes).

This is on the short list of things to update next, so I'll try to get to it soon, though I'm not exactly sure when that will be.  Given two people have experienced this issue, I'll prioritize it somewhat higher.

**Comment by robby81** [comment] 2021-04-01 14:03
Dear jonn-smith,

I saw you made the pull request to solve the issue...is there a way I could test it?
Thanks, Cheers.

**Comment by jonn-smith** [comment] 2021-04-01 15:12
@robby81 - sure - you can clone the GATK git repo, checkout the branch in the PR (`jts_gencode_parser_update_7054`), build the GATK (`./gradlew clean installDist`), and then rerun the indexing tool:

`/home/robby/Tools/NGS/gatk_clone/gatk IndexFeatureFile -I /home/robby/Tools/NGS/gatk-master4_2_src/scripts/funcotator/data_sources/gencode/hg19/gencode.v37lift37.annotation.REORDERED.gtf`

**Comment by jonn-smith** [comment] 2021-04-02 00:33
@robby81 If you're willing to wait until tomorrow, I should be merging that PR into the main branch sometime then.

**Comment by robby81** [comment] 2021-04-02 09:12
will wait, thank you. Then I only have to clone the master branch,yes?

**Comment by jonn-smith** [comment] 2021-04-02 13:52
Correct.  You should see when it gets merged by this issue being closed out.

**Comment by jonn-smith** [comment] 2021-04-05 18:11
Fixed by #7166

**Closed by jonn-smith** 2021-04-05 18:11 UTC
Labels: Funcotator
