### ISSUE TITLE
Detect anomalous samples during/after coverage PoN creation

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2895] opened 2017-06-05 17:58 UTC
@mbabadi commented on [Tue Sep 20 2016](https://github.com/broadinstitute/gatk-protected/issues/710)

It happens often that the users attempt to make a coverage PoN from samples that come from different sequencing platforms, for example, let say platforms A and B. In this situation, some principal components will have strong projections onto A, and some onto B. We need to be able to identify such anomalies, either during PoN creations or in a post-processing step.

**Comment by samuelklee** [comment] 2019-01-31 15:08
Dupe of #4060.

**Closed by samuelklee** 2019-01-31 15:08 UTC
Labels: Copy Number tools, Germline CNV, Somatic CNV
