### ISSUE TITLE
ADAM ReadsSparkSinkUnitTest.loadReadsADAM test fails on NA12878.chr17_69k_70k.dictFix.bam

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1267] opened 2015-12-07 20:07 UTC
see test in ReadsSparkSinkUnitTest.loadReadsADAM

**Comment by droazen** [comment] 2015-12-07 20:08
Dupe of https://github.com/broadinstitute/gatk/issues/1254 -- closing

**Comment by akiezun** [comment] 2015-12-07 20:09
not sure if they are related.
but fine

**Closed by droazen** 2015-12-07 20:08 UTC

**Comment by droazen** [comment] 2015-12-07 20:10
@akiezun Could you add a comment to the existing ticket (https://github.com/broadinstitute/gatk/issues/1254) 
with the additional failure?
