### ISSUE TITLE
Verify CRAM support works on Hadoop-BAM

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/gatk#1160] opened 2015-11-19 19:18 UTC
@tomwhite just added support. We should try `SortBamSpark` on a large CRAM file to see if we have any reading or writing problem.

**Comment by akiezun** [comment] 2015-11-19 20:09
do we need to upgrade to the latest hadoop-bam to have this @tomwhite ?

**Comment by tomwhite** [comment] 2015-11-20 10:56
@akiezun yes, version 7.3.0.

The other thing I didn't mention is that AnySAMInputFormat will need to be changed to CRAMInputFormat for the test. (I opened https://github.com/HadoopGenomics/Hadoop-BAM/issues/35 to fix this properly.)

**Comment by tomwhite** [comment] 2015-11-20 11:03
This is a duplicate of https://github.com/broadinstitute/gatk/issues/966, so one or other should be closed.

**Comment by droazen** [comment] 2015-11-20 13:15
Closing in favor of https://github.com/broadinstitute/gatk/issues/966

**Closed by droazen** 2015-11-20 13:15 UTC
