### ISSUE TITLE
How to get OREF info in VCF INFO filed.

### ISSUE THREAD

**Issue by pigraul** [broadinstitute/gatk#6249] opened 2019-11-06 09:09 UTC
How can I get "OREF" and "OALT" info  from GATK?  Need special parameters?

My script is below:
java -Xmx6g -Djava.io.tmpdir=./ -jar GenomeAnalysisTK.jar \
-T HaplotypeCaller \
-R b37.fasta \
-I EC46IOCV.final.bam \
-nct 8 \
--genotyping_mode DISCOVERY \
-stand_call_conf 30 \
--dbsnp dbsnp_137.b37.vcf \
-o EC46IOCV.GATK.var.vcf 

I did not find it in VariantAnnotator either.

Many thanks,
Raulee

**Comment by ldgauthier** [comment] 2020-01-17 20:40
@pigraul What are OREF and OALT?

**Comment by davidbenjamin** [comment] 2020-02-09 03:54
This is a dupe of a Biostars question: https://www.biostars.org/p/406695/ where the same user hasn't responded in 3 months.  The answer there suggested it was some sort of IonTorrent tag.

**Closed by davidbenjamin** 2020-02-09 03:54 UTC
Labels: WaitingForUser
