### ISSUE TITLE
Only the first letter of unknown arguments is shown in the error.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#1751] opened 2016-04-21 15:41 UTC
When the user includes an unknown argument in a tool command line the error message only indicates the first letter of the unknown argument as supposed to the full name. 

At the very least the message should read  "unknown argument STARTING with 'x'". However I would say that is far better if the whole argument name is output.

**Comment by vruano** [comment] 2016-04-21 15:42
To be more exact here is an actual error message:
```
Invalid command line: z is not a recognized option
```

Ideally would be

```
Invalid command line: 'zscores' is not a recognized option
```

**Comment by lbergelson** [comment] 2016-04-21 15:48
I assume it was specified with a single `-`?  It interprets short options as single letters if it can't identify them, since it allows chaining of single letter short options i.e. `-tvf`.

**Comment by vruano** [comment] 2016-04-23 03:14
I could see why it happens, however I think we can do better.

**Comment by droazen** [comment] 2017-03-22 19:14
@cmnbroad Is this still an issue with barclay? Assigning to you to find out.

**Comment by cmnbroad** [comment] 2017-03-23 13:28
Yes, I think @lbergelson is right about the cause he mentioned above - the jopt parser allows short name clusters, so it chooses the parsimonious interpretation in the error case. Its might be worth a look to see if we can do something smarter without too much effort.

**Comment by droazen** [comment] 2017-10-17 19:54
Closing -- I tested just now, and this is fixed.

**Closed by droazen** 2017-10-17 19:54 UTC
Labels: CLI, enhancement
