### ISSUE TITLE
implement per-target coverage collection in spark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1038] opened 2015-10-22 16:15 UTC
It should be able to optionally split by read group or library or sample

**Comment by davidbenjamin** [comment] 2017-05-03 19:45
@samuelklee is this issue still relevant?

**Comment by samuelklee** [comment] 2017-05-03 20:08
@asmirnov239 will start working on unifying WES/WGS coverage collection in a Spark tool in the next couple of weeks.

**Comment by samuelklee** [comment] 2017-10-11 14:55
Dupe of #3660.

**Closed by samuelklee** 2017-10-11 14:55 UTC
Labels: Copy Number tools, Spark
