### ISSUE TITLE
Migrate tools to GATKTool/walker/GATKSparkTool interfaces where possible

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2471] opened 2017-03-20 14:57 UTC

**Comment by davidbenjamin** [comment] 2018-01-14 02:49
@droazen Can we close this?  AFAIK M2 and CNV were the only protected tools, since SVs were always in public.  Everything in the M2 pipeline is a walker, and @samuelklee has cleaned house with CNVs

**Comment by samuelklee** [comment] 2018-01-14 19:12
Almost all of the CNV tools extend `CommandLineProgram` unless they are walkers or otherwise need to use `-L`.

**Comment by droazen** [comment] 2018-01-16 16:45
I'd like to get to the point where most/all GATK tools extend `GATKTool` rather than `CommandLineProgram` directly, so I think we have to keep this one open.

**Comment by davidbenjamin** [comment] 2018-01-16 17:09
Okay, fair enough!

**Comment by samuelklee** [comment] 2018-01-16 17:26
What the rules for when a tool is allowed to be a `CommandLineProgram`?  Most of the CNV tools extend `CommandLineProgram` rather than `GATKTool` for various reasons, including: 1) they use sequence-dictionary input in a way that requires custom argument documentation, 2) they use `-I` to specify non-BAM/SAM/CRAM input, and 3) they don't really make use of the argument collections available in `GATKTool` or otherwise fall under the walker paradigm.  These reasons are admittedly minor, but they do make the tools a bit nicer to use in the end.

Otherwise, whenever it makes sense for a tool to extend `GATKTool`, it does (4 out of 12 of the CNV tools).  (A bit of a tangent: in a couple of cases where we do extend `GATKTool` to e.g. make use of the `-L` functionality, we still have to jump through some extra hoops to make sure we don't get tripped up.  For example, the default `--interval-merging-rule` behavior is incorrect for most CNV analyses, so the user has to set this to `OVERLAPPING_ONLY` manually, otherwise we throw an exception---which is quite awkward.  Ideally, we'd have some option to not modify the incoming intervals at all, as well.)

So I'm comfortable with closing this issue, but we can discuss the pros and cons of moving more of the tools over if necessary.

**Comment by droazen** [comment] 2018-01-16 17:33
@samuelklee If there are CNV tools that can't comfortably extend `GATKTool` as things stand now, then I think that we should adjust `GATKTool` to be more flexible until they can do so. This would help with certain long-term goals that the engine team has (such as all tools supporting NIO for all inputs, consistent sequence dictionary validation, etc.)

**Comment by samuelklee** [comment] 2018-01-16 17:43
Those are reasonable goals.  Let's discuss more---perhaps if any other teams have "feature requests" for `GATKTool`, they can also chime in on this issue.

**Comment by droazen** [comment] 2018-01-16 17:45
Great -- and as part of this effort, we can fix any pain points you guys have like the `--interval-merging-rule` issue you mentioned above.

**Comment by magicDGS** [comment] 2018-01-17 09:58
@droazen - a proposal for that, which will be great for my toolkit too, is to make `GATKTool` params an argument collection which defaults to the ones in the tool now, but can be change in a tool-basis.

For example, if I have a `VariantWalker` which does not use any read-source, disabling all params for reads will be nice for re-use the `VariantWalker` interface without allowing the user to pass something that it is not used at all. It is not enough to provide a way to require or not a source, but to completely remove from the command line the ability to get that argument.

I guess that's what it is required also for the CNV tools (correct me if I am wrong, @samuelkle), to be able to change that behaviour and to being able to provide custom documentation/arguments (re-factor the reads input `-I` to be other kind of input). I did something similar for the `ReadFilter` plugin to change the documentation and hide some arguments in my tools using it.

Let me know if I can help with something in this direction, because it will be useful for me too...

**Comment by droazen** [comment] 2018-01-17 14:33
@magicDGS Yes, I agree that there is a need for clients of `GATKTool` to be able to selectively disable arguments/inputs -- that is definitely an ability we'll add as part of this ticket.

**Comment by samuelklee** [comment] 2018-01-17 14:50
Another issue that I remember running into is that some of the fields are package-private.  I think this is by design, but it does add some additional restrictions.

**Comment by droazen** [comment] 2018-01-17 15:07
If the encapsulation of the datasources is causing issues for tools that extend `GATKTool` directly, we can relax it -- it was intended to prevent walker authors from directly manipulating the datasources used for the traversal, but it may be doing more harm than good at this point.

**Comment by samuelklee** [comment] 2018-01-25 05:02
@davidbenjamin Just noticed---what about CalculateContamination?

**Comment by davidbenjamin** [comment] 2018-01-25 05:19
@samuelklee Yeah, that should probably be a GATKTool, too.

**Comment by davidbenjamin** [comment] 2020-02-09 06:37
Absorbed by #4341.

**Closed by davidbenjamin** 2020-02-09 06:37 UTC
Labels: Copy Number tools, Engine
