### ISSUE TITLE
protect against regressions involving hdfs

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1391] opened 2015-12-21 18:17 UTC
we need tests that will protect us from regressions like #1390 - we must test on hdfs, on travis or elsewhere

**Comment by akiezun** [comment] 2015-12-23 17:10
@tomwhite can you recommend an approach to this?

**Comment by tomwhite** [comment] 2016-01-04 16:34
@akiezun you can use a `MiniDFSCluster` to run an HDFS cluster in the local JVM. See MetricsUtilsTest and BucketUtilsTest for how to do this.

**Comment by droazen** [comment] 2016-01-05 23:09
Closing as dupe of https://github.com/broadinstitute/gatk/issues/1402

**Closed by droazen** 2016-01-05 23:09 UTC
Labels: PRIORITY_HIGH
