### ISSUE TITLE
Create a separate artifact for gatk test framework classes.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#3567] opened 2017-09-11 20:24 UTC
The main jar contains some test related classes. 

This seems to be due to dependencies from gate-public to gatk-protected when the latter was around (no longer the case) and is maintained in case some gatk user code's depend on them as well. 

IMO there should not be any such a test code in main jar and if it probes to be usefull for some, then we should provide a separate artifact (a test jar add-on).

**Comment by magicDGS** [comment] 2017-09-12 08:26
I think that this is a duplicate of https://github.com/broadinstitute/gatk/issues/1481

**Closed** 2018-08-16 19:46 UTC
Labels: BuildSystem, enhancement, question, refactoring, tests
