### ISSUE TITLE
HaplotypeCaller/Mutect2: vcf header missing the sequence dictionary

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/gatk#2202] opened 2016-10-11 17:44 UTC

**Comment by droazen** [comment] 2016-10-11 17:49
@cmnbroad Could you have a quick look at this one? The problem is that the output vcf for HaplotypeCaller/Mutect2 is missing a sequence dictionary in the header, even though the input bam(s) have a full dictionary.

First place to check is `HaplotypeCallerEngine.makeVCFWriter()` in gatk-protected (and the equivalent method for Mutect2), to make sure the reads dictionary is getting propagated to the VCF/GVCF writer properly.

**Comment by droazen** [comment] 2016-10-11 17:49
(moderately urgent, by the way)

**Comment by cmnbroad** [comment] 2016-10-11 19:08
Looks like we're just not propagating the reads dictionary to the header. PR is [here](https://github.com/broadinstitute/gatk-protected/pull/740).

**Comment by droazen** [comment] 2016-10-11 20:51
Closing, fixed in https://github.com/broadinstitute/gatk-protected/pull/740

**Closed by droazen** 2016-10-11 20:51 UTC
