### ISSUE TITLE
GermlineCNVCaller stdout is uninformative and could summarize some of the verbose information

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#4826] opened 2018-05-29 21:42 UTC
All that you get is the recapitulated command and, e.g.:
```
21:54:28.439 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/shlee/gatk-4.0.4.0/gatk-package-4.0.4.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
21:54:28.625 INFO  GermlineCNVCaller - ------------------------------------------------------------
21:54:28.625 INFO  GermlineCNVCaller - The Genome Analysis Toolkit (GATK) v4.0.4.0
21:54:28.625 INFO  GermlineCNVCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
21:54:28.625 INFO  GermlineCNVCaller - Executing as shlee@brie on Linux v4.13.0-1017-gcp amd64
21:54:28.625 INFO  GermlineCNVCaller - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11
21:54:28.625 INFO  GermlineCNVCaller - Start Date/Time: May 28, 2018 9:54:28 PM UTC
21:54:28.625 INFO  GermlineCNVCaller - ------------------------------------------------------------
21:54:28.625 INFO  GermlineCNVCaller - ------------------------------------------------------------
21:54:28.626 INFO  GermlineCNVCaller - HTSJDK Version: 2.14.3
21:54:28.626 INFO  GermlineCNVCaller - Picard Version: 2.18.2
21:54:28.626 INFO  GermlineCNVCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
21:54:28.626 INFO  GermlineCNVCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
21:54:28.626 INFO  GermlineCNVCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
21:54:28.626 INFO  GermlineCNVCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
21:54:28.627 INFO  GermlineCNVCaller - Deflater: IntelDeflater
21:54:28.627 INFO  GermlineCNVCaller - Inflater: IntelInflater
21:54:28.627 INFO  GermlineCNVCaller - GCS max retries/reopens: 20
21:54:28.627 INFO  GermlineCNVCaller - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
21:54:28.627 WARN  GermlineCNVCaller - 

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

   Warning: GermlineCNVCaller is a BETA tool and is not yet ready for use in production

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


21:54:28.627 INFO  GermlineCNVCaller - Initializing engine
21:54:31.994 INFO  GermlineCNVCaller - Done initializing engine
log4j:WARN No appenders could be found for logger (org.broadinstitute.hdf5.HDF5Library).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
21:54:33.457 INFO  GermlineCNVCaller - Intervals specified...
21:54:34.113 INFO  IntervalArgumentCollection - Processing 10999816 bp from intervals
21:54:34.145 INFO  GermlineCNVCaller - No GC-content annotations for intervals found; explicit GC-bias correction will not be performed...
21:54:34.217 INFO  GermlineCNVCaller - Running the tool in the COHORT mode...
21:54:34.217 INFO  GermlineCNVCaller - Validating and aggregating data from input read-count files...
21:54:34.241 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG00096.lc.soohee1k.hdf5 (1 / 24)
21:54:36.539 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG00268.lc.soohee1k.hdf5 (2 / 24)
21:54:37.967 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG00419.lc.soohee1k.hdf5 (3 / 24)
21:54:40.147 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG00759.lc.soohee1k.hdf5 (4 / 24)
21:54:41.782 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG01051.lc.soohee1k.hdf5 (5 / 24)
21:54:43.197 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG01112.lc.soohee1k.hdf5 (6 / 24)
21:54:45.169 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG01500.lc.soohee1k.hdf5 (7 / 24)
21:54:46.852 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG01565.lc.soohee1k.hdf5 (8 / 24)
21:54:48.387 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG01583.lc.soohee1k.hdf5 (9 / 24)
21:54:50.875 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG01595.lc.soohee1k.hdf5 (10 / 24)
21:54:52.876 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG01879.lc.soohee1k.hdf5 (11 / 24)
21:54:54.983 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG02568.lc.soohee1k.hdf5 (12 / 24)
21:54:57.191 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG02922.lc.soohee1k.hdf5 (13 / 24)
21:54:59.116 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG03006.lc.soohee1k.hdf5 (14 / 24)
21:55:00.890 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG03052.lc.soohee1k.hdf5 (15 / 24)
21:55:02.822 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG03642.lc.soohee1k.hdf5 (16 / 24)
21:55:04.931 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/HG03742.lc.soohee1k.hdf5 (17 / 24)
21:55:06.457 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/NA18525.lc.soohee1k.hdf5 (18 / 24)
21:55:07.933 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/NA18939.lc.soohee1k.hdf5 (19 / 24)
21:55:09.347 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/NA19017.lc.soohee1k.hdf5 (20 / 24)
21:55:11.068 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/NA19625.lc.soohee1k.hdf5 (21 / 24)
21:55:13.479 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/NA19648.lc.soohee1k.hdf5 (22 / 24)
21:55:15.323 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/NA20502.lc.soohee1k.hdf5 (23 / 24)
21:55:17.219 INFO  GermlineCNVCaller - Aggregating read-count file /home/shlee/gcnv/low_coverage_1k/NA20845.lc.soohee1k.hdf5 (24 / 24)
01:27:10.674 INFO  GermlineCNVCaller - Germline denoising and CNV calling complete.
01:27:10.676 INFO  GermlineCNVCaller - Shutting down engine
[May 29, 2018 1:27:10 AM UTC] org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller done. Elapsed time: 212.70 minutes.
Runtime.totalMemory()=5764022272
Tool returned:
SUCCESS
```

Would be great to have a summary of useful information, e.g. (but not limited to):

- Total number of epochs (INFO level)
- ELBO value and SNR value etc for the final epochs (INFO level)
- Whether convergence was achieved or not (WARN if not)

Currently, the only way to get all three pieces of information is through setting `--verbosity DEBUG`, which makes for very long stdouts that go well beyond what tmux saves.

**Comment by sooheelee** [comment] 2018-05-29 21:44
Not sure who's attention to bring this to, so assigning @samuelklee to delegate.

**Comment by mbabadi** [comment] 2018-05-30 16:22
@sooheelee, the computation engine `gcnvkernel` produces a lot of informative messages, however, they are not shown unless you run GATK with `--verbosity DEBUG`. I have filed an issue about it: #4629. @cmnbroad could you please take a look at the issue?

**Comment by samuelklee** [comment] 2018-06-04 20:21
I think this is essentially a dupe of #4629, so I'm closing it.  @cmnbroad please do let us know when the issue's addressed, though!

**Closed by samuelklee** 2018-06-04 20:21 UTC

**Comment by cmnbroad** [comment] 2018-06-05 11:42
@samuelklee @mbabadi I Haven't forgotten about this, though I'm not sure when I'll get to it.
