### ISSUE TITLE
PostprocessGermlineCNVCalls errors on chunk consisting of random and unplaced contigs.

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#4840] opened 2018-05-31 22:10 UTC
Random and unplaced contigs are a part of the primary assembly. The tool also errors on decoy contigs but no other GRCh38 contig type. This ticket is to investigate why this error is happening for this subset of the data.

Error is
```
Stdout: 22:01:54.365 INFO segment_gcnv_calls - Loading ploidy calls...
22:01:54.366 INFO gcnvkernel.io.io_metadata - Loading germline contig ploidy and global read depth metadata...
22:01:54.381 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chrM). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.381 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr1_KI270706v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.381 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr1_KI270707v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.381 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr1_KI270708v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.381 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr1_KI270709v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr1_KI270710v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr1_KI270711v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr1_KI270712v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr1_KI270713v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr1_KI270714v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr2_KI270715v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr2_KI270716v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr3_GL000221v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr4_GL000008v2_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr5_GL000208v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr9_KI270717v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr9_KI270718v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr9_KI270719v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.382 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr9_KI270720v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr11_KI270721v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr14_GL000009v2_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr14_GL000225v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr14_KI270722v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr14_GL000194v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr14_KI270723v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr14_KI270724v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr14_KI270725v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr14_KI270726v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr15_KI270727v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr16_KI270728v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr17_GL000205v2_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr17_KI270729v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.383 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr17_KI270730v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.384 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr22_KI270731v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.384 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr22_KI270732v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.384 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr22_KI270733v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.384 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr22_KI270734v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.384 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr22_KI270735v1_random). Germline contig ploidy determination may not be reliable for decoy/non-standard contigs.
22:01:54.384 WARNING gcnvkernel.structs.metadata - Sample HG01565 has an unrecognized contig (chr22_KI270736v1_ra
Stderr: Traceback (most recent call last):
  File "/home/shlee/anaconda3/envs/gatk/lib/python3.6/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "/home/shlee/anaconda3/envs/gatk/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 989, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/shlee/anaconda3/envs/gatk/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 978, in p
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 215, in theano.scan_module.scan_perform.perform (/home/shlee/.theano/compiledir_Linux-4.13--gcp-x86_64-with-debian-stretch-sid-x86_64-3.6.2-64/scan_perform/mod.cpp:2628)
NotImplementedError: We didn't implemented yet the case where scan do 0 iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/shlee/segment_gcnv_calls.5861176430020419759.py", line 73, in <module>
    viterbi_engine.write_copy_number_segments_for_single_sample(args.sample_index)
  File "/home/shlee/anaconda3/envs/gatk/lib/python3.6/site-packages/gcnvkernel/postprocess/viterbi_segmentation.py", line 265, in write_copy_number_segments_for_single_sample
    for segment in self._viterbi_segments_generator_for_single_sample(sample_index):
  File "/home/shlee/anaconda3/envs/gatk/lib/python3.6/site-packages/gcnvkernel/postprocess/viterbi_segmentation.py", line 188, in _viterbi_segments_generator_for_single_sample
    log_prior_c, log_trans_contig_tcc, copy_number_log_emission_contig_tc)
  File "/home/shlee/anaconda3/envs/gatk/lib/python3.6/site-packages/gcnvkernel/models/theano_hmm.py", line 88, in perform_forward_backward
    prev_log_posterior_tc, admixing_rate, temperature)))
  File "/home/shlee/anaconda3/envs/gatk/lib/python3.6/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/shlee/anaconda3/envs/gatk/lib/python3.6/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/shlee/anaconda3/envs/gatk/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/shlee/anaconda3/envs/gatk/lib/python3.6/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "/home/shlee/anaconda3/envs/gatk/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 989, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/shlee/anaconda3/envs/gatk/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 978, in p
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 215, in theano.scan_module.scan_perform.perform (/home/shlee/.theano/compiledir_Linux-4.13--gcp-x86_64-with-debian-stretch-sid-x86_64-3.6.2-64/scan_perform/mod.cpp:2628)
NotImplementedError: We didn't implemented yet the case where scan do 0 iteration
Apply node that caused the error: forall_inplace,cpu,scan_fn}(Elemwise{minimum,no_inplace}.0, InplaceDimShuffle{0,2,1}.0, Subtensor{int64:int64:int64}.0, IncSubtensor{InplaceSet;:int64:}.0, Shape_i{0}.0)
Toposort index: 97
Inputs types: [TensorType(int64, scalar), TensorType(float64, 3D), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(int64, scalar)]
Inputs shapes: [(), (0, 6, 6), (0, 6), (2, 6), ()]
Inputs strides: [(), (288, 8, 48), (48, 8), (48, 8), ()]
Inputs values: [array(0), array([], shape=(0, 6, 6), dtype=float64), array([], shape=(0, 6), dtype=float64), 'not shown', array(6)]
Outputs clients: [[Subtensor{int64:int64:int8}(forall_inplace,cpu,scan_fn}.0, ScalarFromTensor.0, ScalarFromTensor.0, Constant{1})]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be d
isabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

        at org.broadinstitute.hellbender.utils.python.PythonExecutorBase.getScriptException(PythonExecutorBase.java:75)
        at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:126)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeArgs(PythonScriptExecutor.java:170)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:151)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:121)
        at org.broadinstitute.hellbender.tools.copynumber.PostprocessGermlineCNVCalls.executeSegmentGermlineCNVCallsPythonScript(PostprocessGermlineCNVCalls.java:500)
        at org.broadinstitute.hellbender.tools.copynumber.PostprocessGermlineCNVCalls.generateSegmentsVCFFileFromAllShards(PostprocessGermlineCNVCalls.java:436)
        at org.broadinstitute.hellbender.tools.copynumber.PostprocessGermlineCNVCalls.traverse(PostprocessGermlineCNVCalls.java:297)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:892)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

Let me know what data files we need to look into to figure out the cause of error so I can make them available.

**Comment by samuelklee** [comment] 2019-08-29 19:12
I think this is actually a dupe of #5852, closing.

**Closed by samuelklee** 2019-08-29 19:12 UTC
Labels: Copy Number tools, Germline CNV
