### ISSUE TITLE
Error in Mutect2

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#4665] opened 2018-04-17 14:17 UTC
A couple of users have reported errors with --disable-tool-default-read-filters. Is this expected? This user says the tool runs without that flag.

----
User Report
----

I just encountered this error in Mutect2: 

Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx4g -jar /Users/loeblabm11/bioinformatics/programs/GATK/gatk-4.0.3.0/gatk-package-4.0.3.0-local.jar Mutect2 -R /Users/loeblabm11/bioinformatics/reference/human/hg19/hg19.fa -I 20171027_BN31_python.dcs.filt.no_overlap.bam -tumor BN31 -O 20171027_BN31_python.dcs.MuTect2.vcf -bamout 20171027_BN31_python.dcs.MuTect2.bam --max-reads-per-alignment-start 0 --max-population-af 1 --disable-tool-default-read-filters
12:18:10.900 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/loeblabm11/bioinformatics/programs/GATK/gatk-4.0.3.0/gatk-package-4.0.3.0-local.jar!/com/intel/gkl/native/libgkl_compression.dylib
12:18:11.387 INFO  Mutect2 - ------------------------------------------------------------
12:18:11.388 INFO  Mutect2 - The Genome Analysis Toolkit (GATK) v4.0.3.0
12:18:11.388 INFO  Mutect2 - For support and documentation go to https://software.broadinstitute.org/gatk/
12:18:11.388 INFO  Mutect2 - Executing as loeblabm11@LoeblabM11s-iMac.local on Mac OS X v10.12.6 x86_64
12:18:11.388 INFO  Mutect2 - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_151-b12
12:18:11.388 INFO  Mutect2 - Start Date/Time: April 11, 2018 12:18:10 PM PDT
12:18:11.388 INFO  Mutect2 - ------------------------------------------------------------
12:18:11.388 INFO  Mutect2 - ------------------------------------------------------------
12:18:11.388 INFO  Mutect2 - HTSJDK Version: 2.14.3
12:18:11.388 INFO  Mutect2 - Picard Version: 2.17.2
12:18:11.388 INFO  Mutect2 - HTSJDK Defaults.COMPRESSION_LEVEL : 2
12:18:11.388 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
12:18:11.388 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
12:18:11.388 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
12:18:11.388 INFO  Mutect2 - Deflater: IntelDeflater
12:18:11.388 INFO  Mutect2 - Inflater: IntelInflater
12:18:11.389 INFO  Mutect2 - GCS max retries/reopens: 20
12:18:11.389 INFO  Mutect2 - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
12:18:11.389 INFO  Mutect2 - Initializing engine
12:18:11.724 INFO  Mutect2 - Done initializing engine
12:18:12.288 INFO  NativeLibraryLoader - Loading libgkl_utils.dylib from jar:file:/Users/loeblabm11/bioinformatics/programs/GATK/gatk-4.0.3.0/gatk-package-4.0.3.0-local.jar!/com/intel/gkl/native/libgkl_utils.dylib
12:18:12.290 WARN  NativeLibraryLoader - Unable to find native library: native/libgkl_pairhmm_omp.dylib
12:18:12.290 INFO  PairHMM - OpenMP multi-threaded AVX-accelerated native PairHMM implementation is not supported
12:18:12.290 INFO  NativeLibraryLoader - Loading libgkl_pairhmm.dylib from jar:file:/Users/loeblabm11/bioinformatics/programs/GATK/gatk-4.0.3.0/gatk-package-4.0.3.0-local.jar!/com/intel/gkl/native/libgkl_pairhmm.dylib
12:18:12.368 WARN  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
12:18:12.368 WARN  IntelPairHmm - Ignoring request for 4 threads; not using OpenMP implementation
12:18:12.369 INFO  PairHMM - Using the AVX-accelerated native PairHMM implementation
12:18:12.403 INFO  ProgressMeter - Starting traversal
12:18:12.403 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Regions Processed   Regions/Minute
12:18:22.403 INFO  ProgressMeter -        chr1:75065650              0.2                250240        1501440.0
12:18:29.713 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 0.009098343
12:18:29.713 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 0.121747383
12:18:29.713 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 0.42 sec
12:18:29.763 INFO  Mutect2 - Shutting down engine
[April 11, 2018 12:18:29 PM PDT] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.31 minutes.
Runtime.totalMemory()=1781006336
java.lang.NullPointerException
	at org.broadinstitute.hellbender.utils.locusiterator.ReadStateManager.readStartsAtCurrentPosition(ReadStateManager.java:132)
	at org.broadinstitute.hellbender.utils.locusiterator.ReadStateManager.collectPendingReads(ReadStateManager.java:159)
	at org.broadinstitute.hellbender.utils.locusiterator.LocusIteratorByState.lazyLoadNextAlignmentContext(LocusIteratorByState.java:315)
	at org.broadinstitute.hellbender.utils.locusiterator.LocusIteratorByState.hasNext(LocusIteratorByState.java:252)
	at org.broadinstitute.hellbender.utils.locusiterator.IntervalAlignmentContextIterator.advanceAlignmentContext(IntervalAlignmentContextIterator.java:104)
	at org.broadinstitute.hellbender.utils.locusiterator.IntervalAlignmentContextIterator.advanceAlignmentContextToCurrentInterval(IntervalAlignmentContextIterator.java:99)
	at org.broadinstitute.hellbender.utils.locusiterator.IntervalAlignmentContextIterator.next(IntervalAlignmentContextIterator.java:69)
	at org.broadinstitute.hellbender.utils.locusiterator.IntervalAlignmentContextIterator.next(IntervalAlignmentContextIterator.java:21)
	at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.loadNextAssemblyRegion(AssemblyRegionIterator.java:143)
	at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:135)
	at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:34)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:290)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:271)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

My command looks like this:
~/bioinformatics/programs/GATK/gatk-4.0.3.0/gatk --java-options "-Xmx4g" Mutect2 -R /Users/loeblabm11/bioinformatics/reference/human/hg19/hg19.fa -I 20171027_BN31_python.dcs.filt.no_overlap.bam -tumor BN31 -O 20171027_BN31_python.dcs.MuTect2.vcf -bamout 20171027_BN31_python.dcs.MuTect2.bam --max-reads-per-alignment-start 0 --max-population-af 1 --disable-tool-default-read-filters

and I'm running on MacOSX Sierra (10.12.6).  java -version returns 
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

The input file is position-sorted output from Duplex Sequencing pipelines, and has been through IndelRealigner (from GATK 3.7), and ClipOverlappingReads from FgBio.  It has been indexed.  

I can put together a full bug report, complete with my input file, if necessary; I just want an idea of what might be happening.  

Brendan

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/11790/error-in-mutect2/p1

**Comment by droazen** [comment] 2018-04-18 12:57
@chandrans I agree with @cmnbroad. In GATK4 we allow users the freedom to disable all built-in read filters via `--disable-tool-default-read-filters`, however users should really know what they're doing when they run with that option. Most tools require reads to be well-formed (and therefore the `WellformedReadFilter`), and `Mutect2` definitely requires the `MappedReadFilter` in order to function correctly. Perhaps the user should try selectively disabling individual read filters rather than turning them all off at once.

**Comment by droazen** [comment] 2018-04-18 12:57
Closing -- works as intended.

**Closed by droazen** 2018-04-18 12:57 UTC
Labels: Vanilla

**Comment by chandrans** [comment] 2018-04-18 14:30
Okay. Thanks. I will refer user to this thread. I also saw you made the flag an advanced argument, so hopefully that will help.

**Comment by Ismaelfermir** [comment] 2019-04-23 09:37
Hi! I have the same issue as @chandrans.
When I run Mutect2 this is the error:
`(gatk) root@d387db9e4351:/Desktop# gatk Mutect2 -R /Desktop/UCSC_hg19_genome.fasta -I /Desktop/HP0049.bam -O /Desktop/HP0049.vcf.g
Using GATK jar /gatk/gatk-package-4.1.1.0-local.ja
Running:

    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gatk/gatk-package-4.1.1.0-local.jar Mutect2 -R /Desktop/UCSC_hg19_genome.fasta -I /Desktop/HP0049.bam -O /Desktop/HP0049.vcf.g
08:27:06.032 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/gatk-package-4.1.1.0-local.jar!/com/intel/gkl/native/libgkl_compression.s
Apr 23, 2019 8:27:10 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngin
INFO: Failed to detect whether we are running on Google Compute Engine.

08:27:10.882 INFO  Mutect2 - -----------------------------------------------------------
08:27:10.883 INFO  Mutect2 - The Genome Analysis Toolkit (GATK) v4.1.1.
08:27:10.883 INFO  Mutect2 - For support and documentation go to https://software.broadinstitute.org/gatk/

08:27:10.884 INFO  Mutect2 - Executing as root@d387db9e4351 on Linux v4.9.125-linuxkit amd64

08:27:10.884 INFO  Mutect2 - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12

08:27:10.885 INFO  Mutect2 - Start Date/Time: April 23, 2019 8:27:05 AM UT
08:27:10.885 INFO  Mutect2 - -----------------------------------------------------------
08:27:10.886 INFO  Mutect2 - -----------------------------------------------------------
08:27:10.887 INFO  Mutect2 - HTSJDK Version: 2.19.
08:27:10.887 INFO  Mutect2 - Picard Version: 2.19.
08:27:10.887 INFO  Mutect2 - HTSJDK Defaults.COMPRESSION_LEVEL : 2

08:27:10.888 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : fals
08:27:10.888 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : tru
08:27:10.888 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : fals
08:27:10.888 INFO  Mutect2 - Deflater: IntelDeflate
08:27:10.889 INFO  Mutect2 - Inflater: IntelInflate
08:27:10.889 INFO  Mutect2 - GCS max retries/reopens: 2
08:27:10.889 INFO  Mutect2 - Requester pays: disable
08:27:10.889 INFO  Mutect2 - Initializing engin
08:27:11.333 INFO  Mutect2 - Done initializing engin
08:27:11.381 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/gatk/gatk-package-4.1.1.0-local.jar!/com/intel/gkl/native/libgkl_utils.s
08:27:11.383 INFO  NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/gatk/gatk-package-4.1.1.0-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.s
08:27:11.426 INFO  **IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHM**
08:27:11.427 INFO  IntelPairHmm - Available threads: 4
08:27:11.428 INFO  IntelPairHmm - Requested threads: 4
08:27:11.428 INFO  PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementatio
08:27:11.432 INFO  Mutect2 - Shutting down engin
[April 23, 2019 8:27:11 AM UTC] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.09 minutes.
Runtime.totalMemory()=190840832
java.lang.IllegalArgumentException: samples cannot be empt
	at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:724)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.ReferenceConfidenceModel.<init>(ReferenceConfidenceModel.java:116)
	at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticReferenceConfidenceModel.<init>(SomaticReferenceConfidenceModel.java:38)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.<init>(Mutect2Engine.java:149)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.onTraversalStart(Mutect2.java:286)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:982)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)`

I think that it is a issue from the PairHMM: 

> IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHM

I work with a Mac so I don't know if it is a problem from it. I try with the --disable-tool-default-read-filters option but it did not work.

**Comment by droazen** [comment] 2019-04-24 19:02
@Ismaelfermir The message about "Flush-to-zero" is normal, and not an error. The problem is likely that your BAM doesn't have read groups in its header, or if it does, those read groups may lack sample names.
