### ISSUE TITLE
two classes called ReferenceFileSource

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1238] opened 2015-12-03 14:59 UTC
`org.broadinstitute.hellbender.engine.ReferenceFileSource`
`org.broadinstitute.hellbender.engine.datasources.ReferenceFileSource`

for @droazen to resolve

**Comment by droazen** [comment] 2015-12-03 16:51
This is a dupe of https://github.com/broadinstitute/gatk/issues/959 -- closing.

**Closed by droazen** 2015-12-03 16:51 UTC
Labels: bogus
