### ISSUE TITLE
ReadSparkSink produced non-coor sorted BAM

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/gatk#1249] opened 2015-12-04 15:06 UTC
${GATK4_JAR} MarkDuplicatesSpark -I  src/test/resources/org/broadinstitute/hellbender/tools/BQSR/CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam -O tmp.junk.bam --METRICS_FILE=tmp.metrics -parallelism 1

samtools view tmp.junk.bam | less
and you'll see 1001995 ahead of 1001645
Offending records are at [20:1001995] and [20:1001645]

**Comment by droazen** [comment] 2015-12-04 15:14
For @tomwhite to look at when he has a chance.

**Comment by tomwhite** [comment] 2015-12-04 15:22
@davidadamsphd @droazen ReadsSparkSink doesn't sort when writing sharded output: https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java#L125-L148.

Should this always sort by position? If so, should it do a total sort (like the single file case), or a partial sort (where the reads are sorted within each partition)?

**Comment by droazen** [comment] 2015-12-04 15:27
We're not writing sharded output, though -- notice that we're running with `-parallelism 1`, which causes us to call `ReadsSparkSink.writeReads()` with `ReadsWriteFormat.SINGLE`

**Comment by tomwhite** [comment] 2015-12-04 16:21
You're right. I had a look and I think it's to do with an inconsistency between org.broadinstitute.hellbender.utils.read.ReadCoordinateComparator (used by Spark for sorting), and htsjdk.samtools.SAMRecordCoordinateComparator (used by samtools).

The offending record seems to be the first unmapped one, and has been placed after [20:1001995] by MarkDuplicatesSpark:

```
20GAVAAXX100126:4:24:10635:52735 20:1001995-1002095
20FUKAAXX100202:1:22:1193:123181 UNMAPPED
```

Any thoughts about how to fix this?

**Comment by akiezun** [comment] 2015-12-04 16:27
ugh, unmapped reads biting us again. I bet it's an unmapped read (as in isUnmapped()) that still does has a start position - can you check? We consider those reads invalid and may sort them badly.

**Comment by tomwhite** [comment] 2015-12-04 16:30
Yes, I think that's what's happening. Not sure how to fix though.

**Comment by yfarjoun** [comment] 2015-12-04 16:32
these reads should not be considered invalid as we place unmappable mates
in the same position as their mate (I think).

**Comment by droazen** [comment] 2015-12-04 16:34
We don't consider them as invalid -- we consider them to be unmapped, even though they have a position (including reference index).

**Comment by droazen** [comment] 2015-12-04 16:37
@akiezun I think you may have been thinking of the opposite situation, a read with the unmapped flag NOT set but an unmapped value in either the reference name or position fields -- we consider these reads as unmapped in hellbender, which is different from htsjdk.

**Comment by akiezun** [comment] 2015-12-04 16:38
aha! true

**Comment by droazen** [comment] 2015-12-04 17:06
Discussed in person just now -- we are going to change `ReadsSparkSink` so that it internally operates on a `JavaPairRDD<SAMRecord, SAMRecordWritable>` and uses `SAMRecordCoordinateComparator` to order the output instead of operating on a `JavaPairRDD<GATKRead, SAMRecordWritable>` and using `ReadCoordinateComparator`. This should be fine since the writer being used in Hadoop-BAM is the `KeyIgnoringSAMRecordWriter`, which doesn't care what the keys are in the `JavaPairRDD`.

**Comment by tomwhite** [comment] 2015-12-04 17:14
I don't think that will work as the key needs to be `GATKRead` to take advantage of the `SAMRecordToGATKReadAdapterSerializer`.

How about writing a new `Comparator<GATKRead>` that wraps a `SAMRecordCoordinateComparator`? That should be pretty simple and won't require a new serializer.

BTW minor correction: `ReadSparkSink` operates on `JavaPairRDD<GATKRead, Void>` (not `JavaPairRDD<GATKRead, SAMRecordWritable>`) at the moment - the values are null so as to not duplicate the amount of data going through the shuffle.

**Comment by droazen** [comment] 2015-12-04 17:20
@tomwhite The problem is that `GATKRead` does not expose the "positions" of reads that are marked as unmapped (this was a conscious design choice so that client code doesn't have to check 5 different fields to determine whether a read is unmapped or not). So we could write a new comparator, but it would have to convert to `SAMRecord` internally and would only be used when writing -- this is why we initially preferred to patch `ReadsSparkSink` rather than write a new comparator. But it looks like we have no choice...

**Comment by tomwhite** [comment] 2015-12-04 17:24
OK, then writing a `SAMRecordSerializer` might be another option. If you look at `SAMRecordToGATKReadAdapterSerializer` you'll see that it basically extracts a `SAMRecord` from a `GATKRead` then encodes it to the stream.

**Closed** 2015-12-05 00:28 UTC
Labels: bug, PRIORITY_HIGH, Spark
