### ISSUE TITLE
Add LearnReadOrientationModel documentation to ToolDocs

### ISSUE THREAD

**Issue by gbrandt6** [broadinstitute/gatk#6862] opened 2020-10-05 22:36 UTC
### Tool(s) or class(es) involved
LearnReadOrientationModel

### Description 
The tool LearnReadOrientationModel does not appear in the tool docs. We would like to update the documentation for this tool so that it is included with the other tool docs when GATK is updated and is more visible to users.

**Comment by cmnbroad** [comment] 2020-10-06 12:29
This is a duplicate of https://github.com/broadinstitute/gatk/issues/6720, which has already been fixed in https://github.com/broadinstitute/gatk/pull/6726. The doc will appear in the next release.

**Closed by cmnbroad** 2020-10-06 12:29 UTC

**Comment by gbrandt6** [comment] 2020-10-06 19:18
Thank you @cmnbroad
