### ISSUE TITLE
Edge case in hardclipping a read

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/gatk#3813] opened 2017-11-08 22:24 UTC
We have a problematic read that goes in as cigar `14S45M92S` (or something similar) and turns `137H14S` when clipped by `ReadClipper.hardClipLowQualEnds` `(AssemblyBasedCallerUtils::L73)`. This is because the first 137 are base quality 2. M2 (and HC) fails later on because we miscalculate the start position as -4. This only occurs when a specific interval file is used. When run with `-L chrM`, the we don't get the error, for example.

Problematic bam: `/seq/picard_aggregation/RP-1490/WGS/OCB006937/v2/OCB006937.bam`
Read Name: `H3FWGCCXY170920`
Position: chrM:147-146 (this is what I wrote down but I'm not sure if it's right)
Reference: `/seq/references/Mus_musculus_assembly10/v0/Mus_musculus_assembly10.fasta` (this is a mouse reference)

```
java.lang.IllegalArgumentException: contig must be non-null and not equal to *, and start must be >= 1
contig = chrM
start = -4
	at org.broadinstitute.hellbender.utils.read.SAMRecordToGATKReadAdapter.setPosition(SAMRecordToGATKReadAdapter.java:92)
	at org.broadinstitute.hellbender.utils.clipping.ClippingOp.applyHARDCLIP_BASES(ClippingOp.java:381)
	at org.broadinstitute.hellbender.utils.clipping.ClippingOp.apply(ClippingOp.java:73)
	at org.broadinstitute.hellbender.utils.clipping.ReadClipper.clipRead(ReadClipper.java:145)
	at org.broadinstitute.hellbender.utils.clipping.ReadClipper.clipRead(ReadClipper.java:126)
	at org.broadinstitute.hellbender.utils.clipping.ReadClipper.hardClipSoftClippedBases(ReadClipper.java:330)
	at org.broadinstitute.hellbender.utils.clipping.ReadClipper.hardClipSoftClippedBases(ReadClipper.java:333)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.finalizeRegion(AssemblyBasedCallerUtils.java:82)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:242)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:211)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:245)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:317)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:293)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:838)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:119)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:176)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:195)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:137)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:158)
	at org.broadinstitute.hellbender.Main.main(Main.java:239)
```

**Comment by lbergelson** [comment] 2018-01-05 19:56
I'm closing this because I believe it's a duplicate of #3466.  Track that issue for updates.

**Closed by lbergelson** 2018-01-05 19:56 UTC
Labels: bug, HaplotypeCaller

**Comment by droazen** [comment] 2018-01-08 16:59
Fix for this issue is here: https://github.com/broadinstitute/gatk/pull/4080
