### ISSUE TITLE
Request created from: run into PythonScriptExecutorException when executing PostprocessGermlineCNVCalls about positional arguments

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#7444] opened 2021-08-30 17:34 UTC
This request was created from a contribution made by Yangyxt on August 30, 2021 08:18 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/4405983290395-run-into-PythonScriptExecutorException-when-executing-PostprocessGermlineCNVCalls-about-positional-arguments](https://gatk.broadinstitute.org/hc/en-us/community/posts/4405983290395-run-into-PythonScriptExecutorException-when-executing-PostprocessGermlineCNVCalls-about-positional-arguments)

\--

If you are seeing an error, please provide(REQUIRED) :  
  
a) GATK version used: 4.2.2.0  
  
b) Exact command used:

${gatk} PostprocessGermlineCNVCalls \\

\--model-shard-path ${gCNV\_model\_prefix}-model \\

\--calls-shard-path ${gCNV\_case\_prefix}-calls \\

\--allosomal-contig chrX --allosomal-contig chrY \\

\--contig-ploidy-calls ${ploidy\_case\_prefix}-calls \\

\--sample-index ${sample\_index} \\

\--output-denoised-copy-ratios ${cnv\_dir}/${sampleID}.sample\_${sample\_index}.denoised\_copy\_ration.tsv \\

\--output-genotyped-intervals ${cnv\_dir}/genotyped-intervals-case-${sampleID}-vs-${probe}cohort.vcf.gz \\

\--output-genotyped-segments ${cnv\_dir}/genotyped-segments-case-${sampleID}-vs-${probe}cohort.vcf.gz \\

\--sequence-dictionary ${ref\_gen}/ucsc.hg19.dict

c) Entire error log:

11:04:20.841 INFO NativeLibraryLoader - Loading libgkl\_compression.so from jar:file:/home/yangyxt/software/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar!/com/intel/gkl/native/libgkl\_compression.so  
  
Aug 30, 2021 11:04:20 AM shaded.cloud\_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine  
  
INFO: Failed to detect whether we are running on Google Compute Engine.  
  
11:04:20.983 INFO PostprocessGermlineCNVCalls - ------------------------------------------------------------  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - The Genome Analysis Toolkit (GATK) v4.2.2.0  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - For support and documentation go to [https://software.broadinstitute.org/gatk/](https://software.broadinstitute.org/gatk/)  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - Executing as yangyxt@paedyl02 on Linux v3.10.0-1160.11.1.el7.x86\_64 amd64  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - Java runtime: OpenJDK 64-Bit Server VM v1.8.0\_152-release-1056-b12  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - Start Date/Time: August 30, 2021 11:04:20 AM HKT  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - ------------------------------------------------------------  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - ------------------------------------------------------------  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - HTSJDK Version: 2.24.1  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - Picard Version: 2.25.4  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - Built for Spark Version: 2.4.5  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - HTSJDK Defaults.COMPRESSION\_LEVEL : 2  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - HTSJDK Defaults.USE\_ASYNC\_IO\_READ\_FOR\_SAMTOOLS : false

11:04:20.984 INFO PostprocessGermlineCNVCalls - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_SAMTOOLS : true  
  
11:04:20.984 INFO PostprocessGermlineCNVCalls - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_TRIBBLE : false  
  
11:04:20.985 INFO PostprocessGermlineCNVCalls - Deflater: IntelDeflater  
  
11:04:20.985 INFO PostprocessGermlineCNVCalls - Inflater: IntelInflater  
  
11:04:20.985 INFO PostprocessGermlineCNVCalls - GCS max retries/reopens: 20  
  
11:04:20.985 INFO PostprocessGermlineCNVCalls - Requester pays: disabled  
  
11:04:20.985 INFO PostprocessGermlineCNVCalls - Initializing engine  
  
11:04:26.627 INFO PostprocessGermlineCNVCalls - Done initializing engine  
  
11:04:27.492 INFO ProgressMeter - Starting traversal  
  
11:04:27.492 INFO ProgressMeter - Current Locus Elapsed Minutes Records Processed Records/Minute  
  
11:04:27.493 INFO ProgressMeter - unmapped 0.0 0 NaN  
  
11:04:27.493 INFO ProgressMeter - Traversal complete. Processed 0 total records in 0.0 minutes.  
  
11:04:27.493 INFO PostprocessGermlineCNVCalls - Generating intervals VCF file...  
  
11:04:27.510 INFO PostprocessGermlineCNVCalls - Writing intervals VCF file to /staging/wes/1\_sample\_20210615/CNV\_calling/genotyped-intervals-case-A210066-vs-v7cohort.vcf.gz...  
  
11:04:27.510 INFO PostprocessGermlineCNVCalls - Analyzing shard 1 / 1...  
  
11:04:30.169 INFO PostprocessGermlineCNVCalls - Generating segments...  
  
11:04:37.131 INFO PostprocessGermlineCNVCalls - Shutting down engine  
  
\[August 30, 2021 11:04:37 AM HKT\] org.broadinstitute.hellbender.tools.copynumber.PostprocessGermlineCNVCalls done. Elapsed time: 0.27 minutes.  
  
Runtime.totalMemory()=2463105024  
  
org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException:  
  
python exited with 1  
  
Command Line: python /tmp/segment\_gcnv\_calls.8152704641395924200.py --ploidy\_calls\_path /staging/wes/healthy\_bams\_for\_CNV/using\_v7\_probe/v7\_case\_ploidy/v7\_cases\_ploidy\_1\_sample\_20210615-calls --model\_shards /staging/wes/healthy\_bams\_for\_C  
  
Stdout: 11:04:36.532 INFO segment\_gcnv\_calls - THEANO\_FLAGS environment variable has been set to: device=cpu,floatX=float64,optimizer=fast\_run,compute\_test\_value=ignore,openmp=true,blas.ldflags=-lmkl\_rt,openmp\_elemwise\_minsize=10  
  
11:04:36.532 INFO segment\_gcnv\_calls - Loading ploidy calls...  
  
11:04:36.533 INFO gcnvkernel.io.io\_metadata - Loading germline contig ploidy and global read depth metadata...  
  
11:04:36.543 INFO segment\_gcnv\_calls - Instantiating the Viterbi segmentation engine...

Stderr: Traceback (most recent call last):  
  
File "/tmp/segment\_gcnv\_calls.8152704641395924200.py", line 92, in <module>  
  
args.intervals\_vcf, args.clustered\_vcf)  
  
TypeError: \_\_init\_\_() takes 6 positional arguments but 8 were given

at org.broadinstitute.hellbender.utils.python.PythonExecutorBase.getScriptException(PythonExecutorBase.java:75)  
  
at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:112)  
  
at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeArgs(PythonScriptExecutor.java:193)  
  
at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:168)  
  
at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:139)  
  
at org.broadinstitute.hellbender.tools.copynumber.PostprocessGermlineCNVCalls.executeSegmentGermlineCNVCallsPythonScript(PostprocessGermlineCNVCalls.java:739)  
  
at org.broadinstitute.hellbender.tools.copynumber.PostprocessGermlineCNVCalls.generateSegmentsVCFFileFromAllShards(PostprocessGermlineCNVCalls.java:485)  
  
at org.broadinstitute.hellbender.tools.copynumber.PostprocessGermlineCNVCalls.onTraversalSuccess(PostprocessGermlineCNVCalls.java:456)  
  
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1089)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)  
  
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)  
  
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)  
  
at org.broadinstitute.hellbender.Main.main(Main.java:289)  
  
Using GATK jar /home/yangyxt/software/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar  
  
Running:  
  
java -Dsamjdk.use\_async\_io\_read\_samtools=false -Dsamjdk.use\_async\_io\_write\_samtools=true -Dsamjdk.use\_async\_io\_write\_tribble=false -Dsamjdk.compression\_level=2 -jar /home/yangyxt/software/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar Po

If not an error, choose a category for your question(REQUIRED):  
  
a)How do I (......)?  
  
b) What does (......) mean?  
  
c) Why do I see (......)?  
  
d) Where do I find (......)?  
  
e) Will (......) be in future releases?<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/181533'>Zendesk ticket #181533</a>)<br>gz#181533</i>

**Comment by yangyxt** [comment] 2021-08-30 17:43
Hi, I think this can be closed now. 

I just found that this issue might due to the inconsistency between gCNV version and PostProcessGermlineCNVCalls version. 
I updated my python configuration from 4.1.8.0 to 4.2.2.0 and the issue is gone. 

Sorry for the troubles here.

**Comment by droazen** [comment] 2021-08-30 18:08
Thanks for following up @yangyxt ! Closing as resolved

**Closed by droazen** 2021-08-30 18:08 UTC

**Comment by cmnbroad** [comment] 2021-10-18 13:44
@urano95 Are you certain that you're running with the correct GATK conda environment? The previous report for this issue indicates that it was caused by using an out-of-date GATK python environment. I would remove and then re-create the GATK conda environment and see if the problem persists.
