### ISSUE TITLE
using -L pulls in unmapped reads on Spark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1060] opened 2015-10-28 02:22 UTC
It seems that using -L pulls in unmapped reads which is not what we want I think. The reason I think unmapped reads are pulled in is this progress log from a Spark job. Note the 'Current locus' on the last line

```
org.broadinstitute.hellbender.tools.CountReads  --intervals 1:1-20000000 --input /humgen/gsa-hpprojects/NA12878Collection/bams/CEUTrio.HiSeq.WGS.b37.NA12878.bam  --disable_all_read_filters false --interval_set_rule UNION --interval_padding 0 --secondsBetweenProgressUpdates 10.0 --help false --version false --VERBOSITY INFO --QUIET false
[October 24, 2015 2:16:18 AM EDT] Executing as akiezun@dataflow01.broadinstitute.org on Linux 2.6.32-573.3.1.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0-b132; Version: Version:4.pre-alpha-45-g168cd60-SNAPSHOT JdkDeflater
02:16:18.972 INFO  CountReads - Initializing engine
02:16:19.296 INFO  IntervalArgumentCollection - Processing 20000000 bp from intervals
02:16:19.300 INFO  ReadsDataSource - Preparing intervals for traversal
02:16:19.301 INFO  CountReads - Done initializing engine
02:16:19.301 INFO  ProgressMeter - Starting traversal
02:16:19.302 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
02:16:29.306 INFO  ProgressMeter -            1:3034965              0.2               2219000       13310007.0
02:16:39.306 INFO  ProgressMeter -             unmapped              0.3               4542000       13623275.3
```

**Comment by droazen** [comment] 2015-11-02 15:30
I think this is by design (the reader intentionally keeps unmapped reads that have mapped mates). We might want to reconsider this behavior and just filter out all unmapped reads, but then we won't be able to match the old test outputs.

The progress meter, of course, just prints out the locus for whatever read happens to be around when its polling interval is up, and this may occasionally happen to be an unmapped read.

**Comment by akiezun** [comment] 2015-12-09 15:44
hmm this is not a spark issue i think. got mislabeled somehow

**Comment by droazen** [comment] 2015-12-09 15:45
This is by design -- can we close this as invalid?

**Comment by droazen** [comment] 2016-01-05 21:57
Replaced by https://github.com/broadinstitute/gatk/issues/1408. Closing

**Closed by droazen** 2016-01-05 21:57 UTC
Labels: Engine
