### ISSUE TITLE
Unrecognized runtime attribute keys: discs, cpu (ReadsPipelineSparkMulticore.wdl)

### ISSUE THREAD

**Issue by Aqoolare** [broadinstitute/gatk#7796] opened 2022-04-20 11:21 UTC
Hello again, I have not been able to solve the problem with the launch ReadsPipelineSparkMulticore.wdl. :(
![qoKs8pEt_-0](https://user-images.githubusercontent.com/55628707/161521914-49b7b10f-3264-43d5-8f5c-739d924656a1.jpg)
I use this command:
`java -jar ../cromwell-77.jar run ReadsPipelineSparkMulticore.wdl -i exome/ReadsPiplineSpark_exome.json`
This is my json file:
![qo2S-PSVs_xNXb5ZysWT8g](https://user-images.githubusercontent.com/55628707/164080985-ae983a19-104a-4742-9401-82ea938ef69e.jpeg)
Here is my configuration (CPU and RAM):
![PEP_IbcPaXyZtql0oefE_A](https://user-images.githubusercontent.com/55628707/164081131-58958f86-5aaf-450f-b985-d7885d4a8de4.jpeg)
![FDmF-6wr4RelT11qqByfGA](https://user-images.githubusercontent.com/55628707/164081137-2d07fe83-845e-463e-ab17-7a5cecb415e0.jpeg)

Found this error in my stderr file:
22/04/06 15:36:17 ERROR Executor: Exception in task 10.0 in stage 11.0 (TID 1596)
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine.calculateFractionalErrorArray(BaseRecalibrationEngine.java:440)
	at org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine.processRead(BaseRecalibrationEngine.java:141)
	at org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn.lambda$null$0(BaseRecalibratorSparkFn.java:33)
	at org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn$$Lambda$705/136574652.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at org.broadinstitute.hellbender.utils.iterators.CloseAtEndIterator.forEachRemaining(CloseAtEndIterator.java:47)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn.lambda$apply$6ed74b3e$1(BaseRecalibratorSparkFn.java:33)
	at org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn$$Lambda$635/777640102.call(Unknown Source)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:823)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:823)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I will be greateful for your help

**Comment by lbergelson** [comment] 2022-04-25 18:42
@Aqoolare Hello.   There are a a few things going on here.

The `unrecognized runtime attribute keys` warning is coming from cromwell.  It's telling you that the cromwell **local** backend doesn't understand those keys, which is true.  That means it's just ignoring them.

I think the actual problem is different though.  You're running the spark tool in spark local mode, which in this case isn't configured to use the correct amount of cores or memory.   I think the intent of this wdl script was that it would be run in a container on a cluster and the container would restrict the cores and memory options.  In any case, it's not configured correctly for what you need.

I would skip running cromwell and just invoke gatk directly since this wdl only executes a single job.   Since this is going to run spark in local mode you need to specify the number of cores using the `--spark-master` argument, and set the memory using the `--java-options "-Xmx"` arguments.

For example:

```
gatk ReadsPipelineSpark 
    --java-options "-Xmx16G" 
    --spark-master 'local[8]'
    --I yourbam.
    ... etc
```

The above command is specifying to use 8 (that's what the local[**8**] means) cores for spark and give it 16G of memory.   Your job was accidentally using 200 cores so it doesn't surprise me that it would run into memory issues.   Using spark with more than 16ish cores in a single process is going to bog down a lot. I think 8 is a good starting place to try.  If you want to go wider you should really look into running a proper cluster (or using dataproc), but there's pretty heavy diminishing returns.  Try 8 or 16 and tune the memory from there.

**Comment by Aqoolare** [comment] 2022-04-27 10:05
@lbergelson Thank you very much for your response.
Using the Java argument -Xmx really helped to solve "java.lang.OutOfMemoryError" problem.
Also, I would like to ask why it happens that when I increase the number of threads and RAM from 45/90 to 180/360, I do not get a gain in time?

**Comment by lbergelson** [comment] 2022-04-27 20:54
@Aqoolare You might, but there are scaling issues when running within a single java process which is what you're doing.  There are issues with lock contention and garbage collection which cause more cores to not be utilized very well.  (Lots of cores waiting while garbage collection stops the world, that sort of thing.). 

You could definitely test it.  We found that 8-16 cores was optimal for our use cases for running in spark local mode, but spark performance is extremely finicky and it's very possible your system might do better than what I'm used to. If you wantt to go very parallel it works better to run an actual spark cluster.  You should be able to utilize cores more efficiently that way, but it's more complicated to set up and operatte and there are still bottlenecks that keep it from being infinitely scaleable.  (IO bandwidth and network traffic being important ones).  

There are lots of articles on the internet about how to set up a local yarn cluster that can help walk you through it if you want to try.  

I'm going to close this ticket since it seems like the problem is solved.  Feel free to reopen or open a new one if you have other issues.

**Closed by lbergelson** 2022-04-27 20:54 UTC
