### ISSUE TITLE
ASEReadCounter outputs only header

### ISSUE THREAD

**Issue by chunyangbao** [broadinstitute/gatk#7314] opened 2021-06-15 02:17 UTC
I am using ASEReadCounter to call allelic read counts on 1000 genome reference. But, I found ASEReadCounter generatd only header in output file. Here I enclosed my command and stderr log. Please help me to check it. Thank you!

If you are seeing an error, please provide(REQUIRED) :
a) GATK version used: 4.1.8.1
b) Exact command used:

java -Xmx8000m -Djava.io.tmpdir=/broad/hptmp/cbao \
 -jar ${path2gatk}/gatk-package-4.1.8.1-local.jar \
 ASEReadCounter \
 -L scattered.interval_list \
 -R Homo_sapiens_assembly19.fasta \
 -V 1000G_phase1.snps.high_confidence.b37.vcf.gz \
 -I downsample_10k.bam \
 -O output.txt --verbosity INFO 

c) Entire error log:
19:13:25.991 INFO NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/broad/software/free/Linux/redhat_7_x86_64/pkgs/gatk_4.1.8.1/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jun 14, 2021 7:13:26 PM shaded.cloud_nio.com.google.auth.oauth2.DefaultCredentialsProvider warnAboutProblematicCredentials
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
19:13:26.217 INFO ASEReadCounter - ------------------------------------------------------------
19:13:26.218 INFO ASEReadCounter - The Genome Analysis Toolkit (GATK) v4.1.8.1
19:13:26.218 INFO ASEReadCounter - For support and documentation go to https://software.broadinstitute.org/gatk/
19:13:26.219 INFO ASEReadCounter - Executing as cbao@uger-c009.broadinstitute.org on Linux v3.10.0-1160.15.2.el7.x86_64 amd64
19:13:26.219 INFO ASEReadCounter - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_181-b13
19:13:26.219 INFO ASEReadCounter - Start Date/Time: June 14, 2021 7:13:25 PM UTC
19:13:26.219 INFO ASEReadCounter - ------------------------------------------------------------
19:13:26.219 INFO ASEReadCounter - ------------------------------------------------------------
19:13:26.220 INFO ASEReadCounter - HTSJDK Version: 2.23.0
19:13:26.220 INFO ASEReadCounter - Picard Version: 2.22.8
19:13:26.220 INFO ASEReadCounter - HTSJDK Defaults.COMPRESSION_LEVEL : 2
19:13:26.220 INFO ASEReadCounter - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
19:13:26.220 INFO ASEReadCounter - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
19:13:26.220 INFO ASEReadCounter - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
19:13:26.220 INFO ASEReadCounter - Deflater: IntelDeflater
19:13:26.220 INFO ASEReadCounter - Inflater: IntelInflater
19:13:26.220 INFO ASEReadCounter - GCS max retries/reopens: 20
19:13:26.221 INFO ASEReadCounter - Requester pays: disabled
19:13:26.221 INFO ASEReadCounter - Initializing engine
19:13:26.663 INFO FeatureManager - Using codec VCFCodec to read file file:///cga/bass/Chunyang/ref/hg19/1000G_phase1.snps.high_confidence.b37.vcf.gz
19:13:26.818 INFO FeatureManager - Using codec IntervalListCodec to read file file:///cga/bass/Chunyang/ref/hg19/gatk_b37.scattered_wgs_intervals/scatter-50/temp_0001_of_50/scattered.interval_list
19:13:26.831 INFO IntervalArgumentCollection - Processing 29268134 bp from intervals
19:13:26.834 WARN IndexUtils - Feature file "/cga/bass/Chunyang/ref/hg19/1000G_phase1.snps.high_confidence.b37.vcf.gz" appears to contain no sequence dictionary. Attempting to retrieve a sequence dictionary from the associated index file
19:13:26.973 INFO ASEReadCounter - Done initializing engine
19:13:26.977 INFO ProgressMeter - Starting traversal
19:13:26.977 INFO ProgressMeter - Current Locus Elapsed Minutes Loci Processed Loci/Minute
19:13:27.118 WARN ASEReadCounter - Ignoring site: variant is not het at postion: 1:835092
19:13:27.118 WARN ASEReadCounter - Ignoring site: variant is not het at postion: 1:835132
19:13:27.118 WARN ASEReadCounter - Ignoring site: variant is not het at postion: 1:835133
... 
...
...
19:13:28.229 WARN ASEReadCounter - Ignoring site: variant is not het at postion: 1:29617944
19:13:28.230 WARN ASEReadCounter - Ignoring site: variant is not het at postion: 1:29618025
19:13:28.231 INFO ASEReadCounter - 0 read(s) filtered by: ValidAlignmentStartReadFilter
0 read(s) filtered by: ValidAlignmentEndReadFilter
0 read(s) filtered by: HasReadGroupReadFilter
0 read(s) filtered by: MatchingBasesAndQualsReadFilter
0 read(s) filtered by: SeqIsStoredReadFilter
51 read(s) filtered by: NotDuplicateReadFilter
63 read(s) filtered by: NotSecondaryAlignmentReadFilter
3 read(s) filtered by: MappedReadFilter
117 total reads filtered
19:13:28.231 INFO ProgressMeter - 1:29618022 0.0 110019 5264067.0
19:13:28.231 INFO ProgressMeter - Traversal complete. Processed 110019 total loci in 0.0 minutes.
19:13:28.233 INFO ASEReadCounter - Shutting down engine
[June 14, 2021 7:13:28 PM UTC] org.broadinstitute.hellbender.tools.walkers.rnaseq.ASEReadCounter done. Elapsed time: 0.04 minutes.
Runtime.totalMemory()=2303197184
 
 

output.txt:

contig position variantID refAllele altAllele refCount altCount totalCount lowMAPQDepth lowBaseQDepth rawDepth otherBases improperPairs

 

Thanks for your help!

Chunyang

**Comment by jamesemery** [comment] 2021-06-22 21:16
This has been fixed. Duplicate of #7327.

**Closed by jamesemery** 2021-06-22 21:16 UTC
