### ISSUE TITLE
ApplyRecalibration -> ApplyRecalibration produces no variants when using .vcf.gz output

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/gatk#2795] opened 2017-06-01 18:53 UTC
If I run ApplyRecalibration twice in a chain (the first for indel recalibration, the second for snp recalibration) the final resulting vcf only has a header.

IF the output of the first ApplyRecalibration is a .vcf.gz, this occurs.  IF I change that to be a .vcf instead (non-compressed) this does not happen.

It seems like something either in the compression out of ApplyRecalibration or the decompression into the second ApplyRecalibration is broken

**Comment by droazen** [comment] 2017-06-02 13:20
@kcibul Have you determined that the issue here was actually in the index creation step, and that the bug is that `IndexFeatureFile` was generating a bad tabix index?

**Comment by droazen** [comment] 2017-06-02 13:47
Opened https://github.com/broadinstitute/gatk/issues/2801

**Comment by droazen** [comment] 2017-06-02 14:19
Closing -- this is actually caused by https://github.com/broadinstitute/gatk/issues/2801

**Closed by droazen** 2017-06-02 14:19 UTC
Labels: bug, PRIORITY_HIGH
