### ISSUE TITLE
Find a way to avoid shipping the Sam header around in Spark

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/gatk#900] opened 2015-09-17 00:04 UTC
This is meant as a group discussion that could happen several places, and here is as good as any.

We know that shipping around the header is has a *huge* cost. So, we need to find a way to effectively strip it from the `SAMRecord` without breaking it. I propose the following.
* Modify `SAMRecord` to use getter methods for the header
* Create a `HeaderSAMRecord` that extends `SAMRecord` and that has a static field for the header. This class would override `getHeader` to return the static
* Use `Broadcast` with `mapPartitions` to set the static on each worker

An alternative would be audit the field usage and do a combination of performing all necessary calls that require the header to when we load the reads and, if possible, making the still offending methods inaccessible.

So, @tomwhite , @akiezun , @droazen , @lbergelson , @jean-philippe-martin , what do you all think?

I know @lbergelson previous expressed he didn't like the usage of statics for this purpose.

**Comment by jean-philippe-martin** [comment] 2015-09-17 00:09
The problem with a static member is that then we can only have one header for every read, ever. This will probably break computations that handle more than one bam at a time.

Another potential solution is to audit every Dataflow (and spark) code that can receive SAMRecords as input, and make sure they call some utility "putHeadersBack" function. There aren't so many of those so it would be possible, though not super-pleasant.

**Comment by jean-philippe-martin** [comment] 2015-09-17 00:11
And to put it on the table, another option is to give the header to the deserializer (aka "coder"), so it can put it back as it reads in the objects. This can be a little delicate, though, when there's more than one header in play as we have to manually specify the "right" decoder every time. This is definitely less pleasant than just registering one coder and being done with it.

**Comment by jean-philippe-martin** [comment] 2015-09-17 00:20
Oh, and to add: I'm not too worried about having to put the header back in because that's what I'm doing right now anyways.

**Comment by akiezun** [comment] 2015-09-17 02:31
what's [ADAM's](https://github.com/bigdatagenomics/adam) approach to this?

**Comment by laserson** [comment] 2015-09-17 07:22
ADAM has no header.  I realize I'm only coming into the game rather late, but would it be possible to ditch `SAMRecord`?  Since you're already using Google `Read`-backed data as well, instead of writing against an interface (`GATKRead`), you could simply come up with your own, more-awesome concrete data structure.  (Perhaps even an Avro `SpecificRecord` a la `AlignmentRecord`).  In cases where ADAM wants a header back, at the moment it actually runs an aggregation across all the reads to rebuild it.  (I'm trying to add a patch that allows you to specify a header, though, because it's breaking a hellbender test for reading/writing parquet.)

**Comment by tomwhite** [comment] 2015-09-17 08:30
> Another potential solution is to audit every Dataflow (and spark) code that can receive SAMRecords as input, and make sure they call some utility "putHeadersBack" function.

I agree. I think this is the most practical solution. (Having the coder/serializer do it is difficult, as it's hard to get the header to the serializer, unless it is passed statically, which I think we'd rather avoid.)

This would look something like `reads.map(read -> ReadUtils.addHeader(header, read))`, and would be added after every shuffle. Since we should be very aware where every shuffle is happening (and we want to minimize their number) it shouldn't be too onerous.

The other related point that Uri has touched on is the need for an efficient encoding of reads (even without the header), which is critical to making the computations run in a reasonable amount of time. The approach I've taken in https://github.com/broadinstitute/hellbender/pull/899 is to use the htsjdk BAMEncoder to serialize reads (Hadoop-BAM does something very similar), and it works very well in my tests of sorting large BAMs.

Does https://github.com/broadinstitute/hellbender/pull/899 plus "putHeadersBack" sound like a reasonable solution?

**Comment by davidadamsphd** [comment] 2015-09-17 13:30
@laserson the `SAMRecord` vs. Google `Read` is a loooooong story.
The super-short version:
We had a bunch of utilities written for `SAMRecord` that @droazen refactored over months to take the GATKRead interface. As it happens, the SAM spec and the GA4GH spec are not 100% compatible. So, it's not possible to losslessly convert from A -> B -> A (where A is `SAMRecord` or Google `Read`). The cases where it doesn't work are edge cases, but they exist.

Second, @jean-philippe-martin found that converting to Google `Read` was fairly expensive. Between those two points, I think we're probably better off with SAM-backed reads. (Also, right now the Google `Read` is serialized via JSON, so it's not that small anyway.)


@tomwhite and @jean-philippe-martin, I think adding the header back will be fine for us engineers working on the engine, but it will make for a poorer user experience for newcomers and Comp Bios to burden them with having to care about what happens with shuffles (when they just want to prototype something). 

That said, I think this is probably the best approach we have at our disposal. If we do, we need to do an excellent job of throwing errors if users try to perform actions that would require the header. The error message should explain what really happened and ideally point to some documentation we write explaining the stripping of the header and how to fix it. If this error occurs, it needs to be simple for anyone to fix it.

 @droazen @lbergelson, what do you two think? (also @laserson, do you have any ideas or thoughts on the header since we're probably stuck with `SAMRecord`?)

**Comment by lbergelson** [comment] 2015-09-17 14:41
I think all of our dataflow / spark code is at least almost entirely using `GATKRead`.  GATKRead is designed to not provide access to the header because it's not available from a google `Read` backed `GATKRead`.  It sounds like there is some information that `Read` includes that is missing from a headerless `SAMRecord`.  I think we could audit the `SAMRecordToGATKReadAdaptor` to find any places it touches the header and then cache that information in the adaptor before stripping the header.   We don't need to add back in the headers at any point, because we provide library functions to perform any header related operation with a provided header.

**Comment by davidadamsphd** [comment] 2015-09-17 15:30
Audit results, there are two (very related issues).
Issue (1)
`setPosition` from `SAMRecordToGATKReadAdapter` calls `setReferenceName` from `SAMRecord`

```
    public void setReferenceName(final String value) {
        /* String.intern() is surprisingly expensive, so avoid it by looking up in sequence dictionary if possible */
        if (NO_ALIGNMENT_REFERENCE_NAME.equals(value)) {
            mReferenceName = NO_ALIGNMENT_REFERENCE_NAME;
            mReferenceIndex = NO_ALIGNMENT_REFERENCE_INDEX;
            return;
        } else if (mHeader != null) {
            final int referenceIndex = mHeader.getSequenceIndex(value);
            if (referenceIndex != -1) {
                setReferenceIndex(referenceIndex);
                return;
            }
        }
        // Drop through from above if nothing done.
        mReferenceName = value.intern();
        mReferenceIndex = null;
    }
```
Issue (2)
`setMatePosition`  from `SAMRecordToGATKReadAdapter` calls `setMateReferenceName` from `SAMRecord`

```
    public void setMateReferenceName(final String mateReferenceName) {
        /* String.intern() is surprisingly expensive, so avoid it by looking up in sequence dictionary if possible */
        if (NO_ALIGNMENT_REFERENCE_NAME.equals(mateReferenceName)) {
            mMateReferenceName = NO_ALIGNMENT_REFERENCE_NAME;
            mMateReferenceIndex = NO_ALIGNMENT_REFERENCE_INDEX;
            return;
        } else if (mHeader != null) {
            final int referenceIndex = mHeader.getSequenceIndex(mateReferenceName);
            if (referenceIndex != -1) {
                setMateReferenceIndex(referenceIndex);
                return;
            }
        }
        // Drop through from above if nothing done.
        this.mMateReferenceName = mateReferenceName.intern();
        mMateReferenceIndex = null;
    }
```

@lbergelson, what's the fix?

**Comment by tomwhite** [comment] 2015-09-17 16:42
Something like LazyBAMRecord in https://github.com/broadinstitute/hellbender/pull/899/files?

**Comment by droazen** [comment] 2015-09-17 16:58
@jean-philippe-martin I don't think we have to worry about the case of multiple headers for the reads. The GATK has always taken the approach of requiring compatibility between the various reads headers, and then merging them into a single header. 

Given this, is it at all feasible to handle this at the coder level (stripping the header on encode and restoring on decode)? If it is, I think that is the best solution. Requiring client code to manually put the header back is onerous and error-prone, and shipping around headerless `SAMRecord` objects is likely to be an ongoing source of headaches, as the class is really designed on the assumption that a header is present.

**Comment by jean-philippe-martin** [comment] 2015-09-17 17:04
on **data representation**:

@laserson: yes, I think it makes total sense to eventually move to a better format. The requirements seem to be: (a) efficient serialization/deserialization, and (b) can easily convert to a SAMRecord for compatibility with existing code. We can make things extra efficient by only deserializing things if they are needed (if a phase doesn't need the CIGAR-related structures, no need to deserialize that). We can achieve this by having the deserialization be lazy. The LazyBAMRecord is a step in that direction since it looks up the reference name only if we ask for it, but we could go a lot further in this direction.

But before we do that, having an efficient coder for SAMRecords (I vote for @tomwhite's approach of using the BAMEncoder) will get us 80% of the way for 20% of the effort. Then we can introduce our OptimizedSAMRecord incrementally. 

on **headers**:

I agree with @tomwhite that adding the header back after a shuffle is the right thing to do. We know where that happens and we control that code.
@davidadamsphd, you worry about newcomers. But we've already decided that we were going to provide our own API for them (one that does the Dataflow copying for them so they don't have to worry about it). This same API will provide them with header-filled reads, so they don't have to worry about this detail. This falls into the general category of "the 3rd party devs won't have to even know about Dataflow/Spark: they just need to know our nice, simple interface and use that". If they know more and want to do fancier things then more power to them, but those users will surely be able to fill in headers, too.

We have library functions to use the reads without the headers, but the problem is that (at least for the sort of code I'm writing), I'm handing off a SAMRecord to a big black box and I can't force it to use the library functions - it's going to work on the SAMRecord directly. So at least in this case it's important to fill in the header (unless I happen to know that the "black box" won't call any of the header-requiring methods).

**Comment by laserson** [comment] 2015-09-17 17:15
+1 to @lbergelson's point.  It seems the header is really only involved when reading or writing a bam file.  Would be great to eliminate it entirely except on the "external interface" when writing files.

**Comment by jean-philippe-martin** [comment] 2015-09-17 17:15
@droazen, if it's true we can merge the headers then I suppose that may be a possibility. I'm a little bit dubious, though, because one of the pieces of information is the reference index to reference name mapping, and I didn't think we required those to match. Or do we?

Keep in mind however that static variables aren't serialized, so we'd still have to include some fancy code to make sure that every worker has the header. And since workers may be added dynamically by Dataflow's auto-tuning, we may have to call that code at the beginning of every transform... just like addHeaders. 

So we would have some "action-at-a-distance" type of code, with statics that may or may not have different values depending on which computer you're on. This sounds like it may be just as error-prone and headache-causing as the other approach.

At this point I'm still leaning towards manually putting the headers back. I think this makes the code less surprising than using globals (statics are a form of global variable after all) and so less likely to confuse someone new to the codebase.

**Comment by davidadamsphd** [comment] 2015-09-17 18:26
@jean-philippe-martin, we want to expose a walker-like interface, but we also care about the general ease of writing programs using the tools we and the user wrote (in native Dataflow/Spark). This is a point that @droazen, has emphasized to me several times. I'll let him add more detail on this if needed.

I agree that the static approach won't work for Dataflow when workers are added, but I think I have a solution for Spark that works even when workers are added.
We'd create a new class (like I suggested above), but this would have a `Broadcast<SAMFileHeader>`, which is basically a lazy-loader for headers. We'd only load the header when needed.
I think this may be the best of all solution as it could also support several headers.

**Comment by droazen** [comment] 2015-09-17 20:28
@davidadamsphd, @lbergelson, and myself met for an hour or two just now to discuss this issue, and after reviewing all the options I think we were convinced by the following argument:

The `SAMRecord` class currently allows its header to be set to null, so if there are cases where the class won't function properly or can enter into an inconsistent state when a header is not present these should be treated as bugs and patched, and we should add unit tests to htsjdk to prove that headerless `SAMRecords` function properly. Then in hellbender we can freely use headerless `SAMRecords` everywhere, only restoring the header to the record when writing out the final bam (since our bam writers do require that a header be present in the records, I believe). 

I've created https://github.com/broadinstitute/hellbender/issues/903 to make the necessary changes in htsjdk, and assigned it to @cmnbroad. He said he could get to it early next week. What do you guys think of this approach to the problem?

**Comment by jean-philippe-martin** [comment] 2015-09-17 21:40
@droazen a headerless SAMRecord would be convenient, for sure. They would be less efficient  because we need to copy the contig and mate contig names onto every read but perhaps that cost is worth it to you. 

There is a risk we may re-introduce something like the header when we move to more efficient versions of SAMRecord.

**Comment by droazen** [comment] 2015-09-17 21:51
@jean-philippe-martin The idea is that you **wouldn't** have to copy the contig and mate contig indices into every read. The SAMRecord class would be modified as needed to function correctly when no contig index information is available in the absence of a header (ie., only names are known).

**Comment by jean-philippe-martin** [comment] 2015-09-17 22:14
@droazen, the SAMRecord interface exposes getReferenceIndex and getMateReferenceIndex, so there is no question that the index has to be there. 

What I was talking about what the optimization where when serializing, the [BAMRecordCodec only saves the index](https://github.com/samtools/htsjdk/blob/master/src/java/htsjdk/samtools/BAMRecordCodec.java#L131), and not the name. That is because if we have the header then we can go from the index to the name.

If there is no header, then we can't do that optimization anymore and instead have to save those two fields for every read.

**Comment by droazen** [comment] 2015-09-17 23:04
@jean-philippe-martin I disagree that just because there are getters for the index, the index has to be there. It is already allowed to be absent for various reasons (via the special value `NO_ALIGNMENT_REFERENCE_INDEX`). Since use of the index instead of the name is mostly a performance optimization, I think we can get away with allowing records that have the name filled in but not the index.

Relying on contig indices in general is a bad idea, as they are quite brittle, particularly when querying data from multiple sources. We purposefully moved away from using the indices in hellbender in favor of names when we migrated from `GenomeLoc` to `SimpleInterval`, and are, I think, willing to pay the extra cost of string parsing to avoid the subtle bugs that historically resulted from relying on the indices. This is a micro-optimization that probably isn't worth pursuing.

**Comment by droazen** [comment] 2015-09-17 23:04
@jean-philippe-martin I disagree that just because there are getters for the index, the index has to be there. It is already allowed to be absent for various reasons (via the special value `NO_ALIGNMENT_REFERENCE_INDEX`). Since use of the index instead of the name is mostly a performance optimization, I think we can get away with allowing records that have the name filled in but not the index.

Relying on contig indices in general is a bad idea, as they are quite brittle, particularly when querying data from multiple sources. We purposefully moved away from using the indices in hellbender in favor of names when we migrated from `GenomeLoc` to `SimpleInterval`, and are, I think, willing to pay the extra cost of string parsing to avoid the subtle bugs that historically resulted from relying on the indices. This is a micro-optimization that probably isn't worth pursuing.

**Comment by jean-philippe-martin** [comment] 2015-09-18 00:03
@droazen ok, good point, if you know the code will keep on working without the index then we can indeed remove it. Just for the record I wasn't saying this was a reason not to do it, I was just pointing it out since there was no mention of the cost.

**Comment by davidadamsphd** [comment] 2015-09-18 00:21
I'll wait for @laserson and @tomwhite to get a chance to chime in, but it looks like we have plan.

Supposing that it takes @cmnbroad two weeks (which seems like a reasonable estimate to me). We should we do in the mean time? Is there something simple we can do (that's hacky but correct) to hold us over until the real fix is in?
@tomwhite's suggestion of stripping the header before shuffles, then adding it back after sounds OK to me (and should be easy to clean up).
Other thoughts?

**Comment by jean-philippe-martin** [comment] 2015-09-18 00:30
@davidadamsphd stripping the header helps, but also encoding to BAM helps more. I expect to be using the LazeBAMRecordFactory that @tomwhite wrote.

**Comment by laserson** [comment] 2015-09-18 02:23
Sounds like a reasonable strategy to me.  WRT to the performance costs, it sounds like @tomwhite's serialization changes would be a much bigger benefit than the cost of having to serialize the reference names.

**Comment by tomwhite** [comment] 2015-09-18 11:37
Sounds good to me.

**Comment by bhandsaker** [comment] 2015-09-18 13:28
Since you asked, I have a couple of thoughts:

First, I don't know if allowing the SAMRecord header to be set to null 
something that was intended to be widely used, or whether it was an 
oversight in the API or done to solve some particular corner case.  If 
many SAMRecord methods appear to be broken if the header is null, then 
perhaps this isn't something that was intended for wide use.

Second, it sounds like the suggestion is that headerless SAMRecords 
would now be widely used, and thus a common thing that people writing 
code against htsjdk need to anticipate.
So if you go this way you should update the SAMRecord documentation to 
clearly indicate that SAMRecords can be in either a headerless or 
non-headerless (headerful?) state
and indicate how each API function is affected by this.  If certain 
methods behave differently, then people writing code against SAMRecord 
need to anticipate this
and existing code may need to be updated.  In other words, headerless 
SAMRecords should become "part of the spec".

Third, although I don't know in detail about the different execution 
environments you are trying to support, there is a general strategy that 
I haven't seen discussed in these threads.
Perhaps it's impractical, but I'll mention it anyway.  It seems like 
another approach would be to create (internal to the implementation) a 
"header tag" that could be efficiently serialized
and passed as part of the SAMRecord when you need to distribute it. The 
header tag could be used by the receiver to reattach the SAMRecord to 
its header (either proactively or on demand), but transparently to 
application code that is running against the SAMRecord API.
This would allow SAM headers to be transmitted out-of-band in a way that 
depends on the execution environment.  Depending on the environment, 
this might be done by proactive broadcast, or you could think of the 
header tag as a promise to retrieve the header if/when it is needed.  
The size and complexity of the header tag might also depend on the 
execution environment. If the execution environment only supports a 
small finite number of headers, the header tag could be a small integer, 
or in a different execution environment it could be
a unique hash of the header or something like that. Memory footprint in 
the receiver is minimized because many SAMRecords can all share the same 
header object.
This requires more work to support in each execution environment, but it 
seems like it could be efficient and allows application code written to 
operate on SAMRecords to be portable
across different execution environments without having to contend with 
the possible presence of headerless SAMRecords.

-Bob

**Comment by droazen** [comment] 2015-09-21 15:42
@bhandsaker Thanks for chiming in with your thoughts/concerns.

Under this proposal, the various classes in htsjdk that read and return `SAMRecords` (eg., `SAMReader` & co.) would continue to put the header inside of the records, so we would not be imposing an additional burden on direct clients of htsjdk to check for null headers any more than they do currently. The only difference is that if downstream consumers of `SAMRecords` (like hellbender) choose to strip the header from the records, there would be an explicit contract governing the behavior of headerless `SAMRecords` (as opposed to the status quo, in which the header may be null but behavior is totally undocumented and in some cases inconsistent -- eg., the reference name and index in a headerless `SAMRecord` can get out-of-sync in some cases). 

In additional to documenting/clarifying the behavior of headerless `SAMRecords` and fixing any consistency-related bugs we find when operating without a header, we would also make an effort to document when a class in htsjdk that consumes `SAMRecords` requires that a header be present in the records (such as the various writer classes).

Does this sound reasonable? It's actually a much more conservative proposal than it may have initially sounded :)

**Comment by bhandsaker** [comment] 2015-09-22 20:02
Thanks for the explanation.

It isn't clear to me that the SAMRecord API was ever intended to support 
headerless records (except maybe in very rare corner cases).

I don't really know the scope of hellbender.  If it is just for internal 
DSDE tools development, then I guess it doesn't matter.
If you ever want to leverage code/libraries from elsewhere, then those 
would have to be "headerless-aware", I guess.

For example, a common operation in Genome STRiP is to ask for the sample 
associated with a read.  This requires the header, I would think.
Anyway, my main point was just to stimulate thinking about the value of 
implementing an efficient way to transmit the headers.
It also seems to me that this generalizes to efficient patterns to 
transmit any widely shared data (that is referenced by many serialized 
individual data items) out-of-band.

-Bob

**Comment by droazen** [comment] 2015-09-22 20:28
@bhandsaker In hellbender we do already ship the header around "out-of-band" much as you described (via the spark broadcast mechanism and the dataflow "side input" mechanism), and use that header singleton for operations such as looking up the sample, library, platform, etc. We wrote utility methods in hellbender that take both a read and a separate header for all operations that previously required a header within the read, to avoid having to actually restore the header into the reads themselves after every operation that involves a shuffle over the network.

Our goal is just to ensure that `SAMRecord` behaves in a consistent, well-documented way when it lacks a header without imposing any additional burden on other users of htsjdk. The only code that would have to be "headerless-aware" as a result of this effort would be code that has explicitly opted-in to stripping the headers (eg., hellbender itself, or projects that depend on hellbender).

**Comment by droazen** [comment] 2015-11-20 16:01
This is solved -- @cmnbroad patched htsjdk to make using headerless reads directly safer, we modified `ReadsSparkSource` to null out headers, and @tomwhite implemented a custom serializer based on the BAM codec that is both fast and safe for headerless reads.

**Closed by droazen** 2015-11-20 16:01 UTC
Labels: Spark
