### ISSUE TITLE
CRAM writing in hellbender has issues with unmapped reads

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#766] opened 2015-07-29 17:44 UTC
It appears that when we try to write out a CRAM file in hellbender from input that contains an unmapped read, we produce a malformed CRAM. We need to fix this before we can write the tests in https://github.com/broadinstitute/hellbender/issues/675 and https://github.com/broadinstitute/hellbender/issues/590

To replicate, take a BAM file containing an unmapped read (eg., `src/test/resources/org/broadinstitute/hellbender/tools/print_reads.bam`), run it through hellbender's `PrintReads` with the output set to cram, then run `samtools view` on the resulting cram file.

**Comment by droazen** [comment] 2015-07-29 17:45
Prerequisite for https://github.com/broadinstitute/hellbender/issues/675 and https://github.com/broadinstitute/hellbender/issues/590

**Comment by akiezun** [comment] 2015-09-03 21:04
@droazen please feel free to close if this is done

**Comment by cmnbroad** [comment] 2015-10-07 20:16
The output cram is malformed because because the cram writer code in htsjdk assumes it has a reference source for the output, but in this case it doesn't. It throws an NPE when it tries to access the reference bases. We need fixes and to tighten up code in several places in both htsjdk and HB. I'll add/update tickets accordingly.

**Comment by cmnbroad** [comment] 2015-11-17 21:29
I don't think we have any remaining issues or constraints with unmapped reads at this point. The issue above was caused by not having a reference for the CRAM output .The other place you can get into trouble in some cases is with sort order (see https://github.com/samtools/htsjdk/issues/365) but there is a fix in PR https://github.com/samtools/htsjdk/pull/368 for that.

Between PR https://github.com/broadinstitute/gatk/pull/1084  (MergeBamAlignmentIntegrationTest) and SamFormatConverterIntegrationTest, we now have tests that both read and write CRAMs with unmapped reads 
 .

**Comment by akiezun** [comment] 2015-11-25 16:07
@cmnbroad can this be closed?

**Comment by cmnbroad** [comment] 2015-11-25 16:10
I'd like to leave it open until we get the fixes to #365 and add a test then that verifies that. However, I don't think this needs to be for alpha.

**Comment by akiezun** [comment] 2015-11-25 16:13
ok then

**Comment by cmnbroad** [comment] 2015-12-07 13:06
The tests for writing unmapped reads are reenabled now, closing via #1255.

**Closed by cmnbroad** 2015-12-07 13:06 UTC
Labels: bug, Engine
