### ISSUE TITLE
Investigate nonlinear alternatives to tangent normalization

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2830] opened 2017-06-05 15:41 UTC
@davidbenjamin commented on [Sat Dec 19 2015](https://github.com/broadinstitute/gatk-protected/issues/260)

We use (linear) PCA to map the PoN, each datum of which is a high-dimensional vector over targets, to a low-dimensional manifold.  Do we really believe that this manifold is simply a hyperplane?

Concretely, suppose the data really lives on a 4-dimensional curved manifold.  Due to the curvature, we might require many more, say 20, flat dimensions to encompass a significant amount of the PoN's variance.  What this means is that we lump a huge amount of noise in with the true signal.

Non-linear alternatives worth investigating include kernel PCA -- nice because like all machine learning things involving the kernel trick you get to recycle almost all of your mathematical and algorithmic machinery, denoising autoencoders, and Gaussian process latent variable models.

---

@davidbenjamin commented on [Wed Dec 23 2015](https://github.com/broadinstitute/gatk-protected/issues/260#issuecomment-166804219)

Linear PCA could be sufficient if the PoN samples are tightly clustered about their mean so that variance is a small perturbation that can be treated linearly.  I don't think we know enough about PoNs to judge what actually occurs.

**Comment by samuelklee** [comment] 2017-10-11 14:56
Calling this a dupe of #3319.

**Closed by samuelklee** 2017-10-11 14:56 UTC
Labels: Copy Number tools, question
