### ISSUE TITLE
Some concerns about the Mutect2 WDL pipeline 

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3061] opened 2017-06-07 18:40 UTC
For discussion with @davidbenjamin. Conversation will benefit Mutect2 workflow documentation.

The Mutect2 WDL pipeline at <https://github.com/broadinstitute/gatk/blob/master/scripts/mutect2_wdl/mutect2.wdl> uses the following:

1. SplitIntervals in default mode (clarified in #3032 that default INTERVAL_SUBDIVISION mode can cut into an interval in the intervals list)
    ```
     java -jar $GATK_JAR SplitIntervals -R ${ref_fasta} ${"-L " + intervals} -scatter ${scatter_count} -O interval-files
    cp interval-files/*.intervals .
    ```
2. Scatter Mutect2 over files of intervals
    ```
    scatter (subintervals in SplitIntervals.interval_files ) {
    call M2 {
    ```
3. MergeVCFs to collate the resulting VCF callsets
    ```
    java -Xmx2g -jar $GATK_JAR MergeVcfs -I ${sep=' -I ' input_vcfs} -O ${output_vcf_name}.vcf
    ```

Assuming Mutect2 handles active regions in the same manner as HaplotypeCaller, which will expand/pad active regions, then a consequence of the current workflow is potential _duplicate calls_ (that can also differ slightly from each other e.g. due to rounding) for the same genomic locus that result from expansion of the active region into the edges of the intervals being split.

MergeVCFs as well as GatherVCFs, allows duplicate calls in the final VCF without checks. GatherVCFs does not allow for out-of-genomic-order-inputs and will give an error. However, I'm noticing something interesting (see below).

I would recommend creating intervals without splitting, i.e. with the BALANCING_WITHOUT_INTERVAL_SUBDIVISION option and setting the default of the tool to such to ward against accidental misuse.

**Comment by sooheelee** [comment] 2017-06-07 18:43
I just heard that production is also moving to GatherVCFs. I know that the workflows say that they are using MergeVCFs because of other issues:

```
  # using MergeVcfs instead of GatherVcfs so we can create indices
  # WARNING 2015-10-28 15:01:48 GatherVcfs  Index creation not currently supported when gathering block compressed VCFs.
```

However, I believe we can create an index after gathering with TABIX or other tool

**Comment by sooheelee** [comment] 2017-06-07 18:48
This concern is germane to any WGS analyses and perhaps not concerning for WES analyses. So perhaps our current WDL workflows that use SplitIntervals could expressly state that they are not safe for WGS variant calling analyses.

**Comment by davidbenjamin** [comment] 2017-07-12 19:03
@sooheelee It looks like split2_8.vcf.gz and split3_8.vcf.gz were generated with GATK 3 M2.  In GATK 4 we only emit calls that are within the unpadded read shards, which I believe do not extend past the input intervals.  Thus, as long as `SplitIntervals` returns disjoint subintervals (which it does), different scatters of M2 should produce disjoint calls.  Could you try to reproduce the issue with GATK 4 M2?

**Comment by sooheelee** [comment] 2017-07-12 20:16
Alright. I will assume this is not urgent unless you say otherwise.

**Comment by sooheelee** [comment] 2017-12-06 18:12
I still feel strongly about not using outputs of SplitIntervals with any reassembly caller as these will expand active regions beyond the intervals given. It is thus possible to end up with calls that depend on identical reads. That is, read evidence is being counted twice for different calls and/or we end up with duplicate calls.

**Comment by sooheelee** [comment] 2017-12-06 18:15
@davidbenjamin

**Comment by davidbenjamin** [comment] 2017-12-07 20:43
@sooheelee Do we have a known case in GATK4?  I thought we had some code to avoid it but when I recently looked I couldn't find it.  So perhaps it was a figment of my imagination, in which case it's certainly an issue.

**Comment by ldgauthier** [comment] 2017-12-07 21:01
I'm pretty sure we've done this in the exome production pipeline forever, though not with SplitIntervals.  HaplotypeCaller (and presumably MuTect) will only output calls in the specified region, no matter how much territory goes into the active region.  If a small interval gets split, it will likely have the same active region for both calls.

**Comment by vdauwera** [comment] 2017-12-26 18:43
That's how I remember it as well. If anyone comes with a specific case we can reexamine, but pending that I think it's best to close this. Reopen if you disagree.

**Closed by vdauwera** 2017-12-26 18:43 UTC
