### ISSUE TITLE
New logical name feature in TaggedInputFileArgument breaks hdfs urls that contain port numbers.

### ISSUE THREAD

**Issue by tedsharpe** [broadinstitute/gatk#2000] opened 2016-07-13 20:05 UTC
Trying to use an url of the form hdfs://server:port/path/to/file as an input to a spark program.  This used to work.  Now we're confused by the possibility that we're declaring a logical name.

**Comment by droazen** [comment] 2016-07-13 20:10
I'll work on a quick fix for this, as it's a fairly serious regression.

**Comment by akiezun** [comment] 2016-07-13 20:17
maybe we could use a different character than `:` to separate logical names. Maybe `+` (?) Or hardwire a bunch of protocols like `hdfs`, `file`, `gs`, etc?

**Comment by akiezun** [comment] 2016-07-13 20:18
good idea too

**Comment by droazen** [comment] 2016-07-13 20:21
I think that won't actually work @lbergelson, since we also have to handle the colon for the port numbers.

**Comment by droazen** [comment] 2016-07-13 20:22
According to https://tools.ietf.org/html/rfc3986#section-2, there are many disallowed characters in URIs that we could use as a delimiter for logical name, like |. This would be a syntax change vs. GATK3, however.

**Comment by akiezun** [comment] 2016-07-13 20:22
but the logical name is always first so it can't be confused with anything else

**Comment by akiezun** [comment] 2016-07-13 20:22
syntax is already different `-I:tumor bam` vs `-I tumor:bam`

**Comment by droazen** [comment] 2016-07-13 20:24
yes, that's true

**Comment by lbergelson** [comment] 2016-07-13 20:32
@droazen Maybe I'm misunderstanding, but we'd just split up until a uri specifier?

**Comment by droazen** [comment] 2016-07-13 20:36
@lbergelson The regex you used in the TileDB branch would ignore the colon for the scheme, but split on the colon for the port number (if there is one), wouldn't it?

**Comment by lbergelson** [comment] 2016-07-13 21:06
Might be time to abandon regex and write a few lines of logic...

**Comment by droazen** [comment] 2016-07-13 21:08
I'll have a fix by tomorrow

**Comment by droazen** [comment] 2016-07-13 21:16
This is more serious than just URIs with port numbers, by the way -- I'm pretty sure all URIs are broken on spark right now.

**Comment by tedsharpe** [comment] 2016-07-13 21:22
Yes.  That's true.  All Spark URIs.  I didn't provide an accurate description of the problem.

**Comment by droazen** [comment] 2016-07-14 20:22
We are going to temporarily revert the problematic change until a definitive fix can be developed (https://github.com/broadinstitute/gatk/pull/2007).

**Comment by droazen** [comment] 2017-03-22 20:14
Closing -- this will be solved by hooking up the new barclay argument tagging feature: https://github.com/broadinstitute/gatk/issues/2473

**Closed by droazen** 2017-03-22 20:14 UTC
Labels: bug
