### ISSUE TITLE
document how to add tools in extensions of GATK4

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1397] opened 2015-12-23 17:20 UTC
scenario: someone wants to use gatk4 as a framework and add new tools. They need show on the list of tools etc. They package names are the user's, ie not org.broadinstitute.hellbender*. The way to do this is to extend Main but we have no example and not documentation of this (other that in the Main class, which is not the right place - I think it should be in README or some such).

**Comment by vdauwera** [comment] 2015-12-23 18:12
I recommend putting that in the GitHub wiki.

**Comment by droazen** [comment] 2017-10-17 19:33
Duplicate of https://github.com/broadinstitute/gatk/issues/1016

**Closed by droazen** 2017-10-17 19:33 UTC
Labels: DeveloperDoc
